// Copyright (c) 2026 NorvikOps. All rights reserved.
// SPDX-License-Identifier: Elastic-2.0

package policy

// soaControlTemplate is a static entry from ISO 27001:2022 Annex A.
type soaControlTemplate struct {
	Ref   string
	Group string
	Name  string
}

// ISO27001AnnexAControls contains all 93 controls from ISO 27001:2022 Annex A.
var ISO27001AnnexAControls = []soaControlTemplate{
	// Group 5: Organizational Controls (37)
	{"A.5.1", "5", "Policies for information security"},
	{"A.5.2", "5", "Information security roles and responsibilities"},
	{"A.5.3", "5", "Segregation of duties"},
	{"A.5.4", "5", "Management responsibilities"},
	{"A.5.5", "5", "Contact with authorities"},
	{"A.5.6", "5", "Contact with special interest groups"},
	{"A.5.7", "5", "Threat intelligence"},
	{"A.5.8", "5", "Information security in project management"},
	{"A.5.9", "5", "Inventory of information and other associated assets"},
	{"A.5.10", "5", "Acceptable use of information and other associated assets"},
	{"A.5.11", "5", "Return of assets"},
	{"A.5.12", "5", "Classification of information"},
	{"A.5.13", "5", "Labelling of information"},
	{"A.5.14", "5", "Information transfer"},
	{"A.5.15", "5", "Access control"},
	{"A.5.16", "5", "Identity management"},
	{"A.5.17", "5", "Authentication information"},
	{"A.5.18", "5", "Access rights"},
	{"A.5.19", "5", "Information security in supplier relationships"},
	{"A.5.20", "5", "Addressing information security within supplier agreements"},
	{"A.5.21", "5", "Managing information security in the ICT supply chain"},
	{"A.5.22", "5", "Monitoring, review and change management of supplier services"},
	{"A.5.23", "5", "Information security for use of cloud services"},
	{"A.5.24", "5", "Information security incident management planning and preparation"},
	{"A.5.25", "5", "Assessment and decision on information security events"},
	{"A.5.26", "5", "Response to information security incidents"},
	{"A.5.27", "5", "Learning from information security incidents"},
	{"A.5.28", "5", "Collection of evidence"},
	{"A.5.29", "5", "Information security during disruption"},
	{"A.5.30", "5", "ICT readiness for business continuity"},
	{"A.5.31", "5", "Legal, statutory, regulatory and contractual requirements"},
	{"A.5.32", "5", "Intellectual property rights"},
	{"A.5.33", "5", "Protection of records"},
	{"A.5.34", "5", "Privacy and protection of PII"},
	{"A.5.35", "5", "Independent review of information security"},
	{"A.5.36", "5", "Compliance with policies, rules and standards for information security"},
	{"A.5.37", "5", "Documented operating procedures"},
	// Group 6: People Controls (8)
	{"A.6.1", "6", "Screening"},
	{"A.6.2", "6", "Terms and conditions of employment"},
	{"A.6.3", "6", "Information security awareness, education and training"},
	{"A.6.4", "6", "Disciplinary process"},
	{"A.6.5", "6", "Responsibilities after termination or change of employment"},
	{"A.6.6", "6", "Confidentiality or non-disclosure agreements"},
	{"A.6.7", "6", "Remote working"},
	{"A.6.8", "6", "Information security event reporting"},
	// Group 7: Physical Controls (14)
	{"A.7.1", "7", "Physical security perimeters"},
	{"A.7.2", "7", "Physical entry"},
	{"A.7.3", "7", "Securing offices, rooms and facilities"},
	{"A.7.4", "7", "Physical security monitoring"},
	{"A.7.5", "7", "Protecting against physical and environmental threats"},
	{"A.7.6", "7", "Working in secure areas"},
	{"A.7.7", "7", "Clear desk and clear screen"},
	{"A.7.8", "7", "Equipment siting and protection"},
	{"A.7.9", "7", "Security of assets off-premises"},
	{"A.7.10", "7", "Storage media"},
	{"A.7.11", "7", "Supporting utilities"},
	{"A.7.12", "7", "Cabling security"},
	{"A.7.13", "7", "Equipment maintenance"},
	{"A.7.14", "7", "Secure disposal or re-use of equipment"},
	// Group 8: Technological Controls (34)
	{"A.8.1", "8", "User endpoint devices"},
	{"A.8.2", "8", "Privileged access rights"},
	{"A.8.3", "8", "Information access restriction"},
	{"A.8.4", "8", "Access to source code"},
	{"A.8.5", "8", "Secure authentication"},
	{"A.8.6", "8", "Capacity management"},
	{"A.8.7", "8", "Protection against malware"},
	{"A.8.8", "8", "Management of technical vulnerabilities"},
	{"A.8.9", "8", "Configuration management"},
	{"A.8.10", "8", "Information deletion"},
	{"A.8.11", "8", "Data masking"},
	{"A.8.12", "8", "Data leakage prevention"},
	{"A.8.13", "8", "Information backup"},
	{"A.8.14", "8", "Redundancy of information processing facilities"},
	{"A.8.15", "8", "Logging"},
	{"A.8.16", "8", "Monitoring activities"},
	{"A.8.17", "8", "Clock synchronisation"},
	{"A.8.18", "8", "Use of privileged utility programs"},
	{"A.8.19", "8", "Installation of software on operational systems"},
	{"A.8.20", "8", "Networks security"},
	{"A.8.21", "8", "Security of network services"},
	{"A.8.22", "8", "Segregation of networks"},
	{"A.8.23", "8", "Web filtering"},
	{"A.8.24", "8", "Use of cryptography"},
	{"A.8.25", "8", "Secure development life cycle"},
	{"A.8.26", "8", "Application security requirements"},
	{"A.8.27", "8", "Secure system architecture and engineering principles"},
	{"A.8.28", "8", "Secure coding"},
	{"A.8.29", "8", "Security testing in development and acceptance"},
	{"A.8.30", "8", "Outsourced development"},
	{"A.8.31", "8", "Separation of development, test and production environments"},
	{"A.8.32", "8", "Change management"},
	{"A.8.33", "8", "Test information"},
	{"A.8.34", "8", "Protection of information systems during audit testing"},
}
