{{- if .Values.uploads.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vakt.fullname" . }}-uploads
  labels:
    {{- include "vakt.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.uploads.persistence.storageClass }}
  storageClassName: {{ .Values.uploads.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.uploads.persistence.size | default "5Gi" }}
{{- end }}
