/**
 * R1-18-D4 regression suite — authenticated writes must carry X-CSRF-Token.
 *
 * Seven write paths bypassed `apiFetch` and used a raw `fetch()`, typically
 * because they upload multipart/FormData and nobody wanted to clobber the
 * Content-Type boundary. Without `apiFetch` there is no X-CSRF-Token header,
 * so the double-submit check rejected every one of them with 403 — they were
 * unusable from the day they were introduced, not merely insecure:
 *
 *   1. POST /vaktcomply/controls/:id/evidence/upload   (useUploadEvidence)
 *   2. POST /vaktcomply/controls/:id/evidence-files    (useUploadEvidenceFile)
 *   3. POST /vaktcomply/suppliers/import-csv           (useImportSuppliersCSV)
 *   4. POST /vaktcomply/ai/report                      (AIReportPage)
 *   5. POST /vaktscan/findings/import                  (ImportFindingsDialog)
 *   6. POST /vaktscan/assets/import                    (useImportAssets)
 *   7. POST /vaktscan/assets/import/csv                (CSVImportDialog)
 *
 * Each test below drives the real call site (hook or component) and asserts the
 * request that actually leaves the app carries the header. Reverting any single
 * call site to a raw `fetch()` turns exactly its own test red.
 *
 * The FormData ones additionally assert that NO Content-Type is set: the
 * multipart boundary can only be generated by the browser, and any header we
 * write ourselves replaces it with a boundary-less value the server cannot
 * parse. "Has CSRF" and "has no Content-Type" must both hold — fixing one by
 * breaking the other is not a fix.
 */
import { type ReactElement, type ReactNode } from 'react'
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { renderHook, render, screen, waitFor, fireEvent, act } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { MemoryRouter } from 'react-router-dom'

import { setCsrfToken } from './client'
import { useUploadEvidence } from '../modules/vaktcomply/hooks/useControls'
import { useUploadEvidenceFile } from '../modules/vaktcomply/hooks/useEvidenceFiles'
import { useImportSuppliersCSV } from '../modules/vaktcomply/hooks/useSuppliers'
import { useImportAssets } from '../modules/vaktscan/hooks/useAssets'
import AIReportPage from '../modules/vaktcomply/pages/AIReportPage'
import { CSVImportDialog } from '../shared/components/CSVImportDialog'
import { importFindings } from '../modules/vaktscan/components/ImportFindingsDialog'

const TOKEN = 'csrf-token-under-test'

const realFetch = globalThis.fetch
const realCookie = Object.getOwnPropertyDescriptor(document, 'cookie')

let fetchSpy: ReturnType<typeof vi.fn>

/** Records every call and answers each one with a generic JSON 200. */
function installFetchSpy(): void {
  fetchSpy = vi.fn().mockImplementation(() =>
    Promise.resolve({
      ok: true,
      status: 200,
      statusText: 'OK',
      headers: new Headers({ 'content-type': 'application/json' }),
      json: () => Promise.resolve({ id: 'x', imported: 1, inserted: 1, report: 'text', available: true }),
      clone() {
        return this as unknown as Response
      },
    } as unknown as Response),
  )
  globalThis.fetch = fetchSpy as unknown as typeof fetch
}

/** The request this app made to `path` (suffix match), or undefined. */
function requestTo(path: string): { url: string; init: RequestInit } | undefined {
  for (const call of fetchSpy.mock.calls) {
    const [url, init] = call as [string, RequestInit | undefined]
    if (typeof url === 'string' && url.split('?')[0].endsWith(path)) {
      return { url, init: init ?? {} }
    }
  }
  return undefined
}

function headersOf(init: RequestInit): Record<string, string> {
  return (init.headers ?? {}) as Record<string, string>
}

/** Content-Type lookup that does not care about header casing. */
function contentTypeOf(init: RequestInit): string | undefined {
  const headers = headersOf(init)
  const key = Object.keys(headers).find((k) => k.toLowerCase() === 'content-type')
  return key ? headers[key] : undefined
}

beforeEach(() => {
  Object.defineProperty(document, 'cookie', { value: '', writable: true, configurable: true })
  setCsrfToken(null)
  document.cookie = `csrf_token=${TOKEN}`
  installFetchSpy()
})

afterEach(() => {
  globalThis.fetch = realFetch
  if (realCookie) Object.defineProperty(document, 'cookie', realCookie)
  vi.restoreAllMocks()
})

// ── Hook-driven upload paths ─────────────────────────────────────────────────

function makeWrapper(): ({ children }: { children: ReactNode }) => ReactElement {
  const client = new QueryClient({
    defaultOptions: { queries: { retry: false, gcTime: 0 }, mutations: { retry: false } },
  })
  return function Wrapper({ children }: { children: ReactNode }) {
    return <QueryClientProvider client={client}>{children}</QueryClientProvider>
  }
}

function formDataWithFile(): FormData {
  const fd = new FormData()
  fd.append('file', new File(['content'], 'evidence.pdf', { type: 'application/pdf' }))
  return fd
}

describe('R1-18-D4 — multipart upload hooks send X-CSRF-Token', () => {
  it('1. useUploadEvidence — POST controls/:id/evidence/upload', async () => {
    const { result } = renderHook(() => useUploadEvidence('control-1'), { wrapper: makeWrapper() })

    await act(async () => {
      await result.current.mutateAsync(formDataWithFile())
    })

    const req = requestTo('/vaktcomply/controls/control-1/evidence/upload')
    expect(req, 'no request reached /evidence/upload').toBeDefined()
    expect(headersOf(req!.init)['X-CSRF-Token']).toBe(TOKEN)
    expect(contentTypeOf(req!.init)).toBeUndefined()
    expect(req!.init.body).toBeInstanceOf(FormData)
  })

  it('2. useUploadEvidenceFile — POST controls/:id/evidence-files', async () => {
    const { result } = renderHook(() => useUploadEvidenceFile('control-2'), {
      wrapper: makeWrapper(),
    })

    await act(async () => {
      await result.current.mutateAsync(new File(['x'], 'proof.png', { type: 'image/png' }))
    })

    const req = requestTo('/vaktcomply/controls/control-2/evidence-files')
    expect(req, 'no request reached /evidence-files').toBeDefined()
    expect(headersOf(req!.init)['X-CSRF-Token']).toBe(TOKEN)
    expect(contentTypeOf(req!.init)).toBeUndefined()
  })

  it('3. useImportSuppliersCSV — POST suppliers/import-csv', async () => {
    const { result } = renderHook(() => useImportSuppliersCSV(), { wrapper: makeWrapper() })

    await act(async () => {
      await result.current.mutateAsync(formDataWithFile())
    })

    const req = requestTo('/vaktcomply/suppliers/import-csv')
    expect(req, 'no request reached /suppliers/import-csv').toBeDefined()
    expect(headersOf(req!.init)['X-CSRF-Token']).toBe(TOKEN)
    expect(contentTypeOf(req!.init)).toBeUndefined()
  })

  it('6. useImportAssets — POST vaktscan/assets/import', async () => {
    const { result } = renderHook(() => useImportAssets(), { wrapper: makeWrapper() })

    await act(async () => {
      await result.current.mutateAsync(formDataWithFile())
    })

    const req = requestTo('/vaktscan/assets/import')
    expect(req, 'no request reached /vaktscan/assets/import').toBeDefined()
    expect(headersOf(req!.init)['X-CSRF-Token']).toBe(TOKEN)
    expect(contentTypeOf(req!.init)).toBeUndefined()
  })
})

// ── Component-driven write paths ─────────────────────────────────────────────

describe('R1-18-D4 — component write paths send X-CSRF-Token', () => {
  it('4. AIReportPage — POST vaktcomply/ai/report', async () => {
    render(
      <QueryClientProvider
        client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}
      >
        <MemoryRouter>
          <AIReportPage />
        </MemoryRouter>
      </QueryClientProvider>,
    )

    // The page probes /ai/status first and only renders the type picker when
    // the provider reports available.
    const typeButton = await screen.findByText('Gap-Analyse')
    fireEvent.click(typeButton)
    fireEvent.click(await screen.findByRole('button', { name: /Bericht generieren/i }))

    await waitFor(() => {
      expect(requestTo('/vaktcomply/ai/report')).toBeDefined()
    })
    const req = requestTo('/vaktcomply/ai/report')!
    expect(headersOf(req.init)['X-CSRF-Token']).toBe(TOKEN)
    // JSON body — Content-Type must still be set here.
    expect(contentTypeOf(req.init)).toContain('application/json')
  })

  it('7. CSVImportDialog — POST vaktscan/assets/import/csv', async () => {
    render(
      <CSVImportDialog
        open
        onClose={() => undefined}
        endpoint="/vaktscan/assets/import/csv"
        entityLabel="Assets"
        columns={['name', 'type']}
      />,
    )

    const input = document.querySelector('input[type="file"]')
    expect(input, 'CSVImportDialog has no file input').not.toBeNull()
    fireEvent.change(input!, {
      target: { files: [new File(['name,type\na,server\n'], 'assets.csv', { type: 'text/csv' })] },
    })

    // FileReader is async — the preview step gates the upload button.
    const uploadButton = await screen.findByRole('button', { name: /importieren/i })
    fireEvent.click(uploadButton)

    await waitFor(() => {
      expect(requestTo('/vaktscan/assets/import/csv')).toBeDefined()
    })
    const req = requestTo('/vaktscan/assets/import/csv')!
    expect(headersOf(req.init)['X-CSRF-Token']).toBe(TOKEN)
    expect(contentTypeOf(req.init)).toBeUndefined()
  })

  it('5. ImportFindingsDialog — POST vaktscan/findings/import', async () => {
    // Entered one level below the dialog: the asset picker is a Radix Select,
    // which does not open in jsdom. importFindings() is the exact function the
    // dialog's upload button calls, so the request under test is the real one.
    await importFindings('asset-1', 'sarif', new File(['{}'], 'findings.sarif'))

    const req = requestTo('/vaktscan/findings/import')
    expect(req, 'no request reached /vaktscan/findings/import').toBeDefined()
    expect(headersOf(req!.init)['X-CSRF-Token']).toBe(TOKEN)
    expect(contentTypeOf(req!.init)).toBeUndefined()
    expect(req!.url).toContain('asset_id=asset-1')
  })
})
