-- Backfill descriptions for NIS2 controls
UPDATE ck_controls SET description = v.txt
FROM (VALUES
  ('NIS2-A.1',  'Erstelle und genehmige eine schriftliche Informationssicherheitsrichtlinie. Sie muss Schutzziele, Geltungsbereich, Verantwortlichkeiten und Überprüfungsintervall enthalten. Nachweis: unterschriebenes Richtliniendokument mit Versionsnummer und Genehmigungsdatum.'),
  ('NIS2-A.2',  'Implementiere einen formalen Prozess zur Identifikation, Bewertung und Behandlung von Informationssicherheitsrisiken. Nachweis: Risikomanagement-Prozessbeschreibung, Risikoregister.'),
  ('NIS2-A.3',  'Führe mindestens jährlich eine strukturierte Risikoanalyse durch. Bewerte Eintrittswahrscheinlichkeit und Auswirkung für alle relevanten Bedrohungen. Nachweis: ausgefülltes Risikoregister mit Bewertungsmatrix.'),
  ('NIS2-A.4',  'Definiere für alle identifizierten Risiken konkrete Maßnahmen (Vermeiden, Reduzieren, Übertragen, Akzeptieren) mit Verantwortlichen und Fristen. Nachweis: Risikobehandlungsplan mit Umsetzungsstatus.'),
  ('NIS2-A.5',  'Lege messbare Sicherheitsziele auf Organisations- und Abteilungsebene fest. Stelle sicher, dass die Geschäftsführung die IS-Governance trägt. Nachweis: dokumentierte Sicherheitsziele, Protokolle von Management-Reviews.'),
  ('NIS2-A.6',  'Benenne einen Informationssicherheitsbeauftragten (ISB) und dokumentiere alle sicherheitsrelevanten Rollen und deren Verantwortlichkeiten. Nachweis: Organigramm, Stellenbeschreibungen, Beauftragungsschreiben.'),
  ('NIS2-A.7',  'Überprüfe alle Sicherheitsrichtlinien mindestens jährlich oder nach wesentlichen Änderungen und hole erneute Genehmigung ein. Nachweis: Änderungshistorie der Richtlinien mit Genehmigungsnachweisen.'),
  ('NIS2-A.8',  'Führe ein aktuelles Inventar aller informationsverarbeitenden Assets (Hardware, Software, Daten). Klassifiziere Assets nach Schutzbedarf. Nachweis: Asset-Register mit Klassifizierungsschema.'),
  ('NIS2-A.9',  'Abonniere relevante Bedrohungsinformationen (CERT-Bund, BSI-Warnmeldungen, CVE-Feeds) und integriere sie in den Risikoprozess. Nachweis: Abonnementbestätigung, Prozessdokumentation zur Verarbeitung.'),
  ('NIS2-A.10', 'Identifiziere alle anwendbaren gesetzlichen, regulatorischen und vertraglichen Anforderungen (NIS2, DSGVO, branchenspezifisch) und verfolge deren Einhaltung. Nachweis: Compliance-Register, Auditberichte.'),
  ('NIS2-B.1',  'Erstelle eine schriftliche Incident-Response-Richtlinie mit Klassifizierungsschema, Eskalationspfaden und Reaktionszeiten. Nachweis: genehmigtes Richtliniendokument.'),
  ('NIS2-B.2',  'Implementiere technische Erkennungsmechanismen (SIEM, IDS, Log-Monitoring). Stelle sicher, dass Alarme rund um die Uhr überwacht werden. Nachweis: SIEM-Konfiguration, Monitoring-Dashboard.'),
  ('NIS2-B.3',  'Bilde ein benanntes Incident-Response-Team mit klaren Rollen. Stelle Erreichbarkeit und Eskalationspfade sicher. Nachweis: Teambesetzungsplan, Kontaktliste, Beauftragungsschreiben.'),
  ('NIS2-B.4',  'Definiere ein Klassifizierungsschema (Schweregrade 1–4 o.ä.) mit konkreten Kriterien und daraus abgeleiteten Reaktionszeiten. Nachweis: Klassifizierungsmatrix im Incident-Response-Plan.'),
  ('NIS2-B.5',  'Stelle sicher, dass erhebliche Sicherheitsvorfälle gem. Art. 23 NIS2 innerhalb von 24 Stunden an das BSI/zuständige CSIRT gemeldet werden. Nachweis: Meldeprozess-Dokumentation, ggf. Muster-Meldung.'),
  ('NIS2-B.6',  'Erstelle innerhalb von 72 Stunden nach Ersterkennung einen detaillierten Vorfallsbericht an die Aufsichtsbehörde. Nachweis: Berichtsvorlage, Eskalationsplan mit Fristen.'),
  ('NIS2-B.7',  'Führe nach jedem erheblichen Vorfall eine strukturierte Nachbesprechung (Post-Mortem) durch und dokumentiere Erkenntnisse und Verbesserungsmaßnahmen. Nachweis: Post-Incident-Review-Berichte.'),
  ('NIS2-B.8',  'Dokumentiere interne und externe Kommunikationswege für den Krisenfall inkl. Pressestelle, Juristen, Behörden. Nachweis: Kommunikationsplan mit Kontaktlisten.'),
  ('NIS2-B.9',  'Definiere Verfahren zur gerichtsfesten Sicherung digitaler Beweise bei Vorfällen. Stelle notwendige Tools und Schulung bereit. Nachweis: Forensik-Checkliste, Tool-Dokumentation.'),
  ('NIS2-C.1',  'Erstelle eine BCM-Richtlinie, die Geltungsbereich, Verantwortlichkeiten und Ziele des Business-Continuity-Managements festlegt. Nachweis: genehmigtes BCM-Richtliniendokument.'),
  ('NIS2-C.2',  'Analysiere alle kritischen Geschäftsprozesse hinsichtlich Auswirkung und maximaler Ausfallzeit. Nachweis: BIA-Dokument mit MTPD und MBCO-Angaben.'),
  ('NIS2-C.3',  'Lege für alle kritischen Systeme konkrete Recovery Time Objectives (RTO) und Recovery Point Objectives (RPO) fest. Nachweis: RTO/RPO-Tabelle, abgestimmt mit BIA.'),
  ('NIS2-C.4',  'Definiere Backup-Häufigkeit, Aufbewahrungsdauer, Speicherort (3-2-1-Regel) und Verschlüsselung. Nachweis: Backup-Richtlinie, Backup-Job-Konfiguration.'),
  ('NIS2-C.5',  'Teste Backups mindestens vierteljährlich durch tatsächliche Wiederherstellung. Dokumentiere Ergebnisse. Nachweis: Backup-Testberichte mit Datum und Ergebnis.'),
  ('NIS2-C.6',  'Erstelle einen detaillierten Disaster-Recovery-Plan mit konkreten Wiederherstellungsschritten je Kritisch-System. Nachweis: DR-Plan-Dokument.'),
  ('NIS2-C.7',  'Führe mindestens jährlich einen DR-Test (Tabletop-Übung oder Live-Test) durch. Nachweis: Übungsprotokoll mit Ergebnissen und Verbesserungsmaßnahmen.'),
  ('NIS2-C.8',  'Dokumentiere Kommunikationswege für den Krisenfall: interne Benachrichtigung, externe Kommunikation (Kunden, Medien, Behörden). Nachweis: Kommunikationsplan.'),
  ('NIS2-C.9',  'Implementiere technische Redundanz für kritische Systeme (Failover, Load Balancing, georedundante Standorte). Nachweis: Architektur-Diagramm, SLA-Dokumentation.'),
  ('NIS2-D.1',  'Definiere Mindest-Sicherheitsanforderungen für alle IKT-Lieferanten und Dienstleister. Nachweis: Lieferanten-Sicherheitsrichtlinie.'),
  ('NIS2-D.2',  'Bewerte das Sicherheitsrisiko aller wesentlichen Lieferanten vor Vertragsabschluss und danach jährlich. Nachweis: Lieferanten-Risikobewertungsberichte.'),
  ('NIS2-D.3',  'Verankere verbindliche Sicherheitsanforderungen (DSGVO-AVV, ISO 27001, Auditrechte) in allen IKT-Verträgen. Nachweis: Vertragsklauseln, AVV-Mustervorlage.'),
  ('NIS2-D.4',  'Steuere und überwache Remote-Zugriffe von Lieferanten und externen Dienstleistern. Nachweis: Zugriffskonzept, Protokolle externer Zugriffe.'),
  ('NIS2-D.5',  'Prüfe eingesetzte Open-Source- und Third-Party-Software auf bekannte Schwachstellen (SBOM, Dependency-Scanning). Nachweis: SBOM, Scanner-Berichte.'),
  ('NIS2-D.6',  'Führe vor dem Einsatz neuer IKT-Produkte eine Sicherheitsprüfung durch (Zertifizierungen, Herstellernachweise). Nachweis: Produktprüfungs-Checkliste.'),
  ('NIS2-D.7',  'Überwache laufend Sicherheitsmeldungen und Statusänderungen kritischer Lieferanten. Nachweis: Monitoring-Prozess, Eskalationsverfahren.'),
  ('NIS2-D.8',  'Stelle sicher, dass Sicherheitsanforderungen bei Weitervergabe an Subunternehmer gewahrt bleiben. Nachweis: Outsourcing-Richtlinie, Vertragsklauseln.'),
  ('NIS2-E.1',  'Integriere Sicherheitsanforderungen in alle Phasen des Softwareentwicklungsprozesses (Threat Modeling, Code Review, Security Testing). Nachweis: SDLC-Dokumentation, Review-Nachweise.'),
  ('NIS2-E.2',  'Definiere und prüfe Sicherheitsanforderungen vor Beschaffung neuer IT-Systeme. Nachweis: Beschaffungs-Checkliste mit Sicherheitskriterien.'),
  ('NIS2-E.3',  'Betreibe ein strukturiertes Programm zur Identifikation, Bewertung und Behebung technischer Schwachstellen. Nachweis: Scanner-Berichte, Ticket-System-Auszüge.'),
  ('NIS2-E.4',  'Stelle sicher, dass Sicherheits-Patches für kritische Systeme innerhalb definierter Fristen eingespielt werden (kritisch: ≤72 h). Nachweis: Patch-Berichte, SLA-Dokumentation.'),
  ('NIS2-E.5',  'Führe mindestens jährlich Penetrationstests an kritischen Systemen durch. Nachweis: Pentest-Berichte mit Datum, Scope und Ergebnissen.'),
  ('NIS2-E.6',  'Etabliere einen Prozess zur Entgegennahme und Bearbeitung extern gemeldeter Schwachstellen. Nachweis: Responsible-Disclosure-Policy (z.B. security.txt).'),
  ('NIS2-E.7',  'Stelle sicher, dass alle Änderungen an IT-Systemen genehmigt, getestet und dokumentiert werden. Nachweis: Change-Management-Prozess, Genehmigungsnachweise.'),
  ('NIS2-E.8',  'Segmentiere das Netzwerk nach Schutzbedarf (DMZ, Produktions- vs. Entwicklungsnetz, OT-Trennung). Nachweis: Netzplan, Firewall-Regeln.'),
  ('NIS2-E.9',  'Betreibe Firewalls an allen Netzübergängen nach dem Least-Privilege-Prinzip. Überprüfe Regeln mindestens jährlich. Nachweis: Firewall-Konfiguration, Regelreviews.'),
  ('NIS2-E.10', 'Setze IDS/IPS-Systeme an kritischen Netzpunkten ein und stelle sicher, dass Alarme zeitnah bearbeitet werden. Nachweis: IDS/IPS-Konfiguration, Alarmierungsprotokoll.'),
  ('NIS2-E.11', 'Nutze Hardening-Leitlinien (CIS Benchmarks, BSI SiM) für alle eingesetzten Systeme. Nachweis: Konfigurationsbaselines, Compliance-Scan-Berichte.'),
  ('NIS2-F.1',  'Definiere messbare KPIs für die Sicherheitsleistung (z.B. MTTR, offene Schwachstellen, Patch-Compliance-Rate). Nachweis: KPI-Definition, monatliche Berichte.'),
  ('NIS2-F.2',  'Führe mindestens jährlich interne IS-Audits durch und dokumentiere Befunde und Maßnahmen. Nachweis: Auditplan, Auditberichte.'),
  ('NIS2-F.3',  'Halte mindestens jährlich ein Management-Review der IS-Leistung ab. Nachweis: Meeting-Protokolle, Entscheidungsdokumentation.'),
  ('NIS2-F.4',  'Etabliere einen formalen KVP, der Erkenntnisse aus Audits, Vorfällen und Reviews in konkrete Verbesserungen überführt. Nachweis: Maßnahmenverfolgung (z.B. Ticketsystem).'),
  ('NIS2-F.5',  'Plane externe Audits oder Zertifizierungen (z.B. ISO 27001) als Nachweis gegenüber Kunden und Behörden. Nachweis: Zertifikat, Auditbericht.'),
  ('NIS2-G.1',  'Betreibe ein dauerhaftes Awareness-Programm (Newsletter, Intranet, Poster) zur Sensibilisierung aller Mitarbeitenden. Nachweis: Programmbeschreibung, Materialien.'),
  ('NIS2-G.2',  'Schule alle Mitarbeitenden mindestens jährlich zu grundlegenden Sicherheitsthemen (Phishing, Passwortsicherheit, Datenschutz). Nachweis: Schulungsnachweise, Teilnehmerlisten.'),
  ('NIS2-G.3',  'Biete zusätzliche Schulungen für sicherheitskritische Rollen an (Admins, Entwickler, Management). Nachweis: rollenspezifische Schulungspläne und Teilnahmenachweise.'),
  ('NIS2-G.4',  'Führe regelmäßige (mind. 2x/Jahr) Phishing-Simulationen durch und nutze Ergebnisse für gezielte Nachschulung. Nachweis: Simulationsberichte mit Klickraten und Folgemaßnahmen.'),
  ('NIS2-G.5',  'Lege Mindestanforderungen für Passwörter und Authentifizierung fest (Länge, Komplexität, Wiederverwendung, Passwortmanager). Nachweis: Richtliniendokument, technische Durchsetzung.'),
  ('NIS2-G.6',  'Implementiere E-Mail-Sicherheitsmaßnahmen (SPF, DKIM, DMARC, Anti-Spam, Anti-Phishing). Nachweis: DNS-Einträge, E-Mail-Gateway-Konfiguration.'),
  ('NIS2-G.7',  'Setze Endpoint-Protection-Software auf allen Endgeräten ein und stelle automatische Signatur-Updates sicher. Nachweis: AV-Konfiguration, Scan-Berichte.'),
  ('NIS2-G.8',  'Implementiere EDR-Software zur verhaltensbasierten Erkennung von Angriffen auf Endgeräten. Nachweis: EDR-Konfiguration, Alarmierungsprotokoll.'),
  ('NIS2-G.9',  'Setze Web-Proxy oder DNS-Filtering ein, um den Aufruf schädlicher Websites zu verhindern. Nachweis: Filterlisten-Konfiguration, DNS-Sicherheitsberichte.'),
  ('NIS2-H.1',  'Erstelle eine Richtlinie zu zulässigen kryptographischen Verfahren und deren Einsatzgebieten. Nachweis: genehmigtes Richtliniendokument.'),
  ('NIS2-H.2',  'Dokumentiere den gesamten Lebenszyklus kryptographischer Schlüssel (Generierung, Verteilung, Speicherung, Widerruf, Vernichtung). Nachweis: Schlüsselverwaltungsverfahren, KMS-Konfiguration.'),
  ('NIS2-H.3',  'Verschlüssele alle sensiblen Daten in Ruhe (Datenbanken, Backups, Dateisysteme) mit aktuellen Verfahren (AES-256). Nachweis: Verschlüsselungskonfiguration, Scanner-Berichte.'),
  ('NIS2-H.4',  'Stelle sicher, dass alle Datenübertragungen verschlüsselt erfolgen (TLS 1.2+, keine veralteten Protokolle). Nachweis: TLS-Scan-Bericht (z.B. SSL Labs), Konfigurationsdokumentation.'),
  ('NIS2-H.5',  'Verwalte alle TLS/SSL-Zertifikate zentral, überwache Ablaufdaten und erneuere rechtzeitig. Nachweis: Zertifikatsregister, Erneuerungsprozess.'),
  ('NIS2-H.6',  'Führe eine Liste genehmigter Algorithmen und Schlüssellängen (BSI TR-02102) und schließe veraltete Verfahren (MD5, SHA-1, DES) aus. Nachweis: Algorithmenliste, Konfigurationsprüfung.'),
  ('NIS2-I.1',  'Definiere Sicherheitsanforderungen für alle Phasen des Beschäftigungsverhältnisses (Einstellung, laufend, Austritt). Nachweis: HR-Sicherheitsrichtlinie.'),
  ('NIS2-I.2',  'Führe bei Einstellung und für sicherheitskritische Rollen Hintergrundüberprüfungen durch (soweit gesetzlich zulässig). Nachweis: Screening-Richtlinie, Nachweisarchivierung.'),
  ('NIS2-I.3',  'Kommuniziere eine verbindliche Richtlinie zur akzeptablen Nutzung von IT-Ressourcen an alle Mitarbeitenden. Nachweis: Richtlinie, Unterschriften/Bestätigungen der Mitarbeitenden.'),
  ('NIS2-I.4',  'Stelle sicher, dass beim Austritt alle Zugänge zeitnah gesperrt, Assets zurückgegeben und Wissenstransfer sichergestellt wird. Nachweis: Offboarding-Checkliste.'),
  ('NIS2-I.5',  'Definiere das Prinzip der minimalen Rechtevergabe und dokumentiere den Genehmigungsprozess für Zugriffsrechte. Nachweis: Zugriffskontrollrichtlinie.'),
  ('NIS2-I.6',  'Betreibe ein zentrales IAM-System für die Verwaltung aller Benutzerkonten und -rechte. Nachweis: IAM-Systemdokumentation, Provisionierungsprozess.'),
  ('NIS2-I.7',  'Verwalte privilegierte Konten (Admins, Root) gesondert mit PAM-Lösung, Vier-Augen-Prinzip und vollständigem Logging. Nachweis: PAM-Konfiguration, Zugriffsprotokoll.'),
  ('NIS2-I.8',  'Implementiere rollenbasierte Berechtigungskonzepte für alle kritischen Systeme. Nachweis: Rollenmatrix, Berechtigungskonzept.'),
  ('NIS2-I.9',  'Überprüfe mindestens halbjährlich alle vergebenen Zugriffsrechte auf Aktualität und Notwendigkeit. Nachweis: Prüfprotokolle, Bereinigungsnachweise.'),
  ('NIS2-I.10', 'Sichere Serverräume, Büros und Arbeitsplätze physisch gegen unbefugten Zugang (Zutrittskontrolle, CCTV, Clean-Desk). Nachweis: Zutrittskontrollkonzept, Begehungsprotokoll.'),
  ('NIS2-I.11', 'Kennzeichne alle Hardware-Assets, erfasse sie im Inventar und stelle datensichere Entsorgung sicher (z.B. DSGVO-konformes Löschen). Nachweis: Asset-Register, Entsorgungsnachweise.'),
  ('NIS2-I.12', 'Verwalte Mobilgeräte über MDM-Lösung, setze Geräteverschlüsselung und Remote-Wipe durch. Nachweis: MDM-Konfiguration, BYOD-Richtlinie.'),
  ('NIS2-I.13', 'Protokolliere sicherheitsrelevante Ereignisse auf allen kritischen Systemen und überwache zentral via SIEM. Nachweis: Log-Konfiguration, SIEM-Architektur, Aufbewahrungsrichtlinie.'),
  ('NIS2-J.1',  'Erzwinge MFA für alle Benutzer bei Zugriff auf Unternehmensanwendungen und -systeme. Nachweis: MFA-Konfiguration, Ausnahmeliste mit Begründungen.'),
  ('NIS2-J.2',  'Stelle sicher, dass Administratoren und Remote-Nutzer ausnahmslos MFA verwenden. Nachweis: PAM-Konfiguration, VPN-Zugangsprotokolle.'),
  ('NIS2-J.3',  'Definiere zulässige Methoden und Anforderungen für Remote-Zugang (VPN, Zero Trust, MFA, Gerätezertifikate). Nachweis: Remote-Access-Richtlinie.'),
  ('NIS2-J.4',  'Setze ein verschlüsseltes VPN oder Zero-Trust-Netzwerkzugangslösung für alle Remote-Verbindungen ein. Nachweis: VPN-Konfiguration, Zertifikatsdokumentation.'),
  ('NIS2-J.5',  'Nutze ausschließlich verschlüsselte Kommunikationstools für dienstliche Kommunikation (Signal, Teams mit E2E, etc.). Nachweis: Tool-Richtlinie, Konfiguration.'),
  ('NIS2-J.6',  'Stelle sicher, dass Remote-Endgeräte Sicherheitsanforderungen erfüllen (Verschlüsselung, aktuelle AV, MDM). Nachweis: Endpoint-Compliance-Berichte.'),
  ('NIS2-J.7',  'Konfiguriere mobile Geräte mit Bildschirmsperre, Verschlüsselung und Remote-Wipe-Fähigkeit. Nachweis: MDM-Konfiguration, Compliance-Bericht.'),
  ('NIS2-J.8',  'Halte Notfallkommunikationsmittel bereit, die unabhängig von der normalen IT-Infrastruktur funktionieren (Satellitentelefon, Out-of-Band-Kommunikation). Nachweis: Inventarliste, Testprotokoll.')
) AS v(control_id, txt)
WHERE ck_controls.control_id = v.control_id
  AND (ck_controls.description IS NULL OR ck_controls.description = '');

-- Backfill descriptions for ISO 27001 controls
UPDATE ck_controls SET description = v.txt
FROM (VALUES
  ('A.5.1',    'Definiere den Rahmen für alle IS-Richtlinien der Organisation.'),
  ('A.5.1.1',  'Erstelle ein vollständiges Set genehmigter IS-Richtlinien. Nachweis: aktuelle, unterschriebene Richtliniendokumente.'),
  ('A.5.1.2',  'Überprüfe alle Richtlinien mindestens jährlich. Nachweis: Revisionshistorie mit Datum und Genehmigung.'),
  ('A.6.1',    'Stelle sicher, dass IS-Verantwortlichkeiten klar geregelt sind.'),
  ('A.6.1.1',  'Weise IS-Rollen (ISB, Datenschutzbeauftragter, etc.) explizit zu. Nachweis: Stellenbeschreibungen, Beauftragungsschreiben.'),
  ('A.6.1.2',  'Trenne unvereinbare Aufgaben (z.B. Entwicklung/Freigabe). Nachweis: Rollenmatrix mit Trennungsnachweis.'),
  ('A.6.1.3',  'Pflege aktuelle Kontaktinformationen zu relevanten Behörden (BSI, Datenschutzbehörden). Nachweis: Kontaktliste.'),
  ('A.6.1.5',  'Integriere IS-Anforderungen in alle Projektprozesse. Nachweis: Projektcheckliste mit IS-Punkten.'),
  ('A.6.2',    'Manage Risiken durch mobile Geräte und Heimarbeit.'),
  ('A.6.2.1',  'Definiere zulässige Nutzung und Sicherheitsanforderungen für mobile Geräte. Nachweis: MDM-Konfiguration, Richtliniendokument.'),
  ('A.6.2.2',  'Stelle sichere Arbeitsmöglichkeiten für Heimarbeitsplätze sicher. Nachweis: Telearbeitsrichtlinie, VPN-Konfiguration.'),
  ('A.8.1',    'Inventarisiere und klassifiziere alle Informationsassets.'),
  ('A.8.1.1',  'Führe ein vollständiges, aktuelles Asset-Register. Nachweis: Asset-Inventar mit letztem Aktualisierungsdatum.'),
  ('A.8.1.2',  'Weise jedem Asset einen verantwortlichen Eigentümer zu. Nachweis: Asset-Register mit Eigentümerfeld.'),
  ('A.8.1.3',  'Dokumentiere akzeptable Nutzungsregeln für alle Asset-Klassen. Nachweis: Acceptable-Use-Policy.'),
  ('A.8.1.4',  'Stelle Rückgabe aller Assets bei Beschäftigungsende sicher. Nachweis: Offboarding-Checkliste.'),
  ('A.9.1',    'Definiere Zugangskontrollrichtlinie basierend auf Geschäftsbedarf.'),
  ('A.9.1.1',  'Erstelle eine schriftliche Zugangskontrollrichtlinie (Need-to-know, Least Privilege). Nachweis: genehmigtes Dokument.'),
  ('A.9.1.2',  'Beschränke Netzwerkzugänge auf autorisierte Nutzer und Geräte. Nachweis: NAC-Konfiguration, Firewall-Regeln.'),
  ('A.9.2',    'Manage Benutzerkonten über den gesamten Lebenszyklus.'),
  ('A.9.2.1',  'Formalisiere Onboarding/Offboarding-Prozesse für Konten. Nachweis: Provisionierungs-Workflow.'),
  ('A.9.2.2',  'Stelle sicher, dass Zugriffsrechte nur nach Genehmigung erteilt werden. Nachweis: Genehmigungsprotokoll.'),
  ('A.9.2.3',  'Verwalte Admin-Rechte restriktiv mit PAM-Lösung. Nachweis: PAM-Konfiguration, Zugriffsprotokoll.'),
  ('A.9.2.5',  'Überprüfe Zugriffsrechte halbjährlich auf Aktualität. Nachweis: Review-Protokolle.'),
  ('A.9.4',    'Sichere Systemzugänge durch technische Maßnahmen.'),
  ('A.9.4.1',  'Setze Least-Privilege auf Applikationsebene durch. Nachweis: Berechtigungskonzept.'),
  ('A.9.4.2',  'Erzwinge MFA und sichere Login-Mechanismen. Nachweis: MFA-Konfiguration.'),
  ('A.9.4.3',  'Setze einen Passwort-Manager oder Single-Sign-On ein. Nachweis: Tool-Konfiguration, Richtlinie.'),
  ('A.10.1',   'Stelle den richtigen Einsatz von Kryptographie sicher.'),
  ('A.10.1.1', 'Definiere zulässige Algorithmen, Schlüssellängen und Einsatzgebiete. Nachweis: Kryptographierichtlinie.'),
  ('A.10.1.2', 'Dokumentiere Schlüssellebenszyklus (Generierung, Verteilung, Widerruf). Nachweis: Key-Management-Prozess.'),
  ('A.12.1',   'Dokumentiere und manage IT-Betriebsprozesse.'),
  ('A.12.1.1', 'Erstelle schriftliche Betriebshandbücher für alle kritischen Systeme. Nachweis: Betriebsdokumentation.'),
  ('A.12.1.2', 'Stelle sicher, dass alle IT-Änderungen geplant, genehmigt und dokumentiert werden. Nachweis: Change-Tickets.'),
  ('A.12.3',   'Stelle Datenverfügbarkeit durch regelmäßige Backups sicher.'),
  ('A.12.3.1', 'Implementiere automatisierte Backups nach 3-2-1-Prinzip. Nachweis: Backup-Job-Konfiguration, Testberichte.'),
  ('A.12.6',   'Reduziere Angriffsfläche durch zeitnahes Schwachstellenmanagement.'),
  ('A.12.6.1', 'Scanne regelmäßig auf Schwachstellen und behebe kritische innerhalb definierter Fristen. Nachweis: Scanner-Berichte, Patch-Protokoll.'),
  ('A.14.1',   'Definiere IS-Anforderungen bei Beschaffung und Entwicklung.'),
  ('A.14.1.1', 'Dokumentiere IS-Anforderungen in Pflichtenheften. Nachweis: Anforderungsdokument.'),
  ('A.14.1.2', 'Sichere Web-Dienste gegen OWASP Top 10. Nachweis: Pentest-Bericht, WAF-Konfiguration.'),
  ('A.14.2',   'Integriere Sicherheit in den gesamten SDLC.'),
  ('A.14.2.1', 'Erstelle und kommuniziere Secure-Coding-Richtlinien. Nachweis: Richtliniendokument, Schulungsnachweise.'),
  ('A.14.2.8', 'Führe Sicherheitstests (SAST, DAST, Pentest) vor Releases durch. Nachweis: Testberichte.'),
  ('A.16.1',   'Etabliere einen strukturierten Prozess zur Vorfallbehandlung.'),
  ('A.16.1.1', 'Definiere klare Rollen und Abläufe für Vorfallreaktionen. Nachweis: IR-Plan, Teambesetzungsplan.'),
  ('A.16.1.2', 'Etabliere einfache Meldekanäle für alle Mitarbeitenden. Nachweis: Meldeprozess, Kontaktinfos.'),
  ('A.16.1.4', 'Stelle sicher, dass Ereignisse zeitnah klassifiziert werden. Nachweis: Klassifizierungsmatrix.'),
  ('A.16.1.5', 'Definiere konkrete Reaktionsschritte je Vorfallklasse. Nachweis: IR-Playbooks.'),
  ('A.16.1.6', 'Führe Post-Incident-Reviews durch und leite Verbesserungen ab. Nachweis: Review-Berichte.'),
  ('A.17.1',   'Stelle IS-Kontinuität im Krisenfall sicher.'),
  ('A.17.1.1', 'Erstelle BCM-Plan mit IS-Komponente. Nachweis: BCM-Plan-Dokument.'),
  ('A.17.1.2', 'Setze BCM-Maßnahmen technisch und organisatorisch um. Nachweis: Implementierungsnachweis.'),
  ('A.17.1.3', 'Teste und überprüfe BCM-Pläne mindestens jährlich. Nachweis: Testberichte.'),
  ('A.18.1',   'Identifiziere und erfülle alle anwendbaren Rechtspflichten.'),
  ('A.18.1.1', 'Pflege ein Compliance-Register aller relevanten Gesetze und Verträge. Nachweis: Compliance-Register.'),
  ('A.18.1.3', 'Stelle Aufbewahrung und Schutz von Aufzeichnungen gem. gesetzlicher Fristen sicher. Nachweis: Aufbewahrungsrichtlinie.'),
  ('A.18.1.4', 'Stelle DSGVO-Konformität sicher. Nachweis: Verzeichnis der Verarbeitungstätigkeiten, DSFA.'),
  ('A.18.2',   'Prüfe regelmäßig die Einhaltung der IS-Vorgaben.'),
  ('A.18.2.2', 'Überprüfe technische Systeme auf Konformität mit IS-Richtlinien. Nachweis: Compliance-Scan-Berichte.')
) AS v(control_id, txt)
WHERE ck_controls.control_id = v.control_id
  AND (ck_controls.description IS NULL OR ck_controls.description = '');
