{{- if .Values.ollama.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vakt.fullname" . }}-ollama
  labels:
    {{- include "vakt.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  type: ClusterIP
  ports:
    - port: 11434
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vakt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
{{- end }}
