// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hr.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHREmployees = `-- name: CountHREmployees :one
SELECT COUNT(*) FROM hr_employees WHERE org_id = $1
`

func (q *Queries) CountHREmployees(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRow(ctx, countHREmployees, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHRChecklist = `-- name: CreateHRChecklist :one
INSERT INTO hr_checklists (org_id, type, name, items)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, type, name, items, created_at, updated_at
`

type CreateHRChecklistParams struct {
	OrgID string          `json:"org_id"`
	Type  string          `json:"type"`
	Name  string          `json:"name"`
	Items json.RawMessage `json:"items"`
}

func (q *Queries) CreateHRChecklist(ctx context.Context, arg CreateHRChecklistParams) (HrChecklists, error) {
	row := q.db.QueryRow(ctx, createHRChecklist,
		arg.OrgID,
		arg.Type,
		arg.Name,
		arg.Items,
	)
	var i HrChecklists
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Type,
		&i.Name,
		&i.Items,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createHREmployee = `-- name: CreateHREmployee :one
INSERT INTO hr_employees (org_id, first_name, last_name, email, department, role, start_date, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, first_name, last_name, email, department, role,
          start_date, end_date, status, notes, created_at, updated_at
`

type CreateHREmployeeParams struct {
	OrgID      string      `json:"org_id"`
	FirstName  string      `json:"first_name"`
	LastName   string      `json:"last_name"`
	Email      string      `json:"email"`
	Department pgtype.Text `json:"department"`
	Role       pgtype.Text `json:"role"`
	StartDate  pgtype.Date `json:"start_date"`
	Notes      pgtype.Text `json:"notes"`
}

func (q *Queries) CreateHREmployee(ctx context.Context, arg CreateHREmployeeParams) (HrEmployees, error) {
	row := q.db.QueryRow(ctx, createHREmployee,
		arg.OrgID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Department,
		arg.Role,
		arg.StartDate,
		arg.Notes,
	)
	var i HrEmployees
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Department,
		&i.Role,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHRChecklist = `-- name: DeleteHRChecklist :exec
DELETE FROM hr_checklists WHERE org_id = $1 AND id = $2
`

type DeleteHRChecklistParams struct {
	OrgID string `json:"org_id"`
	ID    string `json:"id"`
}

func (q *Queries) DeleteHRChecklist(ctx context.Context, arg DeleteHRChecklistParams) error {
	_, err := q.db.Exec(ctx, deleteHRChecklist, arg.OrgID, arg.ID)
	return err
}

const deleteHREmployee = `-- name: DeleteHREmployee :exec
DELETE FROM hr_employees WHERE org_id = $1 AND id = $2
`

type DeleteHREmployeeParams struct {
	OrgID string `json:"org_id"`
	ID    string `json:"id"`
}

func (q *Queries) DeleteHREmployee(ctx context.Context, arg DeleteHREmployeeParams) error {
	_, err := q.db.Exec(ctx, deleteHREmployee, arg.OrgID, arg.ID)
	return err
}

const firstHRChecklistByType = `-- name: FirstHRChecklistByType :one
SELECT id, org_id, type, name, items, created_at, updated_at
FROM hr_checklists
WHERE org_id = $1 AND type = $2
ORDER BY created_at ASC
LIMIT 1
`

type FirstHRChecklistByTypeParams struct {
	OrgID string `json:"org_id"`
	Type  string `json:"type"`
}

func (q *Queries) FirstHRChecklistByType(ctx context.Context, arg FirstHRChecklistByTypeParams) (HrChecklists, error) {
	row := q.db.QueryRow(ctx, firstHRChecklistByType, arg.OrgID, arg.Type)
	var i HrChecklists
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Type,
		&i.Name,
		&i.Items,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHRChecklist = `-- name: GetHRChecklist :one
SELECT id, org_id, type, name, items, created_at, updated_at
FROM hr_checklists
WHERE org_id = $1 AND id = $2
`

type GetHRChecklistParams struct {
	OrgID string `json:"org_id"`
	ID    string `json:"id"`
}

func (q *Queries) GetHRChecklist(ctx context.Context, arg GetHRChecklistParams) (HrChecklists, error) {
	row := q.db.QueryRow(ctx, getHRChecklist, arg.OrgID, arg.ID)
	var i HrChecklists
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Type,
		&i.Name,
		&i.Items,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHRChecklistRun = `-- name: GetHRChecklistRun :one
SELECT id, org_id, employee_id, checklist_id, status, completed_items,
       started_at, completed_at, created_at, updated_at
FROM hr_checklist_runs
WHERE org_id = $1 AND id = $2
`

type GetHRChecklistRunParams struct {
	OrgID string `json:"org_id"`
	ID    string `json:"id"`
}

func (q *Queries) GetHRChecklistRun(ctx context.Context, arg GetHRChecklistRunParams) (HrChecklistRuns, error) {
	row := q.db.QueryRow(ctx, getHRChecklistRun, arg.OrgID, arg.ID)
	var i HrChecklistRuns
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.EmployeeID,
		&i.ChecklistID,
		&i.Status,
		&i.CompletedItems,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHREmployee = `-- name: GetHREmployee :one
SELECT id, org_id, first_name, last_name, email, department, role,
       start_date, end_date, status, notes, created_at, updated_at
FROM hr_employees
WHERE org_id = $1 AND id = $2
`

type GetHREmployeeParams struct {
	OrgID string `json:"org_id"`
	ID    string `json:"id"`
}

func (q *Queries) GetHREmployee(ctx context.Context, arg GetHREmployeeParams) (HrEmployees, error) {
	row := q.db.QueryRow(ctx, getHREmployee, arg.OrgID, arg.ID)
	var i HrEmployees
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Department,
		&i.Role,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHREmployeeByEmail = `-- name: GetHREmployeeByEmail :one
SELECT id, org_id, first_name, last_name, email, department, role,
       start_date, end_date, status, notes, created_at, updated_at
FROM hr_employees
WHERE org_id = $1 AND email = $2
`

type GetHREmployeeByEmailParams struct {
	OrgID string `json:"org_id"`
	Email string `json:"email"`
}

func (q *Queries) GetHREmployeeByEmail(ctx context.Context, arg GetHREmployeeByEmailParams) (HrEmployees, error) {
	row := q.db.QueryRow(ctx, getHREmployeeByEmail, arg.OrgID, arg.Email)
	var i HrEmployees
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Department,
		&i.Role,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertHRRunEvent = `-- name: InsertHRRunEvent :exec
INSERT INTO hr_run_events (run_id, org_id, step_id, completed_by)
VALUES ($1, $2, $3, $4)
`

type InsertHRRunEventParams struct {
	RunID       string `json:"run_id"`
	OrgID       string `json:"org_id"`
	StepID      string `json:"step_id"`
	CompletedBy string `json:"completed_by"`
}

func (q *Queries) InsertHRRunEvent(ctx context.Context, arg InsertHRRunEventParams) error {
	_, err := q.db.Exec(ctx, insertHRRunEvent,
		arg.RunID,
		arg.OrgID,
		arg.StepID,
		arg.CompletedBy,
	)
	return err
}

const listHRChecklistRuns = `-- name: ListHRChecklistRuns :many
SELECT id, org_id, employee_id, checklist_id, status, completed_items,
       started_at, completed_at, created_at, updated_at
FROM hr_checklist_runs
WHERE org_id = $1 AND employee_id = $2
ORDER BY started_at DESC
`

type ListHRChecklistRunsParams struct {
	OrgID      string `json:"org_id"`
	EmployeeID string `json:"employee_id"`
}

func (q *Queries) ListHRChecklistRuns(ctx context.Context, arg ListHRChecklistRunsParams) ([]HrChecklistRuns, error) {
	rows, err := q.db.Query(ctx, listHRChecklistRuns, arg.OrgID, arg.EmployeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HrChecklistRuns{}
	for rows.Next() {
		var i HrChecklistRuns
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.EmployeeID,
			&i.ChecklistID,
			&i.Status,
			&i.CompletedItems,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHRChecklists = `-- name: ListHRChecklists :many
SELECT id, org_id, type, name, items, created_at, updated_at
FROM hr_checklists
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListHRChecklists(ctx context.Context, orgID string) ([]HrChecklists, error) {
	rows, err := q.db.Query(ctx, listHRChecklists, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HrChecklists{}
	for rows.Next() {
		var i HrChecklists
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Type,
			&i.Name,
			&i.Items,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHREmployees = `-- name: ListHREmployees :many
SELECT id, org_id, first_name, last_name, email, department, role,
       start_date, end_date, status, notes, created_at, updated_at
FROM hr_employees
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListHREmployeesParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListHREmployees(ctx context.Context, arg ListHREmployeesParams) ([]HrEmployees, error) {
	rows, err := q.db.Query(ctx, listHREmployees, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HrEmployees{}
	for rows.Next() {
		var i HrEmployees
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Department,
			&i.Role,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHRRunEvents = `-- name: ListHRRunEvents :many
SELECT id, run_id, org_id, step_id, completed_by, completed_at
FROM hr_run_events
WHERE org_id = $1 AND run_id = $2
ORDER BY completed_at ASC
`

type ListHRRunEventsParams struct {
	OrgID string `json:"org_id"`
	RunID string `json:"run_id"`
}

func (q *Queries) ListHRRunEvents(ctx context.Context, arg ListHRRunEventsParams) ([]HrRunEvents, error) {
	rows, err := q.db.Query(ctx, listHRRunEvents, arg.OrgID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HrRunEvents{}
	for rows.Next() {
		var i HrRunEvents
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.OrgID,
			&i.StepID,
			&i.CompletedBy,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setHREmployeeStatus = `-- name: SetHREmployeeStatus :exec
UPDATE hr_employees
SET status = $3, updated_at = now()
WHERE org_id = $1 AND id = $2
`

type SetHREmployeeStatusParams struct {
	OrgID  string `json:"org_id"`
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetHREmployeeStatus(ctx context.Context, arg SetHREmployeeStatusParams) error {
	_, err := q.db.Exec(ctx, setHREmployeeStatus, arg.OrgID, arg.ID, arg.Status)
	return err
}

const startHRChecklistRun = `-- name: StartHRChecklistRun :one
INSERT INTO hr_checklist_runs (org_id, employee_id, checklist_id)
VALUES ($1, $2, $3)
RETURNING id, org_id, employee_id, checklist_id, status, completed_items,
          started_at, completed_at, created_at, updated_at
`

type StartHRChecklistRunParams struct {
	OrgID       string `json:"org_id"`
	EmployeeID  string `json:"employee_id"`
	ChecklistID string `json:"checklist_id"`
}

func (q *Queries) StartHRChecklistRun(ctx context.Context, arg StartHRChecklistRunParams) (HrChecklistRuns, error) {
	row := q.db.QueryRow(ctx, startHRChecklistRun, arg.OrgID, arg.EmployeeID, arg.ChecklistID)
	var i HrChecklistRuns
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.EmployeeID,
		&i.ChecklistID,
		&i.Status,
		&i.CompletedItems,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHRChecklistRun = `-- name: UpdateHRChecklistRun :one
UPDATE hr_checklist_runs
SET completed_items = $3,
    status          = $4,
    completed_at    = $5,
    updated_at      = now()
WHERE org_id = $1 AND id = $2
RETURNING id, org_id, employee_id, checklist_id, status, completed_items,
          started_at, completed_at, created_at, updated_at
`

type UpdateHRChecklistRunParams struct {
	OrgID          string             `json:"org_id"`
	ID             string             `json:"id"`
	CompletedItems json.RawMessage    `json:"completed_items"`
	Status         string             `json:"status"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateHRChecklistRun(ctx context.Context, arg UpdateHRChecklistRunParams) (HrChecklistRuns, error) {
	row := q.db.QueryRow(ctx, updateHRChecklistRun,
		arg.OrgID,
		arg.ID,
		arg.CompletedItems,
		arg.Status,
		arg.CompletedAt,
	)
	var i HrChecklistRuns
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.EmployeeID,
		&i.ChecklistID,
		&i.Status,
		&i.CompletedItems,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHREmployee = `-- name: UpdateHREmployee :one
UPDATE hr_employees
SET first_name = $3,
    last_name  = $4,
    department = $5,
    role       = $6,
    end_date   = $7,
    status     = $8,
    notes      = $9,
    updated_at = now()
WHERE org_id = $1 AND id = $2
RETURNING id, org_id, first_name, last_name, email, department, role,
          start_date, end_date, status, notes, created_at, updated_at
`

type UpdateHREmployeeParams struct {
	OrgID      string      `json:"org_id"`
	ID         string      `json:"id"`
	FirstName  string      `json:"first_name"`
	LastName   string      `json:"last_name"`
	Department pgtype.Text `json:"department"`
	Role       pgtype.Text `json:"role"`
	EndDate    pgtype.Date `json:"end_date"`
	Status     string      `json:"status"`
	Notes      pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateHREmployee(ctx context.Context, arg UpdateHREmployeeParams) (HrEmployees, error) {
	row := q.db.QueryRow(ctx, updateHREmployee,
		arg.OrgID,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Department,
		arg.Role,
		arg.EndDate,
		arg.Status,
		arg.Notes,
	)
	var i HrEmployees
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Department,
		&i.Role,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
