// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CkCheckType string

const (
	CkCheckTypeHttpEndpoint      CkCheckType = "http_endpoint"
	CkCheckTypeTrivyNoCritical   CkCheckType = "trivy_no_critical"
	CkCheckTypeEvidenceFreshness CkCheckType = "evidence_freshness"
	CkCheckTypeCustomScript      CkCheckType = "custom_script"
)

func (e *CkCheckType) Scan(src any) error {
	switch s := src.(type) {
	case []byte:
		*e = CkCheckType(s)
	case string:
		*e = CkCheckType(s)
	default:
		return fmt.Errorf("unsupported scan type for CkCheckType: %T", src)
	}
	return nil
}

type NullCkCheckType struct {
	CkCheckType CkCheckType `json:"ck_check_type"`
	Valid       bool        `json:"valid"` // Valid is true if CkCheckType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCkCheckType) Scan(value any) error {
	if value == nil {
		ns.CkCheckType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CkCheckType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCkCheckType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CkCheckType), nil
}

type AlertDeliveryLog struct {
	ID           string             `json:"id"`
	OrgID        string             `json:"org_id"`
	ChannelID    pgtype.UUID        `json:"channel_id"`
	Event        string             `json:"event"`
	Payload      json.RawMessage    `json:"payload"`
	Status       string             `json:"status"`
	ResponseCode pgtype.Int4        `json:"response_code"`
	SentAt       pgtype.Timestamptz `json:"sent_at"`
}

type ApiKeys struct {
	ID         string             `json:"id"`
	OrgID      string             `json:"org_id"`
	CreatedBy  string             `json:"created_by"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	KeyPrefix  string             `json:"key_prefix"`
	Scopes     []string           `json:"scopes"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID           string             `json:"id"`
	OrgID        string             `json:"org_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	UserEmail    pgtype.Text        `json:"user_email"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.Text        `json:"resource_id"`
	ResourceName pgtype.Text        `json:"resource_name"`
	Details      []byte             `json:"details"`
	IpAddress    pgtype.Text        `json:"ip_address"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AuditLogs struct {
	ID           string             `json:"id"`
	OrgID        string             `json:"org_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.Text        `json:"resource_id"`
	IpAddress    pgtype.Text        `json:"ip_address"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	StatusCode   pgtype.Int4        `json:"status_code"`
	Timestamp    pgtype.Timestamptz `json:"timestamp"`
}

type AuditorInvites struct {
	ID         string             `json:"id"`
	OrgID      string             `json:"org_id"`
	Email      string             `json:"email"`
	TokenHash  string             `json:"token_hash"`
	InvitedBy  pgtype.UUID        `json:"invited_by"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuditorSessions struct {
	ID           string             `json:"id"`
	OrgID        string             `json:"org_id"`
	InviteID     string             `json:"invite_id"`
	TokenHash    string             `json:"token_hash"`
	AuditorEmail string             `json:"auditor_email"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AuthOidcStates struct {
	State      string             `json:"state"`
	Provider   string             `json:"provider"`
	RedirectTo pgtype.Text        `json:"redirect_to"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuthRecoveryCodes struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BackupLog struct {
	ID         string             `json:"id"`
	OrgID      string             `json:"org_id"`
	BackedUpAt pgtype.Timestamptz `json:"backed_up_at"`
}

type BsiAdvisories struct {
	ID          string             `json:"id"`
	BsiID       string             `json:"bsi_id"`
	Title       string             `json:"title"`
	Summary     pgtype.Text        `json:"summary"`
	Severity    string             `json:"severity"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	Url         pgtype.Text        `json:"url"`
	CveIds      []string           `json:"cve_ids"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type CkAccessReviewCampaigns struct {
	ID            string             `json:"id"`
	OrgID         string             `json:"org_id"`
	Title         string             `json:"title"`
	Description   pgtype.Text        `json:"description"`
	Status        string             `json:"status"`
	ReviewerEmail string             `json:"reviewer_email"`
	Scope         pgtype.Text        `json:"scope"`
	DueDate       pgtype.Timestamptz `json:"due_date"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	CreatedBy     pgtype.Text        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type CkAccessReviewItems struct {
	ID              string             `json:"id"`
	CampaignID      string             `json:"campaign_id"`
	OrgID           string             `json:"org_id"`
	UserEmail       string             `json:"user_email"`
	AccessLevel     string             `json:"access_level"`
	Decision        string             `json:"decision"`
	ReviewerComment pgtype.Text        `json:"reviewer_comment"`
	DecidedAt       pgtype.Timestamptz `json:"decided_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type CkAiClassifications struct {
	ID            string             `json:"id"`
	OrgID         string             `json:"org_id"`
	AiSystemID    string             `json:"ai_system_id"`
	RiskClass     string             `json:"risk_class"`
	Rationale     pgtype.Text        `json:"rationale"`
	ClassifiedBy  pgtype.Text        `json:"classified_by"`
	WizardAnswers []byte             `json:"wizard_answers"`
	ClassifiedAt  pgtype.Timestamptz `json:"classified_at"`
}

type CkAiDocumentation struct {
	ID                 string             `json:"id"`
	OrgID              string             `json:"org_id"`
	AiSystemID         string             `json:"ai_system_id"`
	Version            int32              `json:"version"`
	SystemDescription  pgtype.Text        `json:"system_description"`
	IntendedPurpose    pgtype.Text        `json:"intended_purpose"`
	TrainingData       pgtype.Text        `json:"training_data"`
	DataQuality        pgtype.Text        `json:"data_quality"`
	PerformanceMetrics pgtype.Text        `json:"performance_metrics"`
	SystemLimits       pgtype.Text        `json:"system_limits"`
	RiskManagement     pgtype.Text        `json:"risk_management"`
	HumanOversight     pgtype.Text        `json:"human_oversight"`
	LoggingAuditTrail  pgtype.Text        `json:"logging_audit_trail"`
	AuthoredBy         pgtype.Text        `json:"authored_by"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type CkAiSystems struct {
	ID                      string             `json:"id"`
	OrgID                   string             `json:"org_id"`
	Name                    string             `json:"name"`
	Description             pgtype.Text        `json:"description"`
	Provider                pgtype.Text        `json:"provider"`
	UseCase                 pgtype.Text        `json:"use_case"`
	AffectedGroups          pgtype.Text        `json:"affected_groups"`
	AutonomyLevel           string             `json:"autonomy_level"`
	InProductionSince       pgtype.Date        `json:"in_production_since"`
	Status                  string             `json:"status"`
	RiskClass               pgtype.Text        `json:"risk_class"`
	ClassificationRationale pgtype.Text        `json:"classification_rationale"`
	ClassifiedAt            pgtype.Timestamptz `json:"classified_at"`
	ClassifiedBy            pgtype.Text        `json:"classified_by"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type CkAuditMilestones struct {
	ID            string             `json:"id"`
	OrgID         string             `json:"org_id"`
	FrameworkID   pgtype.UUID        `json:"framework_id"`
	Title         string             `json:"title"`
	Description   pgtype.Text        `json:"description"`
	MilestoneDate pgtype.Date        `json:"milestone_date"`
	MilestoneType string             `json:"milestone_type"`
	Status        string             `json:"status"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type CkAuditRecords struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	Title           string             `json:"title"`
	Scope           string             `json:"scope"`
	Auditor         string             `json:"auditor"`
	AuditDate       pgtype.Date        `json:"audit_date"`
	Status          string             `json:"status"`
	Findings        string             `json:"findings"`
	Recommendations string             `json:"recommendations"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CkAuditorLinks struct {
	ID             string             `json:"id"`
	OrgID          string             `json:"org_id"`
	FrameworkID    pgtype.UUID        `json:"framework_id"`
	TokenHash      string             `json:"token_hash"`
	CreatedBy      string             `json:"created_by"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	UsedCount      int32              `json:"used_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Label          string             `json:"label"`
	FrameworkIds   json.RawMessage    `json:"framework_ids"`
	LastAccessedAt pgtype.Timestamptz `json:"last_accessed_at"`
	AccessCount    int32              `json:"access_count"`
	MaxUses        pgtype.Int4        `json:"max_uses"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
}

type CkCapas struct {
	ID               string             `json:"id"`
	OrgID            string             `json:"org_id"`
	SourceType       string             `json:"source_type"`
	SourceID         string             `json:"source_id"`
	Title            string             `json:"title"`
	Description      string             `json:"description"`
	RootCause        string             `json:"root_cause"`
	ActionPlan       string             `json:"action_plan"`
	AssigneeEmail    string             `json:"assignee_email"`
	DueDate          pgtype.Date        `json:"due_date"`
	Priority         string             `json:"priority"`
	Status           string             `json:"status"`
	VerificationNote string             `json:"verification_note"`
	ClosedAt         pgtype.Timestamptz `json:"closed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type CkCcmChecks struct {
	ID            string             `json:"id"`
	OrgID         string             `json:"org_id"`
	ControlID     string             `json:"control_id"`
	Name          string             `json:"name"`
	CheckType     CkCheckType        `json:"check_type"`
	Config        json.RawMessage    `json:"config"`
	IntervalHours int32              `json:"interval_hours"`
	LastRunAt     pgtype.Timestamptz `json:"last_run_at"`
	LastStatus    pgtype.Text        `json:"last_status"`
	LastOutput    pgtype.Text        `json:"last_output"`
	Enabled       bool               `json:"enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type CkCcmResults struct {
	ID      string             `json:"id"`
	CheckID string             `json:"check_id"`
	Status  string             `json:"status"`
	Output  pgtype.Text        `json:"output"`
	RanAt   pgtype.Timestamptz `json:"ran_at"`
}

type CkComments struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	EntityType  string             `json:"entity_type"`
	EntityID    string             `json:"entity_id"`
	AuthorEmail string             `json:"author_email"`
	Body        string             `json:"body"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CkControlApprovals struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	ControlID       string             `json:"control_id"`
	RequestedBy     string             `json:"requested_by"`
	RequestedStatus string             `json:"requested_status"`
	CurrentStatus   string             `json:"current_status"`
	Comment         pgtype.Text        `json:"comment"`
	Status          string             `json:"status"`
	ReviewedBy      pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt      pgtype.Timestamptz `json:"reviewed_at"`
	ReviewComment   pgtype.Text        `json:"review_comment"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type CkControlChangelog struct {
	ID        string             `json:"id"`
	ControlID string             `json:"control_id"`
	OrgID     string             `json:"org_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	UserEmail pgtype.Text        `json:"user_email"`
	Field     string             `json:"field"`
	OldValue  pgtype.Text        `json:"old_value"`
	NewValue  pgtype.Text        `json:"new_value"`
	ChangedAt pgtype.Timestamptz `json:"changed_at"`
}

type CkControlExceptions struct {
	ID           string             `json:"id"`
	OrgID        string             `json:"org_id"`
	ControlID    string             `json:"control_id"`
	Title        string             `json:"title"`
	Reason       string             `json:"reason"`
	RiskAccepted string             `json:"risk_accepted"`
	ApprovedBy   pgtype.Text        `json:"approved_by"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	Status       string             `json:"status"`
	CreatedBy    pgtype.Text        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type CkControlMeasures struct {
	ID          string             `json:"id"`
	ControlID   string             `json:"control_id"`
	OrgID       string             `json:"org_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Difficulty  string             `json:"difficulty"`
	StepOrder   int32              `json:"step_order"`
	IsBuiltin   bool               `json:"is_builtin"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CkControlReviews struct {
	ID             string             `json:"id"`
	OrgID          string             `json:"org_id"`
	ControlID      string             `json:"control_id"`
	ReviewedBy     string             `json:"reviewed_by"`
	ReviewNote     string             `json:"review_note"`
	StatusAtReview string             `json:"status_at_review"`
	ReviewedAt     pgtype.Timestamptz `json:"reviewed_at"`
}

type CkControlTasks struct {
	ID        string             `json:"id"`
	ControlID string             `json:"control_id"`
	OrgID     string             `json:"org_id"`
	Text      string             `json:"text"`
	Completed bool               `json:"completed"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CkControls struct {
	ID                  string             `json:"id"`
	FrameworkID         string             `json:"framework_id"`
	OrgID               string             `json:"org_id"`
	ControlID           string             `json:"control_id"`
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	Domain              string             `json:"domain"`
	EvidenceType        string             `json:"evidence_type"`
	Weight              int32              `json:"weight"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	NotApplicable       bool               `json:"not_applicable"`
	NotApplicableReason pgtype.Text        `json:"not_applicable_reason"`
	ManualStatus        pgtype.Text        `json:"manual_status"`
	MaturityScore       int16              `json:"maturity_score"`
	SoaJustification    pgtype.Text        `json:"soa_justification"`
	SoaImplementation   pgtype.Text        `json:"soa_implementation"`
	SoaResponsible      pgtype.Text        `json:"soa_responsible"`
	LastReviewedAt      pgtype.Timestamptz `json:"last_reviewed_at"`
	ReviewIntervalDays  int32              `json:"review_interval_days"`
	NextReviewDue       pgtype.Timestamptz `json:"next_review_due"`
	LastReviewedBy      string             `json:"last_reviewed_by"`
	ReviewNote          string             `json:"review_note"`
	Owner               pgtype.Text        `json:"owner"`
	TestIntervalDays    pgtype.Int4        `json:"test_interval_days"`
	LastTestedAt        pgtype.Timestamptz `json:"last_tested_at"`
	NextTestDueAt       pgtype.Timestamptz `json:"next_test_due_at"`
	SoaApplicable       bool               `json:"soa_applicable"`
	SoaJustificationYes pgtype.Text        `json:"soa_justification_yes"`
	SoaJustificationNo  pgtype.Text        `json:"soa_justification_no"`
	DueDate             pgtype.Date        `json:"due_date"`
}

type CkEvidence struct {
	ID               string             `json:"id"`
	ControlID        pgtype.UUID        `json:"control_id"`
	OrgID            string             `json:"org_id"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	Source           string             `json:"source"`
	FilePath         pgtype.Text        `json:"file_path"`
	FileSize         pgtype.Int8        `json:"file_size"`
	CollectorData    []byte             `json:"collector_data"`
	Status           string             `json:"status"`
	Version          int32              `json:"version"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	UploadedBy       pgtype.UUID        `json:"uploaded_by"`
	ReviewedBy       pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	AutoSourceType   pgtype.Text        `json:"auto_source_type"`
	AutoSourceRef    pgtype.Text        `json:"auto_source_ref"`
	AutoCollectedAt  pgtype.Timestamptz `json:"auto_collected_at"`
	ExpiryNotifiedAt pgtype.Timestamptz `json:"expiry_notified_at"`
}

type CkEvidenceFiles struct {
	ID           string             `json:"id"`
	OrgID        string             `json:"org_id"`
	EvidenceID   pgtype.UUID        `json:"evidence_id"`
	ControlID    string             `json:"control_id"`
	OriginalName string             `json:"original_name"`
	StoredName   string             `json:"stored_name"`
	MimeType     string             `json:"mime_type"`
	SizeBytes    int64              `json:"size_bytes"`
	UploadedBy   string             `json:"uploaded_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type CkEvidenceHistory struct {
	ID          string             `json:"id"`
	EvidenceID  string             `json:"evidence_id"`
	OrgID       string             `json:"org_id"`
	ChangedBy   pgtype.UUID        `json:"changed_by"`
	ChangedAt   pgtype.Timestamptz `json:"changed_at"`
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      pgtype.Text        `json:"status"`
	FileUrl     pgtype.Text        `json:"file_url"`
	ChangeNote  pgtype.Text        `json:"change_note"`
}

type CkFrameworkControlMappings struct {
	ID                string             `json:"id"`
	SourceFramework   string             `json:"source_framework"`
	SourceControlCode string             `json:"source_control_code"`
	TargetFramework   string             `json:"target_framework"`
	TargetControlCode string             `json:"target_control_code"`
	MappingType       string             `json:"mapping_type"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type CkFrameworkMappings struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	SourceControlID string             `json:"source_control_id"`
	TargetControlID string             `json:"target_control_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type CkFrameworks struct {
	ID        string             `json:"id"`
	OrgID     string             `json:"org_id"`
	Name      string             `json:"name"`
	Version   string             `json:"version"`
	IsBuiltin bool               `json:"is_builtin"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CkIncidentReports struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	IncidentID  string             `json:"incident_id"`
	ReportType  string             `json:"report_type"`
	Authority   string             `json:"authority"`
	PdfData     []byte             `json:"pdf_data"`
	Metadata    []byte             `json:"metadata"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
}

type CkIncidents struct {
	ID                       string             `json:"id"`
	OrgID                    string             `json:"org_id"`
	Title                    string             `json:"title"`
	Description              string             `json:"description"`
	Severity                 string             `json:"severity"`
	Status                   string             `json:"status"`
	DiscoveredAt             pgtype.Timestamptz `json:"discovered_at"`
	ResolvedAt               pgtype.Timestamptz `json:"resolved_at"`
	AffectedSystems          []string           `json:"affected_systems"`
	BreachID                 pgtype.UUID        `json:"breach_id"`
	CreatedBy                pgtype.UUID        `json:"created_by"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	IncidentType             string             `json:"incident_type"`
	ReportingObligation      string             `json:"reporting_obligation"`
	NotificationAuthority    pgtype.Text        `json:"notification_authority"`
	Deadline4h               pgtype.Timestamptz `json:"deadline_4h"`
	Deadline24h              pgtype.Timestamptz `json:"deadline_24h"`
	Deadline72h              pgtype.Timestamptz `json:"deadline_72h"`
	Deadline30d              pgtype.Timestamptz `json:"deadline_30d"`
	Reported4hAt             pgtype.Timestamptz `json:"reported_4h_at"`
	Reported24hAt            pgtype.Timestamptz `json:"reported_24h_at"`
	Reported72hAt            pgtype.Timestamptz `json:"reported_72h_at"`
	Reported30dAt            pgtype.Timestamptz `json:"reported_30d_at"`
	AffectedCustomers        pgtype.Int4        `json:"affected_customers"`
	FinancialImpactEstimate  pgtype.Text        `json:"financial_impact_estimate"`
	IsMajorIncident          bool               `json:"is_major_incident"`
	SupplierID               pgtype.UUID        `json:"supplier_id"`
	ReportabilityAnswers     []byte             `json:"reportability_answers"`
	GdprNotificationRequired bool               `json:"gdpr_notification_required"`
	NotifiedWarn24h          bool               `json:"notified_warn_24h"`
	NotifiedWarn72h          bool               `json:"notified_warn_72h"`
	NotifiedWarn30d          bool               `json:"notified_warn_30d"`
}

type CkPolicies struct {
	ID            string             `json:"id"`
	OrgID         string             `json:"org_id"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	Category      string             `json:"category"`
	Status        string             `json:"status"`
	Version       string             `json:"version"`
	EffectiveDate pgtype.Date        `json:"effective_date"`
	ReviewDate    pgtype.Date        `json:"review_date"`
	Owner         string             `json:"owner"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	VersionNum    int32              `json:"version_num"`
	VersionNote   string             `json:"version_note"`
	LastUpdatedBy string             `json:"last_updated_by"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	NextReviewDue pgtype.Date        `json:"next_review_due"`
}

type CkPolicyAcceptanceCampaigns struct {
	ID        string             `json:"id"`
	OrgID     string             `json:"org_id"`
	PolicyID  string             `json:"policy_id"`
	Name      string             `json:"name"`
	Message   pgtype.Text        `json:"message"`
	Deadline  pgtype.Date        `json:"deadline"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CkPolicyAcceptanceRequests struct {
	ID             string             `json:"id"`
	CampaignID     string             `json:"campaign_id"`
	OrgID          string             `json:"org_id"`
	RecipientEmail string             `json:"recipient_email"`
	RecipientName  pgtype.Text        `json:"recipient_name"`
	TokenHash      string             `json:"token_hash"`
	AcceptedAt     pgtype.Timestamptz `json:"accepted_at"`
	AcceptedIp     pgtype.Text        `json:"accepted_ip"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type CkPolicyTemplates struct {
	ID          string             `json:"id"`
	Category    string             `json:"category"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Content     string             `json:"content"`
	Tags        []string           `json:"tags"`
	Framework   pgtype.Text        `json:"framework"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CkPolicyVersions struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	PolicyID    string             `json:"policy_id"`
	Version     int32              `json:"version"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Status      string             `json:"status"`
	VersionNote string             `json:"version_note"`
	UpdatedBy   string             `json:"updated_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CkQuestionnaireQuestions struct {
	ID              string             `json:"id"`
	QuestionnaireID string             `json:"questionnaire_id"`
	OrderIdx        int32              `json:"order_idx"`
	QuestionText    string             `json:"question_text"`
	QuestionType    string             `json:"question_type"`
	Options         []byte             `json:"options"`
	Required        bool               `json:"required"`
	ControlID       pgtype.UUID        `json:"control_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CkQuestionnaires struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsTemplate  bool               `json:"is_template"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CkResilienceTests struct {
	ID                string             `json:"id"`
	OrgID             string             `json:"org_id"`
	Type              string             `json:"type"`
	Scope             pgtype.Text        `json:"scope"`
	Provider          pgtype.Text        `json:"provider"`
	TestDate          pgtype.Date        `json:"test_date"`
	Summary           pgtype.Text        `json:"summary"`
	RemediationStatus string             `json:"remediation_status"`
	AttachmentUrl     pgtype.Text        `json:"attachment_url"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type CkReviews struct {
	ID          string             `json:"id"`
	ControlID   string             `json:"control_id"`
	OrgID       string             `json:"org_id"`
	AssignedTo  string             `json:"assigned_to"`
	AssignedBy  string             `json:"assigned_by"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	Status      string             `json:"status"`
	Notes       pgtype.Text        `json:"notes"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CkRiskControlLinks struct {
	RiskID    string             `json:"risk_id"`
	ControlID string             `json:"control_id"`
	OrgID     string             `json:"org_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CkRisks struct {
	ID                 string             `json:"id"`
	OrgID              string             `json:"org_id"`
	Title              string             `json:"title"`
	Description        string             `json:"description"`
	Category           string             `json:"category"`
	Likelihood         int16              `json:"likelihood"`
	Impact             int16              `json:"impact"`
	RiskScore          pgtype.Int2        `json:"risk_score"`
	Owner              string             `json:"owner"`
	Status             string             `json:"status"`
	Treatment          string             `json:"treatment"`
	TreatmentNotes     string             `json:"treatment_notes"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	TreatmentOption    pgtype.Text        `json:"treatment_option"`
	TreatmentPlan      string             `json:"treatment_plan"`
	TreatmentOwner     string             `json:"treatment_owner"`
	TreatmentDueDate   pgtype.Date        `json:"treatment_due_date"`
	TreatmentStatus    string             `json:"treatment_status"`
	ResidualLikelihood pgtype.Int4        `json:"residual_likelihood"`
	ResidualImpact     pgtype.Int4        `json:"residual_impact"`
}

type CkScoreHistory struct {
	ID                  string             `json:"id"`
	OrgID               string             `json:"org_id"`
	FrameworkID         pgtype.UUID        `json:"framework_id"`
	Score               pgtype.Numeric     `json:"score"`
	ControlsTotal       int32              `json:"controls_total"`
	ControlsImplemented int32              `json:"controls_implemented"`
	RecordedAt          pgtype.Timestamptz `json:"recorded_at"`
}

type CkSupplierAnswers struct {
	ID             string             `json:"id"`
	AssessmentID   string             `json:"assessment_id"`
	QuestionID     string             `json:"question_id"`
	AnswerText     pgtype.Text        `json:"answer_text"`
	AnswerBool     pgtype.Bool        `json:"answer_bool"`
	AnswerOptions  []byte             `json:"answer_options"`
	FileUrl        pgtype.Text        `json:"file_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ReviewStatus   pgtype.Text        `json:"review_status"`
	ReworkNote     pgtype.Text        `json:"rework_note"`
	CertExpiryDate pgtype.Date        `json:"cert_expiry_date"`
}

type CkSupplierAssessments struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	SupplierID      string             `json:"supplier_id"`
	QuestionnaireID string             `json:"questionnaire_id"`
	TokenHash       string             `json:"token_hash"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	Status          string             `json:"status"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
	SubmittedByIp   pgtype.Text        `json:"submitted_by_ip"`
	UserAgent       pgtype.Text        `json:"user_agent"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type CkSupplierRisks struct {
	SupplierID string             `json:"supplier_id"`
	RiskID     string             `json:"risk_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CkSuppliers struct {
	ID                 string             `json:"id"`
	OrgID              string             `json:"org_id"`
	Name               string             `json:"name"`
	ContactName        pgtype.Text        `json:"contact_name"`
	ContactEmail       pgtype.Text        `json:"contact_email"`
	ServiceType        pgtype.Text        `json:"service_type"`
	Criticality        string             `json:"criticality"`
	Nis2Relevant       bool               `json:"nis2_relevant"`
	DoraRelevant       bool               `json:"dora_relevant"`
	ContractEnd        pgtype.Date        `json:"contract_end"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	SubSuppliers       []string           `json:"sub_suppliers"`
	DataLocation       pgtype.Text        `json:"data_location"`
	ExitStrategyExists bool               `json:"exit_strategy_exists"`
	AssessmentStatus   string             `json:"assessment_status"`
	LastAssessmentAt   pgtype.Timestamptz `json:"last_assessment_at"`
}

type CkTasks struct {
	ID            string             `json:"id"`
	OrgID         string             `json:"org_id"`
	EntityType    string             `json:"entity_type"`
	EntityID      string             `json:"entity_id"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	AssigneeEmail string             `json:"assignee_email"`
	DueDate       pgtype.Date        `json:"due_date"`
	Status        string             `json:"status"`
	Priority      string             `json:"priority"`
	CreatedBy     string             `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ClientErrors struct {
	ID             string             `json:"id"`
	OrgID          pgtype.UUID        `json:"org_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Message        string             `json:"message"`
	Stack          pgtype.Text        `json:"stack"`
	ComponentStack pgtype.Text        `json:"component_stack"`
	Url            pgtype.Text        `json:"url"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	TraceID        pgtype.Text        `json:"trace_id"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
}

type CloudIntegrations struct {
	ID             string             `json:"id"`
	OrgID          string             `json:"org_id"`
	Provider       string             `json:"provider"`
	Config         json.RawMessage    `json:"config"`
	Enabled        bool               `json:"enabled"`
	LastSyncAt     pgtype.Timestamptz `json:"last_sync_at"`
	LastSyncStatus pgtype.Text        `json:"last_sync_status"`
	LastSyncError  pgtype.Text        `json:"last_sync_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Comments struct {
	ID         string             `json:"id"`
	OrgID      string             `json:"org_id"`
	EntityType string             `json:"entity_type"`
	EntityID   string             `json:"entity_id"`
	AuthorID   string             `json:"author_id"`
	Content    string             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type DemoFeedback struct {
	ID        string             `json:"id"`
	Rating    int16              `json:"rating"`
	Message   string             `json:"message"`
	Name      pgtype.Text        `json:"name"`
	Email     pgtype.Text        `json:"email"`
	Page      pgtype.Text        `json:"page"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type HrChecklistRuns struct {
	ID             string             `json:"id"`
	OrgID          string             `json:"org_id"`
	EmployeeID     string             `json:"employee_id"`
	ChecklistID    string             `json:"checklist_id"`
	Status         string             `json:"status"`
	CompletedItems json.RawMessage    `json:"completed_items"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type HrChecklists struct {
	ID        string             `json:"id"`
	OrgID     string             `json:"org_id"`
	Type      string             `json:"type"`
	Name      string             `json:"name"`
	Items     json.RawMessage    `json:"items"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type HrEmployees struct {
	ID         string             `json:"id"`
	OrgID      string             `json:"org_id"`
	FirstName  string             `json:"first_name"`
	LastName   string             `json:"last_name"`
	Email      string             `json:"email"`
	Department pgtype.Text        `json:"department"`
	Role       pgtype.Text        `json:"role"`
	StartDate  pgtype.Date        `json:"start_date"`
	EndDate    pgtype.Date        `json:"end_date"`
	Status     string             `json:"status"`
	Notes      pgtype.Text        `json:"notes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type HrRunEvents struct {
	ID          string             `json:"id"`
	RunID       string             `json:"run_id"`
	OrgID       string             `json:"org_id"`
	StepID      string             `json:"step_id"`
	CompletedBy string             `json:"completed_by"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type IntegrationsGithub struct {
	ID           string             `json:"id"`
	OrgID        string             `json:"org_id"`
	RepoOwner    string             `json:"repo_owner"`
	RepoName     string             `json:"repo_name"`
	AccessToken  string             `json:"access_token"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	SyncStatus   pgtype.Text        `json:"sync_status"`
	SyncError    pgtype.Text        `json:"sync_error"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type IntegrationsGithubChecks struct {
	ID            string             `json:"id"`
	IntegrationID string             `json:"integration_id"`
	CheckType     string             `json:"check_type"`
	Status        string             `json:"status"`
	Details       []byte             `json:"details"`
	CheckedAt     pgtype.Timestamptz `json:"checked_at"`
}

type LicenseKeys struct {
	ID          int64              `json:"id"`
	OrgID       string             `json:"org_id"`
	KeyValue    string             `json:"key_value"`
	ActivatedAt pgtype.Timestamptz `json:"activated_at"`
	ActivatedBy pgtype.UUID        `json:"activated_by"`
}

type LsRevokedSubscriptions struct {
	OrgID     string             `json:"org_id"`
	Reason    string             `json:"reason"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type LsSubscriptions struct {
	ID               int64              `json:"id"`
	LsSubscriptionID string             `json:"ls_subscription_id"`
	Tier             string             `json:"tier"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CustomerEmail    string             `json:"customer_email"`
}

type NotificationAlertState struct {
	OrgID       string             `json:"org_id"`
	EventType   string             `json:"event_type"`
	LastFiredAt pgtype.Timestamptz `json:"last_fired_at"`
}

type NotificationChannels struct {
	ID                  string             `json:"id"`
	OrgID               string             `json:"org_id"`
	Name                string             `json:"name"`
	Channel             string             `json:"channel"`
	Config              json.RawMessage    `json:"config"`
	IsActive            bool               `json:"is_active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	HmacSecretEncrypted []byte             `json:"hmac_secret_encrypted"`
}

type NotificationLog struct {
	ID               string             `json:"id"`
	OrgID            string             `json:"org_id"`
	NotificationType string             `json:"notification_type"`
	ResourceID       string             `json:"resource_id"`
	SentAt           pgtype.Timestamptz `json:"sent_at"`
	RecipientEmail   string             `json:"recipient_email"`
}

type NotificationPreferences struct {
	ID                    string             `json:"id"`
	UserID                string             `json:"user_id"`
	EmailWeeklyDigest     bool               `json:"email_weekly_digest"`
	EmailFindingsSeverity string             `json:"email_findings_severity"`
	EmailNewIncidents     bool               `json:"email_new_incidents"`
	EmailOverdueControls  bool               `json:"email_overdue_controls"`
	EmailEvidenceExpiry   bool               `json:"email_evidence_expiry"`
	InappComments         bool               `json:"inapp_comments"`
	InappApprovals        bool               `json:"inapp_approvals"`
	InappSystemUpdates    bool               `json:"inapp_system_updates"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type Notifications struct {
	ID         string             `json:"id"`
	OrgID      string             `json:"org_id"`
	Type       string             `json:"type"`
	Channel    string             `json:"channel"`
	Payload    json.RawMessage    `json:"payload"`
	Status     string             `json:"status"`
	RetryCount int32              `json:"retry_count"`
	SentAt     pgtype.Timestamptz `json:"sent_at"`
	FailedAt   pgtype.Timestamptz `json:"failed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type OrgMembers struct {
	OrgID     string             `json:"org_id"`
	UserID    string             `json:"user_id"`
	RoleID    string             `json:"role_id"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
}

type Organizations struct {
	ID                         string             `json:"id"`
	Name                       string             `json:"name"`
	Slug                       string             `json:"slug"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	Plan                       string             `json:"plan"`
	LogoUrl                    pgtype.Text        `json:"logo_url"`
	TrustCenterEnabled         bool               `json:"trust_center_enabled"`
	TrustCenterDescription     pgtype.Text        `json:"trust_center_description"`
	TrustCenterContact         pgtype.Text        `json:"trust_center_contact"`
	Sector                     string             `json:"sector"`
	FederalState               pgtype.Text        `json:"federal_state"`
	TrustCenterLogoUrl         pgtype.Text        `json:"trust_center_logo_url"`
	TrustCenterShowFrameworks  bool               `json:"trust_center_show_frameworks"`
	TrustCenterShowPolicies    bool               `json:"trust_center_show_policies"`
	TrustCenterShowCerts       bool               `json:"trust_center_show_certs"`
	TrustCenterSubprocessorsMd pgtype.Text        `json:"trust_center_subprocessors_md"`
	DsrPortalEnabled           bool               `json:"dsr_portal_enabled"`
	DsrPortalSlug              pgtype.Text        `json:"dsr_portal_slug"`
	DsrDpoEmail                pgtype.Text        `json:"dsr_dpo_email"`
	DsrPortalIntro             pgtype.Text        `json:"dsr_portal_intro"`
	PhishReportToken           pgtype.Text        `json:"phish_report_token"`
	OnboardingDismissed        bool               `json:"onboarding_dismissed"`
	RequireMfa                 bool               `json:"require_mfa"`
	ApprovalRequired           bool               `json:"approval_required"`
}

type PasswordResetTokens struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Permissions struct {
	ID        string             `json:"id"`
	RoleID    string             `json:"role_id"`
	Resource  string             `json:"resource"`
	Action    string             `json:"action"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PoAvvs struct {
	ID                 string             `json:"id"`
	OrgID              string             `json:"org_id"`
	ProcessorName      string             `json:"processor_name"`
	ServiceDescription string             `json:"service_description"`
	ContractDate       pgtype.Date        `json:"contract_date"`
	ReviewDate         pgtype.Date        `json:"review_date"`
	Status             string             `json:"status"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	TemplateID         pgtype.Text        `json:"template_id"`
	Body               pgtype.Text        `json:"body"`
	SccModule          pgtype.Text        `json:"scc_module"`
	SccAnnexI          pgtype.Text        `json:"scc_annex_i"`
	SccAnnexIi         pgtype.Text        `json:"scc_annex_ii"`
	SccAnnexIii        pgtype.Text        `json:"scc_annex_iii"`
}

type PoBreaches struct {
	ID                           string             `json:"id"`
	OrgID                        string             `json:"org_id"`
	Title                        string             `json:"title"`
	Description                  string             `json:"description"`
	DiscoveredAt                 pgtype.Timestamptz `json:"discovered_at"`
	AuthorityDeadlineAt          pgtype.Timestamptz `json:"authority_deadline_at"`
	AuthorityNotifiedAt          pgtype.Timestamptz `json:"authority_notified_at"`
	SubjectsNotificationRequired bool               `json:"subjects_notification_required"`
	SubjectsNotifiedAt           pgtype.Timestamptz `json:"subjects_notified_at"`
	AffectedCount                pgtype.Int4        `json:"affected_count"`
	DataCategories               []string           `json:"data_categories"`
	Status                       string             `json:"status"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
}

type PoDpias struct {
	ID                  string             `json:"id"`
	OrgID               string             `json:"org_id"`
	VvtEntryID          pgtype.UUID        `json:"vvt_entry_id"`
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	NecessityAssessment pgtype.Text        `json:"necessity_assessment"`
	RiskAssessment      pgtype.Text        `json:"risk_assessment"`
	MitigationMeasures  pgtype.Text        `json:"mitigation_measures"`
	ResidualRisk        pgtype.Text        `json:"residual_risk"`
	DpoConsultation     bool               `json:"dpo_consultation"`
	Status              string             `json:"status"`
	ReviewedBy          pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt          pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type PoDsr struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	RequesterName   string             `json:"requester_name"`
	RequesterEmail  string             `json:"requester_email"`
	Type            string             `json:"type"`
	Description     pgtype.Text        `json:"description"`
	Status          string             `json:"status"`
	DueDate         pgtype.Date        `json:"due_date"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	TokenHash       pgtype.Text        `json:"token_hash"`
	Source          string             `json:"source"`
	PortalLocale    pgtype.Text        `json:"portal_locale"`
	SubmittedIp     pgtype.Text        `json:"submitted_ip"`
	VerifyTokenHash pgtype.Text        `json:"verify_token_hash"`
}

type PoVvtEntries struct {
	ID                   string             `json:"id"`
	OrgID                string             `json:"org_id"`
	Name                 string             `json:"name"`
	Purpose              string             `json:"purpose"`
	LegalBasis           string             `json:"legal_basis"`
	DataCategories       []string           `json:"data_categories"`
	DataSubjects         []string           `json:"data_subjects"`
	Recipients           []string           `json:"recipients"`
	RetentionPeriod      pgtype.Text        `json:"retention_period"`
	ThirdCountryTransfer bool               `json:"third_country_transfer"`
	Safeguards           pgtype.Text        `json:"safeguards"`
	ResponsiblePerson    pgtype.Text        `json:"responsible_person"`
	Status               string             `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type RefreshSessions struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	OrgID      string             `json:"org_id"`
	TokenHash  string             `json:"token_hash"`
	DeviceHint string             `json:"device_hint"`
	LastUsed   pgtype.Timestamptz `json:"last_used"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

type RetentionConfig struct {
	OrgID                string             `json:"org_id"`
	AuditLogDays         int32              `json:"audit_log_days"`
	FindingsResolvedDays int32              `json:"findings_resolved_days"`
	NotificationsDays    int32              `json:"notifications_days"`
	ScanHistoryDays      int32              `json:"scan_history_days"`
	DigestEnabled        bool               `json:"digest_enabled"`
	DigestHour           int16              `json:"digest_hour"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	// 0=Sonntag … 6=Samstag (cron weekday convention)
	DigestDay int16 `json:"digest_day"`
}

type Roles struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ScheduledReports struct {
	ID         string             `json:"id"`
	OrgID      string             `json:"org_id"`
	Name       string             `json:"name"`
	ReportType string             `json:"report_type"`
	Schedule   string             `json:"schedule"`
	Recipients []string           `json:"recipients"`
	Format     string             `json:"format"`
	Active     bool               `json:"active"`
	LastRunAt  pgtype.Timestamptz `json:"last_run_at"`
	NextRunAt  pgtype.Timestamptz `json:"next_run_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ScoreConfig struct {
	OrgID            string             `json:"org_id"`
	BaseScore        int32              `json:"base_score"`
	CritPenalty      int32              `json:"crit_penalty"`
	CritPenaltyCap   int32              `json:"crit_penalty_cap"`
	HighPenalty      int32              `json:"high_penalty"`
	HighPenaltyCap   int32              `json:"high_penalty_cap"`
	BreachPenalty    int32              `json:"breach_penalty"`
	BreachPenaltyCap int32              `json:"breach_penalty_cap"`
	FwBonus          int32              `json:"fw_bonus"`
	FwBonusCap       int32              `json:"fw_bonus_cap"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Sessions struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	OrgID     string             `json:"org_id"`
	TokenHash string             `json:"token_hash"`
	UserAgent pgtype.Text        `json:"user_agent"`
	IpAddress pgtype.Text        `json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SoAccessLog struct {
	ID         string             `json:"id"`
	SecretID   string             `json:"secret_id"`
	OrgID      string             `json:"org_id"`
	AccessedBy pgtype.UUID        `json:"accessed_by"`
	AccessVia  string             `json:"access_via"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	AccessedAt pgtype.Timestamptz `json:"accessed_at"`
}

type SoEnvironments struct {
	ID        string             `json:"id"`
	ProjectID string             `json:"project_id"`
	OrgID     string             `json:"org_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SoGitScans struct {
	ID             string             `json:"id"`
	OrgID          string             `json:"org_id"`
	RepoUrl        string             `json:"repo_url"`
	Branch         string             `json:"branch"`
	Status         string             `json:"status"`
	FindingCount   int32              `json:"finding_count"`
	OpenCount      int32              `json:"open_count"`
	DismissedCount int32              `json:"dismissed_count"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	ScannedAt      pgtype.Timestamptz `json:"scanned_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SoMasterKeyFingerprint struct {
	ID          string             `json:"id"`
	Fingerprint string             `json:"fingerprint"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type SoProjects struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	CreatedBy   string             `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SoRotationPolicies struct {
	ID             string             `json:"id"`
	OrgID          string             `json:"org_id"`
	SecretID       string             `json:"secret_id"`
	IntervalDays   int32              `json:"interval_days"`
	LastRotatedAt  pgtype.Timestamptz `json:"last_rotated_at"`
	NextRotationAt pgtype.Timestamptz `json:"next_rotation_at"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SoScanResults struct {
	ID            string             `json:"id"`
	OrgID         string             `json:"org_id"`
	ScanID        string             `json:"scan_id"`
	RepoUrl       string             `json:"repo_url"`
	CommitHash    pgtype.Text        `json:"commit_hash"`
	FilePath      string             `json:"file_path"`
	LineNumber    pgtype.Int4        `json:"line_number"`
	PatternName   string             `json:"pattern_name"`
	MatchPreview  string             `json:"match_preview"`
	Severity      string             `json:"severity"`
	Status        string             `json:"status"`
	DismissReason pgtype.Text        `json:"dismiss_reason"`
	DismissCount  int32              `json:"dismiss_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type SoSecrets struct {
	ID             string             `json:"id"`
	EnvironmentID  string             `json:"environment_id"`
	OrgID          string             `json:"org_id"`
	Key            string             `json:"key"`
	EncryptedValue []byte             `json:"encrypted_value"`
	Version        int32              `json:"version"`
	RotationDueAt  pgtype.Timestamptz `json:"rotation_due_at"`
	LastRotatedAt  pgtype.Timestamptz `json:"last_rotated_at"`
	LastAccessedAt pgtype.Timestamptz `json:"last_accessed_at"`
	AccessCount    int64              `json:"access_count"`
	CreatedBy      string             `json:"created_by"`
	UpdatedBy      pgtype.UUID        `json:"updated_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type SoShareLinks struct {
	ID        string             `json:"id"`
	SecretID  string             `json:"secret_id"`
	OrgID     string             `json:"org_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedBy string             `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SrAssignments struct {
	ID         string             `json:"id"`
	OrgID      string             `json:"org_id"`
	ModuleID   string             `json:"module_id"`
	TargetID   pgtype.UUID        `json:"target_id"`
	Department pgtype.Text        `json:"department"`
	DueDate    pgtype.Timestamptz `json:"due_date"`
	IsOverdue  bool               `json:"is_overdue"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type SrCampaigns struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	Name            string             `json:"name"`
	Status          string             `json:"status"`
	TemplateID      pgtype.UUID        `json:"template_id"`
	GroupID         pgtype.UUID        `json:"group_id"`
	LandingPageID   pgtype.UUID        `json:"landing_page_id"`
	FromName        string             `json:"from_name"`
	FromEmail       string             `json:"from_email"`
	Subject         string             `json:"subject"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Recurrence      pgtype.Text        `json:"recurrence"`
	NextRunAt       pgtype.Timestamptz `json:"next_run_at"`
	TrackOpens      bool               `json:"track_opens"`
	BetriebsratMode bool               `json:"betriebsrat_mode"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type SrCompletions struct {
	ID           string             `json:"id"`
	OrgID        string             `json:"org_id"`
	AssignmentID string             `json:"assignment_id"`
	Score        pgtype.Int4        `json:"score"`
	Passed       bool               `json:"passed"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

type SrEvents struct {
	ID            string             `json:"id"`
	OrgID         string             `json:"org_id"`
	CampaignID    string             `json:"campaign_id"`
	TargetID      pgtype.UUID        `json:"target_id"`
	Department    pgtype.Text        `json:"department"`
	Type          string             `json:"type"`
	TrackingToken string             `json:"tracking_token"`
	IpAddress     pgtype.Text        `json:"ip_address"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

type SrLandingPages struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	Name        string             `json:"name"`
	HtmlContent string             `json:"html_content"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type SrPhishReports struct {
	ID            string             `json:"id"`
	OrgID         string             `json:"org_id"`
	CampaignID    pgtype.UUID        `json:"campaign_id"`
	ReporterEmail string             `json:"reporter_email"`
	ReportedAt    pgtype.Timestamptz `json:"reported_at"`
	Subject       pgtype.Text        `json:"subject"`
	Sender        pgtype.Text        `json:"sender"`
	IsSimulation  bool               `json:"is_simulation"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type SrTargetGroups struct {
	ID        string             `json:"id"`
	OrgID     string             `json:"org_id"`
	Name      string             `json:"name"`
	Source    string             `json:"source"`
	AdOu      pgtype.Text        `json:"ad_ou"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SrTargets struct {
	ID         string             `json:"id"`
	OrgID      string             `json:"org_id"`
	GroupID    string             `json:"group_id"`
	Email      string             `json:"email"`
	FirstName  string             `json:"first_name"`
	LastName   string             `json:"last_name"`
	Department string             `json:"department"`
	IsBounced  bool               `json:"is_bounced"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type SrTemplates struct {
	ID         string             `json:"id"`
	OrgID      string             `json:"org_id"`
	Name       string             `json:"name"`
	Subject    string             `json:"subject"`
	FromName   string             `json:"from_name"`
	FromEmail  string             `json:"from_email"`
	HtmlBody   string             `json:"html_body"`
	AttackType string             `json:"attack_type"`
	IsPreset   bool               `json:"is_preset"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type SrTrainingModules struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	Title           string             `json:"title"`
	Type            string             `json:"type"`
	AttackType      string             `json:"attack_type"`
	ContentUrl      string             `json:"content_url"`
	DurationSeconds int32              `json:"duration_seconds"`
	PassingScore    int32              `json:"passing_score"`
	Questions       []byte             `json:"questions"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type TcCertificates struct {
	ID           string             `json:"id"`
	OrgID        string             `json:"org_id"`
	Name         string             `json:"name"`
	Issuer       pgtype.Text        `json:"issuer"`
	IssuedAt     pgtype.Date        `json:"issued_at"`
	ExpiresAt    pgtype.Date        `json:"expires_at"`
	IsPublic     bool               `json:"is_public"`
	DisplayOrder int32              `json:"display_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type TcPublicPolicies struct {
	OrgID    string `json:"org_id"`
	PolicyID string `json:"policy_id"`
}

type TotpSecrets struct {
	UserID      string             `json:"user_id"`
	Secret      string             `json:"secret"`
	Enabled     bool               `json:"enabled"`
	BackupCodes []string           `json:"backup_codes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UserInvitations struct {
	ID         string             `json:"id"`
	OrgID      string             `json:"org_id"`
	Email      string             `json:"email"`
	Role       string             `json:"role"`
	TokenHash  string             `json:"token_hash"`
	InvitedBy  string             `json:"invited_by"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type UserModulePermissions struct {
	ID        string             `json:"id"`
	OrgID     string             `json:"org_id"`
	UserID    string             `json:"user_id"`
	Module    string             `json:"module"`
	CanRead   bool               `json:"can_read"`
	CanWrite  bool               `json:"can_write"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserNotifications struct {
	ID        string             `json:"id"`
	OrgID     string             `json:"org_id"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Type      string             `json:"type"`
	Module    string             `json:"module"`
	Read      bool               `json:"read"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Users struct {
	ID                string             `json:"id"`
	Email             string             `json:"email"`
	// json:"-" intentionally overrides sqlc default — never serialize password hashes in API responses
	PasswordHash      pgtype.Text        `json:"-"`
	DisplayName       pgtype.Text        `json:"display_name"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	OidcSubject       pgtype.Text        `json:"oidc_subject"`
	OidcProvider      pgtype.Text        `json:"oidc_provider"`
	IsActive          bool               `json:"is_active"`
	LastLoginAt       pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Role              string             `json:"role"`
	PreferredLanguage string             `json:"preferred_language"`
}

type VbAssets struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	Name        string             `json:"name"`
	Type        string             `json:"type"`
	Criticality string             `json:"criticality"`
	Tags        []string           `json:"tags"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	ExternalUrl pgtype.Text        `json:"external_url"`
	IsDeleted   bool               `json:"is_deleted"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type VbComponents struct {
	ID           string             `json:"id"`
	OrgID        string             `json:"org_id"`
	SbomID       string             `json:"sbom_id"`
	Name         string             `json:"name"`
	Version      string             `json:"version"`
	Purl         pgtype.Text        `json:"purl"`
	EolStatus    string             `json:"eol_status"`
	EolDate      pgtype.Date        `json:"eol_date"`
	EolCheckedAt pgtype.Timestamptz `json:"eol_checked_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type VbEolCache struct {
	Product   string             `json:"product"`
	Cycle     string             `json:"cycle"`
	EolDate   pgtype.Date        `json:"eol_date"`
	Payload   []byte             `json:"payload"`
	FetchedAt pgtype.Timestamptz `json:"fetched_at"`
}

type VbFindingSuppressions struct {
	ID         string             `json:"id"`
	OrgID      string             `json:"org_id"`
	CveID      pgtype.Text        `json:"cve_id"`
	AssetTag   pgtype.Text        `json:"asset_tag"`
	Reason     string             `json:"reason"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	MatchCount int32              `json:"match_count"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type VbFindings struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	AssetID         string             `json:"asset_id"`
	ScanID          pgtype.UUID        `json:"scan_id"`
	CveID           pgtype.Text        `json:"cve_id"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Severity        string             `json:"severity"`
	CvssScore       pgtype.Numeric     `json:"cvss_score"`
	EpssScore       pgtype.Numeric     `json:"epss_score"`
	EpssPercentile  pgtype.Numeric     `json:"epss_percentile"`
	RiskScore       pgtype.Numeric     `json:"risk_score"`
	Status          string             `json:"status"`
	Scanner         string             `json:"scanner"`
	RawID           pgtype.Text        `json:"raw_id"`
	Sources         []string           `json:"sources"`
	TemplateID      pgtype.Text        `json:"template_id"`
	AssignedTo      pgtype.UUID        `json:"assigned_to"`
	Justification   pgtype.Text        `json:"justification"`
	ReopenCount     int32              `json:"reopen_count"`
	OccurrenceCount int32              `json:"occurrence_count"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	SlaDueAt        pgtype.Timestamptz `json:"sla_due_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type VbReports struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	GeneratedBy pgtype.UUID        `json:"generated_by"`
	Scope       json.RawMessage    `json:"scope"`
	FilePath    pgtype.Text        `json:"file_path"`
	Status      string             `json:"status"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Content     []byte             `json:"content"`
}

type VbSboms struct {
	ID             string             `json:"id"`
	OrgID          string             `json:"org_id"`
	AssetID        string             `json:"asset_id"`
	Format         string             `json:"format"`
	SpecVersion    string             `json:"spec_version"`
	Document       json.RawMessage    `json:"document"`
	ComponentCount int32              `json:"component_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type VbScanSchedules struct {
	ID        string             `json:"id"`
	OrgID     string             `json:"org_id"`
	AssetID   string             `json:"asset_id"`
	Scanner   string             `json:"scanner"`
	CronExpr  string             `json:"cron_expr"`
	IsActive  bool               `json:"is_active"`
	LastRun   pgtype.Timestamptz `json:"last_run"`
	NextRun   pgtype.Timestamptz `json:"next_run"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type VbScans struct {
	ID           string             `json:"id"`
	OrgID        string             `json:"org_id"`
	AssetID      string             `json:"asset_id"`
	Scanner      string             `json:"scanner"`
	Status       string             `json:"status"`
	TargetUrl    pgtype.Text        `json:"target_url"`
	TargetIp     pgtype.Text        `json:"target_ip"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	FindingCount int32              `json:"finding_count"`
	DurationMs   pgtype.Int8        `json:"duration_ms"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type VbSlaConfig struct {
	ID           string             `json:"id"`
	OrgID        string             `json:"org_id"`
	CriticalDays int32              `json:"critical_days"`
	HighDays     int32              `json:"high_days"`
	MediumDays   int32              `json:"medium_days"`
	LowDays      int32              `json:"low_days"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Webhooks struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	Name            string             `json:"name"`
	Url             string             `json:"url"`
	Secret          pgtype.Text        `json:"secret"`
	Events          []string           `json:"events"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastTriggeredAt pgtype.Timestamptz `json:"last_triggered_at"`
	LastStatusCode  pgtype.Int4        `json:"last_status_code"`
}

// ── S60: BCP / Notfallhandbuch ────────────────────────────────────────────────

type CkBcpPlans struct {
	ID        string             `json:"id"`
	OrgID     string             `json:"org_id"`
	Title     string             `json:"title"`
	Scope     string             `json:"scope"`
	Version   string             `json:"version"`
	Status    string             `json:"status"`
	Owner     string             `json:"owner"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CkBcpTests struct {
	ID        string             `json:"id"`
	OrgID     string             `json:"org_id"`
	PlanID    string             `json:"plan_id"`
	TestDate  pgtype.Date        `json:"test_date"`
	TestType  string             `json:"test_type"`
	Outcome   string             `json:"outcome"`
	Findings  string             `json:"findings"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// ── S60: Schutzbedarfsfeststellung ────────────────────────────────────────────

type CkProtectionNeedAssessments struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	Name            string             `json:"name"`
	ObjectType      string             `json:"object_type"`
	ObjectName      string             `json:"object_name"`
	Confidentiality string             `json:"confidentiality"`
	Integrity       string             `json:"integrity"`
	Availability    string             `json:"availability"`
	Overall         string             `json:"overall"`
	Status          string             `json:"status"`
	FinalizedAt     pgtype.Timestamptz `json:"finalized_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// ── S60: Berechtigungskonzept ─────────────────────────────────────────────────

type HrAccessConcepts struct {
	ID             string             `json:"id"`
	OrgID          string             `json:"org_id"`
	Title          string             `json:"title"`
	Scope          string             `json:"scope"`
	Owner          string             `json:"owner"`
	CurrentVersion int32              `json:"current_version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type HrAccessRoles struct {
	ID                   string             `json:"id"`
	ConceptID            string             `json:"concept_id"`
	OrgID                string             `json:"org_id"`
	RoleName             string             `json:"role_name"`
	SystemName           string             `json:"system_name"`
	AccessLevel          string             `json:"access_level"`
	Justification        string             `json:"justification"`
	ReviewIntervalMonths int32              `json:"review_interval_months"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type HrAccessConceptVersions struct {
	ID            string             `json:"id"`
	ConceptID     string             `json:"concept_id"`
	OrgID         string             `json:"org_id"`
	VersionNumber int32              `json:"version_number"`
	Snapshot      json.RawMessage    `json:"snapshot"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
