// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secvault.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSVEnvironment = `-- name: CreateSVEnvironment :one

INSERT INTO so_environments (project_id, org_id, name)
VALUES ($1, $2, $3)
RETURNING id, project_id, org_id, name, created_at
`

type CreateSVEnvironmentParams struct {
	ProjectID string `json:"project_id"`
	OrgID     string `json:"org_id"`
	Name      string `json:"name"`
}

// ── Environments ────────────────────────────────────────────────────────────
func (q *Queries) CreateSVEnvironment(ctx context.Context, arg CreateSVEnvironmentParams) (SoEnvironments, error) {
	row := q.db.QueryRow(ctx, createSVEnvironment, arg.ProjectID, arg.OrgID, arg.Name)
	var i SoEnvironments
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createSVProject = `-- name: CreateSVProject :one


INSERT INTO so_projects (org_id, name, slug, description, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, name, slug, description, created_by, created_at
`

type CreateSVProjectParams struct {
	OrgID       string      `json:"org_id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	CreatedBy   string      `json:"created_by"`
}

type CreateSVProjectRow struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	CreatedBy   string             `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// SecVault queries — migrated to sqlc in Sprint 11+ (ADR-0005, inkrementell).
//
// Migrationspfad:
//
//	✅ Projects, Environments, AccessLog, RotationPolicies — sqlc (this file)
//	⏳ Secrets — bleibt embedded SQL in repository.go (Crypto-Felder + dynamische
//	   Spalten-Auswahl je nach decrypt-Strategie machen sqlc-Generierung holprig).
//	   Migration on-demand bei nächstem Secrets-Refactor.
//
// ── Projects ────────────────────────────────────────────────────────────────
func (q *Queries) CreateSVProject(ctx context.Context, arg CreateSVProjectParams) (CreateSVProjectRow, error) {
	row := q.db.QueryRow(ctx, createSVProject,
		arg.OrgID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.CreatedBy,
	)
	var i CreateSVProjectRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSVEnvironment = `-- name: DeleteSVEnvironment :execrows
DELETE FROM so_environments WHERE id = $1 AND org_id = $2
`

type DeleteSVEnvironmentParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeleteSVEnvironment(ctx context.Context, arg DeleteSVEnvironmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSVEnvironment, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSVProject = `-- name: DeleteSVProject :execrows
DELETE FROM so_projects WHERE id = $1 AND org_id = $2
`

type DeleteSVProjectParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeleteSVProject(ctx context.Context, arg DeleteSVProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSVProject, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSVEnvironment = `-- name: GetSVEnvironment :one
SELECT id, project_id, org_id, name, created_at
FROM so_environments
WHERE id = $1 AND org_id = $2
`

type GetSVEnvironmentParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetSVEnvironment(ctx context.Context, arg GetSVEnvironmentParams) (SoEnvironments, error) {
	row := q.db.QueryRow(ctx, getSVEnvironment, arg.ID, arg.OrgID)
	var i SoEnvironments
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getSVProject = `-- name: GetSVProject :one
SELECT id, org_id, name, slug, description, created_by, created_at
FROM so_projects
WHERE id = $1 AND org_id = $2
`

type GetSVProjectParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

type GetSVProjectRow struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	CreatedBy   string             `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetSVProject(ctx context.Context, arg GetSVProjectParams) (GetSVProjectRow, error) {
	row := q.db.QueryRow(ctx, getSVProject, arg.ID, arg.OrgID)
	var i GetSVProjectRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertSVAccessLog = `-- name: InsertSVAccessLog :exec

INSERT INTO so_access_log
  (secret_id, org_id, accessed_by, access_via, ip_address, user_agent)
VALUES
  ($1, $2, $3, $4, $5, $6)
`

type InsertSVAccessLogParams struct {
	SecretID   string      `json:"secret_id"`
	OrgID      string      `json:"org_id"`
	AccessedBy pgtype.UUID `json:"accessed_by"`
	AccessVia  string      `json:"access_via"`
	IpAddress  pgtype.Text `json:"ip_address"`
	UserAgent  pgtype.Text `json:"user_agent"`
}

// ── Access Log ──────────────────────────────────────────────────────────────
func (q *Queries) InsertSVAccessLog(ctx context.Context, arg InsertSVAccessLogParams) error {
	_, err := q.db.Exec(ctx, insertSVAccessLog,
		arg.SecretID,
		arg.OrgID,
		arg.AccessedBy,
		arg.AccessVia,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const listSVAccessLog = `-- name: ListSVAccessLog :many
SELECT id, secret_id, org_id, accessed_by, access_via,
       ip_address, user_agent, accessed_at
FROM so_access_log
WHERE org_id = $1
ORDER BY accessed_at DESC
LIMIT 500
`

func (q *Queries) ListSVAccessLog(ctx context.Context, orgID string) ([]SoAccessLog, error) {
	rows, err := q.db.Query(ctx, listSVAccessLog, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SoAccessLog{}
	for rows.Next() {
		var i SoAccessLog
		if err := rows.Scan(
			&i.ID,
			&i.SecretID,
			&i.OrgID,
			&i.AccessedBy,
			&i.AccessVia,
			&i.IpAddress,
			&i.UserAgent,
			&i.AccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSVEnvironments = `-- name: ListSVEnvironments :many
SELECT id, project_id, org_id, name, created_at
FROM so_environments
WHERE project_id = $1 AND org_id = $2
ORDER BY name
`

type ListSVEnvironmentsParams struct {
	ProjectID string `json:"project_id"`
	OrgID     string `json:"org_id"`
}

func (q *Queries) ListSVEnvironments(ctx context.Context, arg ListSVEnvironmentsParams) ([]SoEnvironments, error) {
	rows, err := q.db.Query(ctx, listSVEnvironments, arg.ProjectID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SoEnvironments{}
	for rows.Next() {
		var i SoEnvironments
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OrgID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSVProjects = `-- name: ListSVProjects :many
SELECT id, org_id, name, slug, description, created_by, created_at
FROM so_projects
WHERE org_id = $1
ORDER BY created_at DESC
`

type ListSVProjectsRow struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	CreatedBy   string             `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSVProjects(ctx context.Context, orgID string) ([]ListSVProjectsRow, error) {
	rows, err := q.db.Query(ctx, listSVProjects, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSVProjectsRow{}
	for rows.Next() {
		var i ListSVProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
