// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_permissions.sql

package db

import (
	"context"
)

const deleteUserModulePermissions = `-- name: DeleteUserModulePermissions :exec
DELETE FROM user_module_permissions WHERE org_id = $1 AND user_id = $2
`

type DeleteUserModulePermissionsParams struct {
	OrgID  string `json:"org_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteUserModulePermissions(ctx context.Context, arg DeleteUserModulePermissionsParams) error {
	_, err := q.db.Exec(ctx, deleteUserModulePermissions, arg.OrgID, arg.UserID)
	return err
}

const getUserModulePermissions = `-- name: GetUserModulePermissions :many
SELECT id, org_id, user_id, module, can_read, can_write, created_at, updated_at FROM user_module_permissions WHERE org_id = $1 AND user_id = $2
`

type GetUserModulePermissionsParams struct {
	OrgID  string `json:"org_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetUserModulePermissions(ctx context.Context, arg GetUserModulePermissionsParams) ([]UserModulePermissions, error) {
	rows, err := q.db.Query(ctx, getUserModulePermissions, arg.OrgID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserModulePermissions{}
	for rows.Next() {
		var i UserModulePermissions
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Module,
			&i.CanRead,
			&i.CanWrite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserModulePermission = `-- name: UpsertUserModulePermission :exec
INSERT INTO user_module_permissions (org_id, user_id, module, can_read, can_write)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (org_id, user_id, module)
DO UPDATE SET can_read = $4, can_write = $5, updated_at = now()
`

type UpsertUserModulePermissionParams struct {
	OrgID    string `json:"org_id"`
	UserID   string `json:"user_id"`
	Module   string `json:"module"`
	CanRead  bool   `json:"can_read"`
	CanWrite bool   `json:"can_write"`
}

func (q *Queries) UpsertUserModulePermission(ctx context.Context, arg UpsertUserModulePermissionParams) error {
	_, err := q.db.Exec(ctx, upsertUserModulePermission,
		arg.OrgID,
		arg.UserID,
		arg.Module,
		arg.CanRead,
		arg.CanWrite,
	)
	return err
}
