// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vaktprivacy.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approvePPDPIA = `-- name: ApprovePPDPIA :one
UPDATE po_dpias SET
  status      = 'approved',
  reviewed_by = $3,
  reviewed_at = NOW(),
  updated_at  = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, vvt_entry_id, title, description,
          necessity_assessment, risk_assessment, mitigation_measures,
          residual_risk, dpo_consultation, status,
          reviewed_by, reviewed_at, created_at, updated_at
`

type ApprovePPDPIAParams struct {
	ID         string      `json:"id"`
	OrgID      string      `json:"org_id"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) ApprovePPDPIA(ctx context.Context, arg ApprovePPDPIAParams) (PoDpias, error) {
	row := q.db.QueryRow(ctx, approvePPDPIA, arg.ID, arg.OrgID, arg.ReviewedBy)
	var i PoDpias
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.VvtEntryID,
		&i.Title,
		&i.Description,
		&i.NecessityAssessment,
		&i.RiskAssessment,
		&i.MitigationMeasures,
		&i.ResidualRisk,
		&i.DpoConsultation,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countPPBreaches = `-- name: CountPPBreaches :one
SELECT COUNT(*) FROM po_breaches WHERE org_id = $1
`

func (q *Queries) CountPPBreaches(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPPBreaches, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPPVVT = `-- name: CountPPVVT :one
SELECT COUNT(*) FROM po_processing_activities WHERE org_id = $1
`

func (q *Queries) CountPPVVT(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPPVVT, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPPAVV = `-- name: CreatePPAVV :one
INSERT INTO po_avvs
  (org_id, processor_name, service_description, contract_date, review_date, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, processor_name, service_description,
          contract_date, review_date, status, notes,
          template_id, body, scc_module, scc_annex_i, scc_annex_ii, scc_annex_iii,
          created_at, updated_at
`

type CreatePPAVVParams struct {
	OrgID              string      `json:"org_id"`
	ProcessorName      string      `json:"processor_name"`
	ServiceDescription string      `json:"service_description"`
	ContractDate       pgtype.Date `json:"contract_date"`
	ReviewDate         pgtype.Date `json:"review_date"`
	Notes              pgtype.Text `json:"notes"`
}

type CreatePPAVVRow struct {
	ID                 string             `json:"id"`
	OrgID              string             `json:"org_id"`
	ProcessorName      string             `json:"processor_name"`
	ServiceDescription string             `json:"service_description"`
	ContractDate       pgtype.Date        `json:"contract_date"`
	ReviewDate         pgtype.Date        `json:"review_date"`
	Status             string             `json:"status"`
	Notes              pgtype.Text        `json:"notes"`
	TemplateID         pgtype.Text        `json:"template_id"`
	Body               pgtype.Text        `json:"body"`
	SccModule          pgtype.Text        `json:"scc_module"`
	SccAnnexI          pgtype.Text        `json:"scc_annex_i"`
	SccAnnexIi         pgtype.Text        `json:"scc_annex_ii"`
	SccAnnexIii        pgtype.Text        `json:"scc_annex_iii"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePPAVV(ctx context.Context, arg CreatePPAVVParams) (CreatePPAVVRow, error) {
	row := q.db.QueryRow(ctx, createPPAVV,
		arg.OrgID,
		arg.ProcessorName,
		arg.ServiceDescription,
		arg.ContractDate,
		arg.ReviewDate,
		arg.Notes,
	)
	var i CreatePPAVVRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProcessorName,
		&i.ServiceDescription,
		&i.ContractDate,
		&i.ReviewDate,
		&i.Status,
		&i.Notes,
		&i.TemplateID,
		&i.Body,
		&i.SccModule,
		&i.SccAnnexI,
		&i.SccAnnexIi,
		&i.SccAnnexIii,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPPAVVWithBody = `-- name: CreatePPAVVWithBody :one
INSERT INTO po_avvs
  (org_id, processor_name, service_description, template_id, body, status)
VALUES ($1, $2, $3, $4, $5, 'active')
RETURNING id, org_id, processor_name, service_description,
          contract_date, review_date, status, notes,
          template_id, body, scc_module, scc_annex_i, scc_annex_ii, scc_annex_iii,
          created_at, updated_at
`

type CreatePPAVVWithBodyParams struct {
	OrgID              string      `json:"org_id"`
	ProcessorName      string      `json:"processor_name"`
	ServiceDescription string      `json:"service_description"`
	TemplateID         pgtype.Text `json:"template_id"`
	Body               pgtype.Text `json:"body"`
}

type CreatePPAVVWithBodyRow struct {
	ID                 string             `json:"id"`
	OrgID              string             `json:"org_id"`
	ProcessorName      string             `json:"processor_name"`
	ServiceDescription string             `json:"service_description"`
	ContractDate       pgtype.Date        `json:"contract_date"`
	ReviewDate         pgtype.Date        `json:"review_date"`
	Status             string             `json:"status"`
	Notes              pgtype.Text        `json:"notes"`
	TemplateID         pgtype.Text        `json:"template_id"`
	Body               pgtype.Text        `json:"body"`
	SccModule          pgtype.Text        `json:"scc_module"`
	SccAnnexI          pgtype.Text        `json:"scc_annex_i"`
	SccAnnexIi         pgtype.Text        `json:"scc_annex_ii"`
	SccAnnexIii        pgtype.Text        `json:"scc_annex_iii"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePPAVVWithBody(ctx context.Context, arg CreatePPAVVWithBodyParams) (CreatePPAVVWithBodyRow, error) {
	row := q.db.QueryRow(ctx, createPPAVVWithBody,
		arg.OrgID,
		arg.ProcessorName,
		arg.ServiceDescription,
		arg.TemplateID,
		arg.Body,
	)
	var i CreatePPAVVWithBodyRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProcessorName,
		&i.ServiceDescription,
		&i.ContractDate,
		&i.ReviewDate,
		&i.Status,
		&i.Notes,
		&i.TemplateID,
		&i.Body,
		&i.SccModule,
		&i.SccAnnexI,
		&i.SccAnnexIi,
		&i.SccAnnexIii,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPPBreach = `-- name: CreatePPBreach :one
INSERT INTO po_breaches
  (org_id, title, description, discovered_at, authority_deadline_at,
   subjects_notification_required, affected_count, data_categories)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, title, description, discovered_at,
          authority_deadline_at, authority_notified_at,
          subjects_notification_required, subjects_notified_at,
          affected_count, data_categories, status, created_at, updated_at
`

type CreatePPBreachParams struct {
	OrgID                        string             `json:"org_id"`
	Title                        string             `json:"title"`
	Description                  string             `json:"description"`
	DiscoveredAt                 pgtype.Timestamptz `json:"discovered_at"`
	AuthorityDeadlineAt          pgtype.Timestamptz `json:"authority_deadline_at"`
	SubjectsNotificationRequired bool               `json:"subjects_notification_required"`
	AffectedCount                pgtype.Int4        `json:"affected_count"`
	DataCategories               []string           `json:"data_categories"`
}

func (q *Queries) CreatePPBreach(ctx context.Context, arg CreatePPBreachParams) (PoBreaches, error) {
	row := q.db.QueryRow(ctx, createPPBreach,
		arg.OrgID,
		arg.Title,
		arg.Description,
		arg.DiscoveredAt,
		arg.AuthorityDeadlineAt,
		arg.SubjectsNotificationRequired,
		arg.AffectedCount,
		arg.DataCategories,
	)
	var i PoBreaches
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.Description,
		&i.DiscoveredAt,
		&i.AuthorityDeadlineAt,
		&i.AuthorityNotifiedAt,
		&i.SubjectsNotificationRequired,
		&i.SubjectsNotifiedAt,
		&i.AffectedCount,
		&i.DataCategories,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPPDPIA = `-- name: CreatePPDPIA :one
INSERT INTO po_dpias
  (org_id, vvt_entry_id, title, description,
   necessity_assessment, risk_assessment, mitigation_measures,
   residual_risk, dpo_consultation)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, vvt_entry_id, title, description,
          necessity_assessment, risk_assessment, mitigation_measures,
          residual_risk, dpo_consultation, status,
          reviewed_by, reviewed_at, created_at, updated_at
`

type CreatePPDPIAParams struct {
	OrgID               string      `json:"org_id"`
	VvtEntryID          pgtype.UUID `json:"vvt_entry_id"`
	Title               string      `json:"title"`
	Description         pgtype.Text `json:"description"`
	NecessityAssessment pgtype.Text `json:"necessity_assessment"`
	RiskAssessment      pgtype.Text `json:"risk_assessment"`
	MitigationMeasures  pgtype.Text `json:"mitigation_measures"`
	ResidualRisk        pgtype.Text `json:"residual_risk"`
	DpoConsultation     bool        `json:"dpo_consultation"`
}

func (q *Queries) CreatePPDPIA(ctx context.Context, arg CreatePPDPIAParams) (PoDpias, error) {
	row := q.db.QueryRow(ctx, createPPDPIA,
		arg.OrgID,
		arg.VvtEntryID,
		arg.Title,
		arg.Description,
		arg.NecessityAssessment,
		arg.RiskAssessment,
		arg.MitigationMeasures,
		arg.ResidualRisk,
		arg.DpoConsultation,
	)
	var i PoDpias
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.VvtEntryID,
		&i.Title,
		&i.Description,
		&i.NecessityAssessment,
		&i.RiskAssessment,
		&i.MitigationMeasures,
		&i.ResidualRisk,
		&i.DpoConsultation,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPPDSR = `-- name: CreatePPDSR :one
INSERT INTO po_dsr
  (org_id, requester_name, requester_email, type, description, due_date)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, requester_name, requester_email, type, description,
          status, due_date, received_at, completed_at, notes,
          token_hash, source, portal_locale, submitted_ip, verify_token_hash,
          created_at, updated_at
`

type CreatePPDSRParams struct {
	OrgID          string      `json:"org_id"`
	RequesterName  string      `json:"requester_name"`
	RequesterEmail string      `json:"requester_email"`
	Type           string      `json:"type"`
	Description    pgtype.Text `json:"description"`
	DueDate        pgtype.Date `json:"due_date"`
}

type CreatePPDSRRow struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	RequesterName   string             `json:"requester_name"`
	RequesterEmail  string             `json:"requester_email"`
	Type            string             `json:"type"`
	Description     pgtype.Text        `json:"description"`
	Status          string             `json:"status"`
	DueDate         pgtype.Date        `json:"due_date"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Notes           pgtype.Text        `json:"notes"`
	TokenHash       pgtype.Text        `json:"token_hash"`
	Source          string             `json:"source"`
	PortalLocale    pgtype.Text        `json:"portal_locale"`
	SubmittedIp     pgtype.Text        `json:"submitted_ip"`
	VerifyTokenHash pgtype.Text        `json:"verify_token_hash"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePPDSR(ctx context.Context, arg CreatePPDSRParams) (CreatePPDSRRow, error) {
	row := q.db.QueryRow(ctx, createPPDSR,
		arg.OrgID,
		arg.RequesterName,
		arg.RequesterEmail,
		arg.Type,
		arg.Description,
		arg.DueDate,
	)
	var i CreatePPDSRRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RequesterName,
		&i.RequesterEmail,
		&i.Type,
		&i.Description,
		&i.Status,
		&i.DueDate,
		&i.ReceivedAt,
		&i.CompletedAt,
		&i.Notes,
		&i.TokenHash,
		&i.Source,
		&i.PortalLocale,
		&i.SubmittedIp,
		&i.VerifyTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPPVVT = `-- name: CreatePPVVT :one
INSERT INTO po_processing_activities
  (org_id, name, purpose, legal_basis, data_categories, data_subjects,
   recipients, retention_period, third_country_transfer, safeguards, responsible_person)
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, org_id, name, purpose, legal_basis,
          data_categories, data_subjects, recipients,
          retention_period, third_country_transfer,
          safeguards, responsible_person,
          status, created_at, updated_at
`

type CreatePPVVTParams struct {
	OrgID                string      `json:"org_id"`
	Name                 string      `json:"name"`
	Purpose              string      `json:"purpose"`
	LegalBasis           string      `json:"legal_basis"`
	DataCategories       []string    `json:"data_categories"`
	DataSubjects         []string    `json:"data_subjects"`
	Recipients           []string    `json:"recipients"`
	RetentionPeriod      pgtype.Text `json:"retention_period"`
	ThirdCountryTransfer bool        `json:"third_country_transfer"`
	Safeguards           pgtype.Text `json:"safeguards"`
	ResponsiblePerson    pgtype.Text `json:"responsible_person"`
}

func (q *Queries) CreatePPVVT(ctx context.Context, arg CreatePPVVTParams) (PoVvtEntries, error) {
	row := q.db.QueryRow(ctx, createPPVVT,
		arg.OrgID,
		arg.Name,
		arg.Purpose,
		arg.LegalBasis,
		arg.DataCategories,
		arg.DataSubjects,
		arg.Recipients,
		arg.RetentionPeriod,
		arg.ThirdCountryTransfer,
		arg.Safeguards,
		arg.ResponsiblePerson,
	)
	var i PoVvtEntries
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Purpose,
		&i.LegalBasis,
		&i.DataCategories,
		&i.DataSubjects,
		&i.Recipients,
		&i.RetentionPeriod,
		&i.ThirdCountryTransfer,
		&i.Safeguards,
		&i.ResponsiblePerson,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPortalPPDSR = `-- name: CreatePortalPPDSR :one
INSERT INTO po_dsr
  (org_id, requester_name, requester_email, type, description, due_date,
   source, portal_locale, token_hash, verify_token_hash, submitted_ip)
VALUES
  ($1, $2, $3, $4, $5, $6, 'portal', $7, $8, $9, $10)
RETURNING id
`

type CreatePortalPPDSRParams struct {
	OrgID           string      `json:"org_id"`
	RequesterName   string      `json:"requester_name"`
	RequesterEmail  string      `json:"requester_email"`
	Type            string      `json:"type"`
	Description     pgtype.Text `json:"description"`
	DueDate         pgtype.Date `json:"due_date"`
	PortalLocale    pgtype.Text `json:"portal_locale"`
	TokenHash       pgtype.Text `json:"token_hash"`
	VerifyTokenHash pgtype.Text `json:"verify_token_hash"`
	SubmittedIp     pgtype.Text `json:"submitted_ip"`
}

func (q *Queries) CreatePortalPPDSR(ctx context.Context, arg CreatePortalPPDSRParams) (string, error) {
	row := q.db.QueryRow(ctx, createPortalPPDSR,
		arg.OrgID,
		arg.RequesterName,
		arg.RequesterEmail,
		arg.Type,
		arg.Description,
		arg.DueDate,
		arg.PortalLocale,
		arg.TokenHash,
		arg.VerifyTokenHash,
		arg.SubmittedIp,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deletePPAVV = `-- name: DeletePPAVV :exec
DELETE FROM po_avvs WHERE id = $1 AND org_id = $2
`

type DeletePPAVVParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeletePPAVV(ctx context.Context, arg DeletePPAVVParams) error {
	_, err := q.db.Exec(ctx, deletePPAVV, arg.ID, arg.OrgID)
	return err
}

const deletePPBreach = `-- name: DeletePPBreach :exec
DELETE FROM po_breaches WHERE id = $1 AND org_id = $2
`

type DeletePPBreachParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeletePPBreach(ctx context.Context, arg DeletePPBreachParams) error {
	_, err := q.db.Exec(ctx, deletePPBreach, arg.ID, arg.OrgID)
	return err
}

const deletePPDPIA = `-- name: DeletePPDPIA :exec
DELETE FROM po_dpias WHERE id = $1 AND org_id = $2
`

type DeletePPDPIAParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeletePPDPIA(ctx context.Context, arg DeletePPDPIAParams) error {
	_, err := q.db.Exec(ctx, deletePPDPIA, arg.ID, arg.OrgID)
	return err
}

const deletePPDSR = `-- name: DeletePPDSR :exec
DELETE FROM po_dsr WHERE id = $1 AND org_id = $2
`

type DeletePPDSRParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeletePPDSR(ctx context.Context, arg DeletePPDSRParams) error {
	_, err := q.db.Exec(ctx, deletePPDSR, arg.ID, arg.OrgID)
	return err
}

const deletePPVVT = `-- name: DeletePPVVT :exec
DELETE FROM po_processing_activities WHERE id = $1 AND org_id = $2
`

type DeletePPVVTParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeletePPVVT(ctx context.Context, arg DeletePPVVTParams) error {
	_, err := q.db.Exec(ctx, deletePPVVT, arg.ID, arg.OrgID)
	return err
}

const executePPDSRErasure = `-- name: ExecutePPDSRErasure :one
UPDATE po_dsr SET
  status       = 'completed',
  completed_at = NOW(),
  notes        = COALESCE(notes, '') || E'\n\n--- Erasure executed ---\n' || $3,
  updated_at   = NOW()
WHERE id = $1 AND org_id = $2
  AND type = 'erasure'
RETURNING id, org_id, requester_name, requester_email, type, description,
          status, due_date, received_at, completed_at, notes,
          token_hash, source, portal_locale, submitted_ip, verify_token_hash,
          created_at, updated_at
`

type ExecutePPDSRErasureParams struct {
	ID    string      `json:"id"`
	OrgID string      `json:"org_id"`
	Notes pgtype.Text `json:"notes"`
}

type ExecutePPDSRErasureRow struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	RequesterName   string             `json:"requester_name"`
	RequesterEmail  string             `json:"requester_email"`
	Type            string             `json:"type"`
	Description     pgtype.Text        `json:"description"`
	Status          string             `json:"status"`
	DueDate         pgtype.Date        `json:"due_date"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Notes           pgtype.Text        `json:"notes"`
	TokenHash       pgtype.Text        `json:"token_hash"`
	Source          string             `json:"source"`
	PortalLocale    pgtype.Text        `json:"portal_locale"`
	SubmittedIp     pgtype.Text        `json:"submitted_ip"`
	VerifyTokenHash pgtype.Text        `json:"verify_token_hash"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ExecutePPDSRErasure(ctx context.Context, arg ExecutePPDSRErasureParams) (ExecutePPDSRErasureRow, error) {
	row := q.db.QueryRow(ctx, executePPDSRErasure, arg.ID, arg.OrgID, arg.Notes)
	var i ExecutePPDSRErasureRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RequesterName,
		&i.RequesterEmail,
		&i.Type,
		&i.Description,
		&i.Status,
		&i.DueDate,
		&i.ReceivedAt,
		&i.CompletedAt,
		&i.Notes,
		&i.TokenHash,
		&i.Source,
		&i.PortalLocale,
		&i.SubmittedIp,
		&i.VerifyTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDSRPortalSettings = `-- name: GetDSRPortalSettings :one
SELECT dsr_portal_enabled, dsr_portal_slug, dsr_dpo_email, dsr_portal_intro
FROM organizations
WHERE id = $1
`

type GetDSRPortalSettingsRow struct {
	DsrPortalEnabled bool        `json:"dsr_portal_enabled"`
	DsrPortalSlug    pgtype.Text `json:"dsr_portal_slug"`
	DsrDpoEmail      pgtype.Text `json:"dsr_dpo_email"`
	DsrPortalIntro   pgtype.Text `json:"dsr_portal_intro"`
}

func (q *Queries) GetDSRPortalSettings(ctx context.Context, id string) (GetDSRPortalSettingsRow, error) {
	row := q.db.QueryRow(ctx, getDSRPortalSettings, id)
	var i GetDSRPortalSettingsRow
	err := row.Scan(
		&i.DsrPortalEnabled,
		&i.DsrPortalSlug,
		&i.DsrDpoEmail,
		&i.DsrPortalIntro,
	)
	return i, err
}

const getOrgByDSRSlug = `-- name: GetOrgByDSRSlug :one

SELECT id, name, dsr_dpo_email, dsr_portal_intro, dsr_portal_enabled
FROM organizations
WHERE dsr_portal_slug = $1
`

type GetOrgByDSRSlugRow struct {
	ID               string      `json:"id"`
	Name             string      `json:"name"`
	DsrDpoEmail      pgtype.Text `json:"dsr_dpo_email"`
	DsrPortalIntro   pgtype.Text `json:"dsr_portal_intro"`
	DsrPortalEnabled bool        `json:"dsr_portal_enabled"`
}

// ── DSR Portal Settings (on organizations table) ────────────────────────────
func (q *Queries) GetOrgByDSRSlug(ctx context.Context, dsrPortalSlug pgtype.Text) (GetOrgByDSRSlugRow, error) {
	row := q.db.QueryRow(ctx, getOrgByDSRSlug, dsrPortalSlug)
	var i GetOrgByDSRSlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DsrDpoEmail,
		&i.DsrPortalIntro,
		&i.DsrPortalEnabled,
	)
	return i, err
}

const getPPAVV = `-- name: GetPPAVV :one
SELECT id, org_id, processor_name, service_description,
       contract_date, review_date, status, notes,
       template_id, body, scc_module, scc_annex_i, scc_annex_ii, scc_annex_iii,
       created_at, updated_at
FROM po_avvs
WHERE id = $1 AND org_id = $2
`

type GetPPAVVParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

type GetPPAVVRow struct {
	ID                 string             `json:"id"`
	OrgID              string             `json:"org_id"`
	ProcessorName      string             `json:"processor_name"`
	ServiceDescription string             `json:"service_description"`
	ContractDate       pgtype.Date        `json:"contract_date"`
	ReviewDate         pgtype.Date        `json:"review_date"`
	Status             string             `json:"status"`
	Notes              pgtype.Text        `json:"notes"`
	TemplateID         pgtype.Text        `json:"template_id"`
	Body               pgtype.Text        `json:"body"`
	SccModule          pgtype.Text        `json:"scc_module"`
	SccAnnexI          pgtype.Text        `json:"scc_annex_i"`
	SccAnnexIi         pgtype.Text        `json:"scc_annex_ii"`
	SccAnnexIii        pgtype.Text        `json:"scc_annex_iii"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPPAVV(ctx context.Context, arg GetPPAVVParams) (GetPPAVVRow, error) {
	row := q.db.QueryRow(ctx, getPPAVV, arg.ID, arg.OrgID)
	var i GetPPAVVRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProcessorName,
		&i.ServiceDescription,
		&i.ContractDate,
		&i.ReviewDate,
		&i.Status,
		&i.Notes,
		&i.TemplateID,
		&i.Body,
		&i.SccModule,
		&i.SccAnnexI,
		&i.SccAnnexIi,
		&i.SccAnnexIii,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPPBreach = `-- name: GetPPBreach :one
SELECT id, org_id, title, description, discovered_at,
       authority_deadline_at, authority_notified_at,
       subjects_notification_required, subjects_notified_at,
       affected_count, data_categories, status, created_at, updated_at
FROM po_breaches
WHERE id = $1 AND org_id = $2
`

type GetPPBreachParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetPPBreach(ctx context.Context, arg GetPPBreachParams) (PoBreaches, error) {
	row := q.db.QueryRow(ctx, getPPBreach, arg.ID, arg.OrgID)
	var i PoBreaches
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.Description,
		&i.DiscoveredAt,
		&i.AuthorityDeadlineAt,
		&i.AuthorityNotifiedAt,
		&i.SubjectsNotificationRequired,
		&i.SubjectsNotifiedAt,
		&i.AffectedCount,
		&i.DataCategories,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPPDPIA = `-- name: GetPPDPIA :one
SELECT id, org_id, vvt_entry_id, title, description,
       necessity_assessment, risk_assessment, mitigation_measures,
       residual_risk, dpo_consultation, status,
       reviewed_by, reviewed_at, created_at, updated_at
FROM po_dpias
WHERE id = $1 AND org_id = $2
`

type GetPPDPIAParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetPPDPIA(ctx context.Context, arg GetPPDPIAParams) (PoDpias, error) {
	row := q.db.QueryRow(ctx, getPPDPIA, arg.ID, arg.OrgID)
	var i PoDpias
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.VvtEntryID,
		&i.Title,
		&i.Description,
		&i.NecessityAssessment,
		&i.RiskAssessment,
		&i.MitigationMeasures,
		&i.ResidualRisk,
		&i.DpoConsultation,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPPDSR = `-- name: GetPPDSR :one
SELECT id, org_id, requester_name, requester_email, type, description,
       status, due_date, received_at, completed_at, notes,
       token_hash, source, portal_locale, submitted_ip, verify_token_hash,
       created_at, updated_at, resolved_by::text, extension_reason
FROM po_dsr
WHERE id = $1 AND org_id = $2
`

type GetPPDSRParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

type GetPPDSRRow struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	RequesterName   string             `json:"requester_name"`
	RequesterEmail  string             `json:"requester_email"`
	Type            string             `json:"type"`
	Description     pgtype.Text        `json:"description"`
	Status          string             `json:"status"`
	DueDate         pgtype.Date        `json:"due_date"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Notes           pgtype.Text        `json:"notes"`
	TokenHash       pgtype.Text        `json:"token_hash"`
	Source          string             `json:"source"`
	PortalLocale    pgtype.Text        `json:"portal_locale"`
	SubmittedIp     pgtype.Text        `json:"submitted_ip"`
	VerifyTokenHash pgtype.Text        `json:"verify_token_hash"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ResolvedBy      pgtype.Text        `json:"resolved_by"`
	ExtensionReason pgtype.Text        `json:"extension_reason"`
}

func (q *Queries) GetPPDSR(ctx context.Context, arg GetPPDSRParams) (GetPPDSRRow, error) {
	row := q.db.QueryRow(ctx, getPPDSR, arg.ID, arg.OrgID)
	var i GetPPDSRRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RequesterName,
		&i.RequesterEmail,
		&i.Type,
		&i.Description,
		&i.Status,
		&i.DueDate,
		&i.ReceivedAt,
		&i.CompletedAt,
		&i.Notes,
		&i.TokenHash,
		&i.Source,
		&i.PortalLocale,
		&i.SubmittedIp,
		&i.VerifyTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedBy,
		&i.ExtensionReason,
	)
	return i, err
}

const getPPDSRByTokenHash = `-- name: GetPPDSRByTokenHash :one
SELECT id, org_id, requester_name, requester_email, type, description,
       status, due_date, received_at, completed_at, notes,
       token_hash, source, portal_locale, submitted_ip, verify_token_hash,
       created_at, updated_at
FROM po_dsr
WHERE token_hash = $1
`

type GetPPDSRByTokenHashRow struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	RequesterName   string             `json:"requester_name"`
	RequesterEmail  string             `json:"requester_email"`
	Type            string             `json:"type"`
	Description     pgtype.Text        `json:"description"`
	Status          string             `json:"status"`
	DueDate         pgtype.Date        `json:"due_date"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Notes           pgtype.Text        `json:"notes"`
	TokenHash       pgtype.Text        `json:"token_hash"`
	Source          string             `json:"source"`
	PortalLocale    pgtype.Text        `json:"portal_locale"`
	SubmittedIp     pgtype.Text        `json:"submitted_ip"`
	VerifyTokenHash pgtype.Text        `json:"verify_token_hash"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPPDSRByTokenHash(ctx context.Context, tokenHash pgtype.Text) (GetPPDSRByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getPPDSRByTokenHash, tokenHash)
	var i GetPPDSRByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RequesterName,
		&i.RequesterEmail,
		&i.Type,
		&i.Description,
		&i.Status,
		&i.DueDate,
		&i.ReceivedAt,
		&i.CompletedAt,
		&i.Notes,
		&i.TokenHash,
		&i.Source,
		&i.PortalLocale,
		&i.SubmittedIp,
		&i.VerifyTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPPVVT = `-- name: GetPPVVT :one
SELECT id, org_id, name, purpose, legal_basis,
       data_categories, data_subjects, recipients,
       retention_period, third_country_transfer,
       safeguards, responsible_person,
       status, created_at, updated_at
FROM po_processing_activities
WHERE id = $1 AND org_id = $2
`

type GetPPVVTParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetPPVVT(ctx context.Context, arg GetPPVVTParams) (PoVvtEntries, error) {
	row := q.db.QueryRow(ctx, getPPVVT, arg.ID, arg.OrgID)
	var i PoVvtEntries
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Purpose,
		&i.LegalBasis,
		&i.DataCategories,
		&i.DataSubjects,
		&i.Recipients,
		&i.RetentionPeriod,
		&i.ThirdCountryTransfer,
		&i.Safeguards,
		&i.ResponsiblePerson,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiringPPAVVs = `-- name: ListExpiringPPAVVs :many
SELECT id, org_id, processor_name, service_description,
       contract_date, review_date, status, notes,
       template_id, body, scc_module, scc_annex_i, scc_annex_ii, scc_annex_iii,
       created_at, updated_at
FROM po_avvs
WHERE review_date IS NOT NULL
  AND review_date <= $1
  AND status = 'active'
ORDER BY review_date ASC
`

type ListExpiringPPAVVsRow struct {
	ID                 string             `json:"id"`
	OrgID              string             `json:"org_id"`
	ProcessorName      string             `json:"processor_name"`
	ServiceDescription string             `json:"service_description"`
	ContractDate       pgtype.Date        `json:"contract_date"`
	ReviewDate         pgtype.Date        `json:"review_date"`
	Status             string             `json:"status"`
	Notes              pgtype.Text        `json:"notes"`
	TemplateID         pgtype.Text        `json:"template_id"`
	Body               pgtype.Text        `json:"body"`
	SccModule          pgtype.Text        `json:"scc_module"`
	SccAnnexI          pgtype.Text        `json:"scc_annex_i"`
	SccAnnexIi         pgtype.Text        `json:"scc_annex_ii"`
	SccAnnexIii        pgtype.Text        `json:"scc_annex_iii"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListExpiringPPAVVs(ctx context.Context, reviewDate pgtype.Date) ([]ListExpiringPPAVVsRow, error) {
	rows, err := q.db.Query(ctx, listExpiringPPAVVs, reviewDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiringPPAVVsRow{}
	for rows.Next() {
		var i ListExpiringPPAVVsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProcessorName,
			&i.ServiceDescription,
			&i.ContractDate,
			&i.ReviewDate,
			&i.Status,
			&i.Notes,
			&i.TemplateID,
			&i.Body,
			&i.SccModule,
			&i.SccAnnexI,
			&i.SccAnnexIi,
			&i.SccAnnexIii,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPPAVVs = `-- name: ListPPAVVs :many

SELECT id, org_id, processor_name, service_description,
       contract_date, review_date, status, notes,
       template_id, body, scc_module, scc_annex_i, scc_annex_ii, scc_annex_iii,
       created_at, updated_at
FROM po_avvs
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT 500
`

type ListPPAVVsRow struct {
	ID                 string             `json:"id"`
	OrgID              string             `json:"org_id"`
	ProcessorName      string             `json:"processor_name"`
	ServiceDescription string             `json:"service_description"`
	ContractDate       pgtype.Date        `json:"contract_date"`
	ReviewDate         pgtype.Date        `json:"review_date"`
	Status             string             `json:"status"`
	Notes              pgtype.Text        `json:"notes"`
	TemplateID         pgtype.Text        `json:"template_id"`
	Body               pgtype.Text        `json:"body"`
	SccModule          pgtype.Text        `json:"scc_module"`
	SccAnnexI          pgtype.Text        `json:"scc_annex_i"`
	SccAnnexIi         pgtype.Text        `json:"scc_annex_ii"`
	SccAnnexIii        pgtype.Text        `json:"scc_annex_iii"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

// ── AVV (Auftragsverarbeitungsverträge) — Art. 28 DSGVO ─────────────────────
func (q *Queries) ListPPAVVs(ctx context.Context, orgID string) ([]ListPPAVVsRow, error) {
	rows, err := q.db.Query(ctx, listPPAVVs, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPPAVVsRow{}
	for rows.Next() {
		var i ListPPAVVsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProcessorName,
			&i.ServiceDescription,
			&i.ContractDate,
			&i.ReviewDate,
			&i.Status,
			&i.Notes,
			&i.TemplateID,
			&i.Body,
			&i.SccModule,
			&i.SccAnnexI,
			&i.SccAnnexIi,
			&i.SccAnnexIii,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPPBreaches = `-- name: ListPPBreaches :many

SELECT id, org_id, title, description, discovered_at,
       authority_deadline_at, authority_notified_at,
       subjects_notification_required, subjects_notified_at,
       affected_count, data_categories, status, created_at, updated_at
FROM po_breaches
WHERE org_id = $1
ORDER BY discovered_at DESC
`

// ── Breaches (Datenpannen) — Art. 33/34 DSGVO ───────────────────────────────
func (q *Queries) ListPPBreaches(ctx context.Context, orgID string) ([]PoBreaches, error) {
	rows, err := q.db.Query(ctx, listPPBreaches, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoBreaches{}
	for rows.Next() {
		var i PoBreaches
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Title,
			&i.Description,
			&i.DiscoveredAt,
			&i.AuthorityDeadlineAt,
			&i.AuthorityNotifiedAt,
			&i.SubjectsNotificationRequired,
			&i.SubjectsNotifiedAt,
			&i.AffectedCount,
			&i.DataCategories,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPPBreachesPaged = `-- name: ListPPBreachesPaged :many
SELECT id, org_id, title, description, discovered_at,
       authority_deadline_at, authority_notified_at,
       subjects_notification_required, subjects_notified_at,
       affected_count, data_categories, status, created_at, updated_at
FROM po_breaches
WHERE org_id = $1
ORDER BY discovered_at DESC
LIMIT $2 OFFSET $3
`

type ListPPBreachesPagedParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListPPBreachesPaged(ctx context.Context, arg ListPPBreachesPagedParams) ([]PoBreaches, error) {
	rows, err := q.db.Query(ctx, listPPBreachesPaged, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoBreaches{}
	for rows.Next() {
		var i PoBreaches
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Title,
			&i.Description,
			&i.DiscoveredAt,
			&i.AuthorityDeadlineAt,
			&i.AuthorityNotifiedAt,
			&i.SubjectsNotificationRequired,
			&i.SubjectsNotifiedAt,
			&i.AffectedCount,
			&i.DataCategories,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPPDPIAs = `-- name: ListPPDPIAs :many

SELECT id, org_id, vvt_entry_id, title, description,
       necessity_assessment, risk_assessment, mitigation_measures,
       residual_risk, dpo_consultation, status,
       reviewed_by, reviewed_at, created_at, updated_at
FROM po_dpias
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT 500
`

// ── DPIA (Data Protection Impact Assessment) — Art. 35 DSGVO ────────────────
func (q *Queries) ListPPDPIAs(ctx context.Context, orgID string) ([]PoDpias, error) {
	rows, err := q.db.Query(ctx, listPPDPIAs, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoDpias{}
	for rows.Next() {
		var i PoDpias
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.VvtEntryID,
			&i.Title,
			&i.Description,
			&i.NecessityAssessment,
			&i.RiskAssessment,
			&i.MitigationMeasures,
			&i.ResidualRisk,
			&i.DpoConsultation,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPPDSRs = `-- name: ListPPDSRs :many

SELECT id, org_id, requester_name, requester_email, type, description,
       status, due_date, received_at, completed_at, notes,
       token_hash, source, portal_locale, submitted_ip, verify_token_hash,
       created_at, updated_at
FROM po_dsr
WHERE org_id = $1
ORDER BY received_at DESC
LIMIT 500
`

type ListPPDSRsRow struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	RequesterName   string             `json:"requester_name"`
	RequesterEmail  string             `json:"requester_email"`
	Type            string             `json:"type"`
	Description     pgtype.Text        `json:"description"`
	Status          string             `json:"status"`
	DueDate         pgtype.Date        `json:"due_date"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Notes           pgtype.Text        `json:"notes"`
	TokenHash       pgtype.Text        `json:"token_hash"`
	Source          string             `json:"source"`
	PortalLocale    pgtype.Text        `json:"portal_locale"`
	SubmittedIp     pgtype.Text        `json:"submitted_ip"`
	VerifyTokenHash pgtype.Text        `json:"verify_token_hash"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// ── DSR (Data Subject Requests) — Art. 15-21 DSGVO ──────────────────────────
func (q *Queries) ListPPDSRs(ctx context.Context, orgID string) ([]ListPPDSRsRow, error) {
	rows, err := q.db.Query(ctx, listPPDSRs, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPPDSRsRow{}
	for rows.Next() {
		var i ListPPDSRsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RequesterName,
			&i.RequesterEmail,
			&i.Type,
			&i.Description,
			&i.Status,
			&i.DueDate,
			&i.ReceivedAt,
			&i.CompletedAt,
			&i.Notes,
			&i.TokenHash,
			&i.Source,
			&i.PortalLocale,
			&i.SubmittedIp,
			&i.VerifyTokenHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPPVVT = `-- name: ListPPVVT :many


SELECT id, org_id, name, purpose, legal_basis,
       data_categories, data_subjects, recipients,
       retention_period, third_country_transfer,
       safeguards, responsible_person,
       status, created_at, updated_at
FROM po_processing_activities
WHERE org_id = $1
ORDER BY created_at DESC
`

// SecPrivacy queries — sqlc migration started in v0.6.x (ADR-0005, inkrementell).
//
// Migrationsstand:
//
//	✅ po_processing_activities — sqlc (this file)
//	✅ po_dpias       — sqlc (this file)
//	✅ po_avvs        — sqlc (this file)
//	⏳ po_breaches    — embedded SQL
//	⏳ po_dsr         — embedded SQL (Portal-Endpoints + DTO-Filtering)
//
// po_dsr ist als Letztes geplant (öffentliches Portal + DSGVO-sensitive DTO).
// ── VVT (Verzeichnis von Verarbeitungstätigkeiten) — Art. 30 DSGVO ──────────
func (q *Queries) ListPPVVT(ctx context.Context, orgID string) ([]PoVvtEntries, error) {
	rows, err := q.db.Query(ctx, listPPVVT, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoVvtEntries{}
	for rows.Next() {
		var i PoVvtEntries
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Purpose,
			&i.LegalBasis,
			&i.DataCategories,
			&i.DataSubjects,
			&i.Recipients,
			&i.RetentionPeriod,
			&i.ThirdCountryTransfer,
			&i.Safeguards,
			&i.ResponsiblePerson,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPPVVTPaged = `-- name: ListPPVVTPaged :many

SELECT id, org_id, name, purpose, legal_basis,
       data_categories, data_subjects, recipients,
       retention_period, third_country_transfer,
       safeguards, responsible_person,
       status, created_at, updated_at
FROM po_processing_activities
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPPVVTPagedParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

// ── Paged list helpers ──────────────────────────────────────────────────────
func (q *Queries) ListPPVVTPaged(ctx context.Context, arg ListPPVVTPagedParams) ([]PoVvtEntries, error) {
	rows, err := q.db.Query(ctx, listPPVVTPaged, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoVvtEntries{}
	for rows.Next() {
		var i PoVvtEntries
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Purpose,
			&i.LegalBasis,
			&i.DataCategories,
			&i.DataSubjects,
			&i.Recipients,
			&i.RetentionPeriod,
			&i.ThirdCountryTransfer,
			&i.Safeguards,
			&i.ResponsiblePerson,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExpiredPPAVVs = `-- name: MarkExpiredPPAVVs :execrows
UPDATE po_avvs SET
  status     = 'expired',
  updated_at = NOW()
WHERE status = 'active'
  AND review_date IS NOT NULL
  AND review_date < CURRENT_DATE
`

func (q *Queries) MarkExpiredPPAVVs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markExpiredPPAVVs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPPBreachAuthorityNotified = `-- name: MarkPPBreachAuthorityNotified :exec
UPDATE po_breaches SET
  authority_notified_at = NOW(),
  updated_at            = NOW()
WHERE id = $1 AND org_id = $2
`

type MarkPPBreachAuthorityNotifiedParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) MarkPPBreachAuthorityNotified(ctx context.Context, arg MarkPPBreachAuthorityNotifiedParams) error {
	_, err := q.db.Exec(ctx, markPPBreachAuthorityNotified, arg.ID, arg.OrgID)
	return err
}

const updateDSRPortalSettings = `-- name: UpdateDSRPortalSettings :exec
UPDATE organizations SET
  dsr_portal_enabled = $2,
  dsr_portal_slug    = $3,
  dsr_dpo_email      = $4,
  dsr_portal_intro   = $5
WHERE id = $1
`

type UpdateDSRPortalSettingsParams struct {
	ID               string      `json:"id"`
	DsrPortalEnabled bool        `json:"dsr_portal_enabled"`
	DsrPortalSlug    pgtype.Text `json:"dsr_portal_slug"`
	DsrDpoEmail      pgtype.Text `json:"dsr_dpo_email"`
	DsrPortalIntro   pgtype.Text `json:"dsr_portal_intro"`
}

func (q *Queries) UpdateDSRPortalSettings(ctx context.Context, arg UpdateDSRPortalSettingsParams) error {
	_, err := q.db.Exec(ctx, updateDSRPortalSettings,
		arg.ID,
		arg.DsrPortalEnabled,
		arg.DsrPortalSlug,
		arg.DsrDpoEmail,
		arg.DsrPortalIntro,
	)
	return err
}

const updatePPAVV = `-- name: UpdatePPAVV :one
UPDATE po_avvs SET
  processor_name      = $3,
  service_description = $4,
  contract_date       = $5,
  review_date         = $6,
  status              = $7,
  notes               = $8,
  updated_at          = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, processor_name, service_description,
          contract_date, review_date, status, notes,
          template_id, body, scc_module, scc_annex_i, scc_annex_ii, scc_annex_iii,
          created_at, updated_at
`

type UpdatePPAVVParams struct {
	ID                 string      `json:"id"`
	OrgID              string      `json:"org_id"`
	ProcessorName      string      `json:"processor_name"`
	ServiceDescription string      `json:"service_description"`
	ContractDate       pgtype.Date `json:"contract_date"`
	ReviewDate         pgtype.Date `json:"review_date"`
	Status             string      `json:"status"`
	Notes              pgtype.Text `json:"notes"`
}

type UpdatePPAVVRow struct {
	ID                 string             `json:"id"`
	OrgID              string             `json:"org_id"`
	ProcessorName      string             `json:"processor_name"`
	ServiceDescription string             `json:"service_description"`
	ContractDate       pgtype.Date        `json:"contract_date"`
	ReviewDate         pgtype.Date        `json:"review_date"`
	Status             string             `json:"status"`
	Notes              pgtype.Text        `json:"notes"`
	TemplateID         pgtype.Text        `json:"template_id"`
	Body               pgtype.Text        `json:"body"`
	SccModule          pgtype.Text        `json:"scc_module"`
	SccAnnexI          pgtype.Text        `json:"scc_annex_i"`
	SccAnnexIi         pgtype.Text        `json:"scc_annex_ii"`
	SccAnnexIii        pgtype.Text        `json:"scc_annex_iii"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePPAVV(ctx context.Context, arg UpdatePPAVVParams) (UpdatePPAVVRow, error) {
	row := q.db.QueryRow(ctx, updatePPAVV,
		arg.ID,
		arg.OrgID,
		arg.ProcessorName,
		arg.ServiceDescription,
		arg.ContractDate,
		arg.ReviewDate,
		arg.Status,
		arg.Notes,
	)
	var i UpdatePPAVVRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProcessorName,
		&i.ServiceDescription,
		&i.ContractDate,
		&i.ReviewDate,
		&i.Status,
		&i.Notes,
		&i.TemplateID,
		&i.Body,
		&i.SccModule,
		&i.SccAnnexI,
		&i.SccAnnexIi,
		&i.SccAnnexIii,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePPAVVBody = `-- name: UpdatePPAVVBody :exec
UPDATE po_avvs SET
  template_id = $3,
  body        = $4,
  updated_at  = NOW()
WHERE id = $1 AND org_id = $2
`

type UpdatePPAVVBodyParams struct {
	ID         string      `json:"id"`
	OrgID      string      `json:"org_id"`
	TemplateID pgtype.Text `json:"template_id"`
	Body       pgtype.Text `json:"body"`
}

func (q *Queries) UpdatePPAVVBody(ctx context.Context, arg UpdatePPAVVBodyParams) error {
	_, err := q.db.Exec(ctx, updatePPAVVBody,
		arg.ID,
		arg.OrgID,
		arg.TemplateID,
		arg.Body,
	)
	return err
}

const updatePPAVVSCC = `-- name: UpdatePPAVVSCC :exec
UPDATE po_avvs SET
  scc_module     = $3,
  scc_annex_i    = $4,
  scc_annex_ii   = $5,
  scc_annex_iii  = $6,
  updated_at     = NOW()
WHERE id = $1 AND org_id = $2
`

type UpdatePPAVVSCCParams struct {
	ID          string      `json:"id"`
	OrgID       string      `json:"org_id"`
	SccModule   pgtype.Text `json:"scc_module"`
	SccAnnexI   pgtype.Text `json:"scc_annex_i"`
	SccAnnexIi  pgtype.Text `json:"scc_annex_ii"`
	SccAnnexIii pgtype.Text `json:"scc_annex_iii"`
}

func (q *Queries) UpdatePPAVVSCC(ctx context.Context, arg UpdatePPAVVSCCParams) error {
	_, err := q.db.Exec(ctx, updatePPAVVSCC,
		arg.ID,
		arg.OrgID,
		arg.SccModule,
		arg.SccAnnexI,
		arg.SccAnnexIi,
		arg.SccAnnexIii,
	)
	return err
}

const updatePPBreach = `-- name: UpdatePPBreach :one
UPDATE po_breaches SET
  title                          = $3,
  description                    = $4,
  subjects_notification_required = $5,
  affected_count                 = $6,
  data_categories                = $7,
  updated_at                     = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, title, description, discovered_at,
          authority_deadline_at, authority_notified_at,
          subjects_notification_required, subjects_notified_at,
          affected_count, data_categories, status, created_at, updated_at
`

type UpdatePPBreachParams struct {
	ID                           string      `json:"id"`
	OrgID                        string      `json:"org_id"`
	Title                        string      `json:"title"`
	Description                  string      `json:"description"`
	SubjectsNotificationRequired bool        `json:"subjects_notification_required"`
	AffectedCount                pgtype.Int4 `json:"affected_count"`
	DataCategories               []string    `json:"data_categories"`
}

func (q *Queries) UpdatePPBreach(ctx context.Context, arg UpdatePPBreachParams) (PoBreaches, error) {
	row := q.db.QueryRow(ctx, updatePPBreach,
		arg.ID,
		arg.OrgID,
		arg.Title,
		arg.Description,
		arg.SubjectsNotificationRequired,
		arg.AffectedCount,
		arg.DataCategories,
	)
	var i PoBreaches
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.Description,
		&i.DiscoveredAt,
		&i.AuthorityDeadlineAt,
		&i.AuthorityNotifiedAt,
		&i.SubjectsNotificationRequired,
		&i.SubjectsNotifiedAt,
		&i.AffectedCount,
		&i.DataCategories,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePPBreachStatus = `-- name: UpdatePPBreachStatus :exec
UPDATE po_breaches SET status = $3, updated_at = NOW()
WHERE id = $1 AND org_id = $2
`

type UpdatePPBreachStatusParams struct {
	ID     string `json:"id"`
	OrgID  string `json:"org_id"`
	Status string `json:"status"`
}

func (q *Queries) UpdatePPBreachStatus(ctx context.Context, arg UpdatePPBreachStatusParams) error {
	_, err := q.db.Exec(ctx, updatePPBreachStatus, arg.ID, arg.OrgID, arg.Status)
	return err
}

const updatePPDPIA = `-- name: UpdatePPDPIA :one
UPDATE po_dpias SET
  title               = $3,
  description         = $4,
  necessity_assessment = $5,
  risk_assessment     = $6,
  mitigation_measures = $7,
  residual_risk       = $8,
  dpo_consultation    = $9,
  updated_at          = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, vvt_entry_id, title, description,
          necessity_assessment, risk_assessment, mitigation_measures,
          residual_risk, dpo_consultation, status,
          reviewed_by, reviewed_at, created_at, updated_at
`

type UpdatePPDPIAParams struct {
	ID                  string      `json:"id"`
	OrgID               string      `json:"org_id"`
	Title               string      `json:"title"`
	Description         pgtype.Text `json:"description"`
	NecessityAssessment pgtype.Text `json:"necessity_assessment"`
	RiskAssessment      pgtype.Text `json:"risk_assessment"`
	MitigationMeasures  pgtype.Text `json:"mitigation_measures"`
	ResidualRisk        pgtype.Text `json:"residual_risk"`
	DpoConsultation     bool        `json:"dpo_consultation"`
}

// vvt_entry_id is intentionally not in the SET list: the link to the originating
// VVT entry is set at creation and never re-pointed by an update — DSGVO Art. 35
// ties a DPIA to a specific processing activity. Use Delete + Create if the
// target activity changes.
func (q *Queries) UpdatePPDPIA(ctx context.Context, arg UpdatePPDPIAParams) (PoDpias, error) {
	row := q.db.QueryRow(ctx, updatePPDPIA,
		arg.ID,
		arg.OrgID,
		arg.Title,
		arg.Description,
		arg.NecessityAssessment,
		arg.RiskAssessment,
		arg.MitigationMeasures,
		arg.ResidualRisk,
		arg.DpoConsultation,
	)
	var i PoDpias
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.VvtEntryID,
		&i.Title,
		&i.Description,
		&i.NecessityAssessment,
		&i.RiskAssessment,
		&i.MitigationMeasures,
		&i.ResidualRisk,
		&i.DpoConsultation,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePPDSR = `-- name: UpdatePPDSR :one
UPDATE po_dsr SET
  status       = $3,
  notes        = $4,
  completed_at = $5,
  updated_at   = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, requester_name, requester_email, type, description,
          status, due_date, received_at, completed_at, notes,
          token_hash, source, portal_locale, submitted_ip, verify_token_hash,
          created_at, updated_at
`

type UpdatePPDSRParams struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	Status      string             `json:"status"`
	Notes       pgtype.Text        `json:"notes"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type UpdatePPDSRRow struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	RequesterName   string             `json:"requester_name"`
	RequesterEmail  string             `json:"requester_email"`
	Type            string             `json:"type"`
	Description     pgtype.Text        `json:"description"`
	Status          string             `json:"status"`
	DueDate         pgtype.Date        `json:"due_date"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Notes           pgtype.Text        `json:"notes"`
	TokenHash       pgtype.Text        `json:"token_hash"`
	Source          string             `json:"source"`
	PortalLocale    pgtype.Text        `json:"portal_locale"`
	SubmittedIp     pgtype.Text        `json:"submitted_ip"`
	VerifyTokenHash pgtype.Text        `json:"verify_token_hash"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePPDSR(ctx context.Context, arg UpdatePPDSRParams) (UpdatePPDSRRow, error) {
	row := q.db.QueryRow(ctx, updatePPDSR,
		arg.ID,
		arg.OrgID,
		arg.Status,
		arg.Notes,
		arg.CompletedAt,
	)
	var i UpdatePPDSRRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RequesterName,
		&i.RequesterEmail,
		&i.Type,
		&i.Description,
		&i.Status,
		&i.DueDate,
		&i.ReceivedAt,
		&i.CompletedAt,
		&i.Notes,
		&i.TokenHash,
		&i.Source,
		&i.PortalLocale,
		&i.SubmittedIp,
		&i.VerifyTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePPVVT = `-- name: UpdatePPVVT :one
UPDATE po_processing_activities SET
  name = $3, purpose = $4, legal_basis = $5,
  data_categories = $6, data_subjects = $7, recipients = $8,
  retention_period = $9, third_country_transfer = $10,
  safeguards = $11, responsible_person = $12, status = $13,
  updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, purpose, legal_basis,
          data_categories, data_subjects, recipients,
          retention_period, third_country_transfer,
          safeguards, responsible_person,
          status, created_at, updated_at
`

type UpdatePPVVTParams struct {
	ID                   string      `json:"id"`
	OrgID                string      `json:"org_id"`
	Name                 string      `json:"name"`
	Purpose              string      `json:"purpose"`
	LegalBasis           string      `json:"legal_basis"`
	DataCategories       []string    `json:"data_categories"`
	DataSubjects         []string    `json:"data_subjects"`
	Recipients           []string    `json:"recipients"`
	RetentionPeriod      pgtype.Text `json:"retention_period"`
	ThirdCountryTransfer bool        `json:"third_country_transfer"`
	Safeguards           pgtype.Text `json:"safeguards"`
	ResponsiblePerson    pgtype.Text `json:"responsible_person"`
	Status               string      `json:"status"`
}

func (q *Queries) UpdatePPVVT(ctx context.Context, arg UpdatePPVVTParams) (PoVvtEntries, error) {
	row := q.db.QueryRow(ctx, updatePPVVT,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Purpose,
		arg.LegalBasis,
		arg.DataCategories,
		arg.DataSubjects,
		arg.Recipients,
		arg.RetentionPeriod,
		arg.ThirdCountryTransfer,
		arg.Safeguards,
		arg.ResponsiblePerson,
		arg.Status,
	)
	var i PoVvtEntries
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Purpose,
		&i.LegalBasis,
		&i.DataCategories,
		&i.DataSubjects,
		&i.Recipients,
		&i.RetentionPeriod,
		&i.ThirdCountryTransfer,
		&i.Safeguards,
		&i.ResponsiblePerson,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
