// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vakthr.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHREmployees = `-- name: CountHREmployees :one
SELECT COUNT(*) FROM hr_employees WHERE org_id = $1
`

func (q *Queries) CountHREmployees(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRow(ctx, countHREmployees, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHRChecklist = `-- name: CreateHRChecklist :one
INSERT INTO hr_checklists (org_id, type, name, items)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, type, name, items, created_at, updated_at
`

type CreateHRChecklistParams struct {
	OrgID string          `json:"org_id"`
	Type  string          `json:"type"`
	Name  string          `json:"name"`
	Items json.RawMessage `json:"items"`
}

func (q *Queries) CreateHRChecklist(ctx context.Context, arg CreateHRChecklistParams) (HrChecklists, error) {
	row := q.db.QueryRow(ctx, createHRChecklist,
		arg.OrgID,
		arg.Type,
		arg.Name,
		arg.Items,
	)
	var i HrChecklists
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Type,
		&i.Name,
		&i.Items,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createHREmployee = `-- name: CreateHREmployee :one
INSERT INTO hr_employees (org_id, first_name, last_name, email, department, role, start_date, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, first_name, last_name, email, department, role,
          start_date, end_date, status, notes, created_at, updated_at
`

type CreateHREmployeeParams struct {
	OrgID      string      `json:"org_id"`
	FirstName  string      `json:"first_name"`
	LastName   string      `json:"last_name"`
	Email      string      `json:"email"`
	Department pgtype.Text `json:"department"`
	Role       pgtype.Text `json:"role"`
	StartDate  pgtype.Date `json:"start_date"`
	Notes      pgtype.Text `json:"notes"`
}

func (q *Queries) CreateHREmployee(ctx context.Context, arg CreateHREmployeeParams) (HrEmployees, error) {
	row := q.db.QueryRow(ctx, createHREmployee,
		arg.OrgID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Department,
		arg.Role,
		arg.StartDate,
		arg.Notes,
	)
	var i HrEmployees
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Department,
		&i.Role,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHRChecklist = `-- name: DeleteHRChecklist :exec
DELETE FROM hr_checklists WHERE org_id = $1 AND id = $2
`

type DeleteHRChecklistParams struct {
	OrgID string `json:"org_id"`
	ID    string `json:"id"`
}

func (q *Queries) DeleteHRChecklist(ctx context.Context, arg DeleteHRChecklistParams) error {
	_, err := q.db.Exec(ctx, deleteHRChecklist, arg.OrgID, arg.ID)
	return err
}

const deleteHREmployee = `-- name: DeleteHREmployee :exec
DELETE FROM hr_employees WHERE org_id = $1 AND id = $2
`

type DeleteHREmployeeParams struct {
	OrgID string `json:"org_id"`
	ID    string `json:"id"`
}

func (q *Queries) DeleteHREmployee(ctx context.Context, arg DeleteHREmployeeParams) error {
	_, err := q.db.Exec(ctx, deleteHREmployee, arg.OrgID, arg.ID)
	return err
}

const firstHRChecklistByType = `-- name: FirstHRChecklistByType :one
SELECT id, org_id, type, name, items, created_at, updated_at
FROM hr_checklists
WHERE org_id = $1 AND type = $2
ORDER BY created_at ASC
LIMIT 1
`

type FirstHRChecklistByTypeParams struct {
	OrgID string `json:"org_id"`
	Type  string `json:"type"`
}

func (q *Queries) FirstHRChecklistByType(ctx context.Context, arg FirstHRChecklistByTypeParams) (HrChecklists, error) {
	row := q.db.QueryRow(ctx, firstHRChecklistByType, arg.OrgID, arg.Type)
	var i HrChecklists
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Type,
		&i.Name,
		&i.Items,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHRChecklist = `-- name: GetHRChecklist :one
SELECT id, org_id, type, name, items, created_at, updated_at
FROM hr_checklists
WHERE org_id = $1 AND id = $2
`

type GetHRChecklistParams struct {
	OrgID string `json:"org_id"`
	ID    string `json:"id"`
}

func (q *Queries) GetHRChecklist(ctx context.Context, arg GetHRChecklistParams) (HrChecklists, error) {
	row := q.db.QueryRow(ctx, getHRChecklist, arg.OrgID, arg.ID)
	var i HrChecklists
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Type,
		&i.Name,
		&i.Items,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHRChecklistRun = `-- name: GetHRChecklistRun :one
SELECT id, org_id, employee_id, checklist_id, status, completed_items,
       started_at, completed_at, created_at, updated_at
FROM hr_checklist_runs
WHERE org_id = $1 AND id = $2
`

type GetHRChecklistRunParams struct {
	OrgID string `json:"org_id"`
	ID    string `json:"id"`
}

func (q *Queries) GetHRChecklistRun(ctx context.Context, arg GetHRChecklistRunParams) (HrChecklistRuns, error) {
	row := q.db.QueryRow(ctx, getHRChecklistRun, arg.OrgID, arg.ID)
	var i HrChecklistRuns
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.EmployeeID,
		&i.ChecklistID,
		&i.Status,
		&i.CompletedItems,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHREmployee = `-- name: GetHREmployee :one
SELECT id, org_id, first_name, last_name, email, department, role,
       start_date, end_date, status, notes, created_at, updated_at
FROM hr_employees
WHERE org_id = $1 AND id = $2
`

type GetHREmployeeParams struct {
	OrgID string `json:"org_id"`
	ID    string `json:"id"`
}

func (q *Queries) GetHREmployee(ctx context.Context, arg GetHREmployeeParams) (HrEmployees, error) {
	row := q.db.QueryRow(ctx, getHREmployee, arg.OrgID, arg.ID)
	var i HrEmployees
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Department,
		&i.Role,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHREmployeeByEmail = `-- name: GetHREmployeeByEmail :one
SELECT id, org_id, first_name, last_name, email, department, role,
       start_date, end_date, status, notes, created_at, updated_at
FROM hr_employees
WHERE org_id = $1 AND email = $2
`

type GetHREmployeeByEmailParams struct {
	OrgID string `json:"org_id"`
	Email string `json:"email"`
}

func (q *Queries) GetHREmployeeByEmail(ctx context.Context, arg GetHREmployeeByEmailParams) (HrEmployees, error) {
	row := q.db.QueryRow(ctx, getHREmployeeByEmail, arg.OrgID, arg.Email)
	var i HrEmployees
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Department,
		&i.Role,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertHRRunEvent = `-- name: InsertHRRunEvent :exec
INSERT INTO hr_run_events (run_id, org_id, step_id, completed_by)
VALUES ($1, $2, $3, $4)
`

type InsertHRRunEventParams struct {
	RunID       string `json:"run_id"`
	OrgID       string `json:"org_id"`
	StepID      string `json:"step_id"`
	CompletedBy string `json:"completed_by"`
}

func (q *Queries) InsertHRRunEvent(ctx context.Context, arg InsertHRRunEventParams) error {
	_, err := q.db.Exec(ctx, insertHRRunEvent,
		arg.RunID,
		arg.OrgID,
		arg.StepID,
		arg.CompletedBy,
	)
	return err
}

const listHRChecklistRuns = `-- name: ListHRChecklistRuns :many
SELECT id, org_id, employee_id, checklist_id, status, completed_items,
       started_at, completed_at, created_at, updated_at
FROM hr_checklist_runs
WHERE org_id = $1 AND employee_id = $2
ORDER BY started_at DESC
`

type ListHRChecklistRunsParams struct {
	OrgID      string `json:"org_id"`
	EmployeeID string `json:"employee_id"`
}

func (q *Queries) ListHRChecklistRuns(ctx context.Context, arg ListHRChecklistRunsParams) ([]HrChecklistRuns, error) {
	rows, err := q.db.Query(ctx, listHRChecklistRuns, arg.OrgID, arg.EmployeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HrChecklistRuns{}
	for rows.Next() {
		var i HrChecklistRuns
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.EmployeeID,
			&i.ChecklistID,
			&i.Status,
			&i.CompletedItems,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHRChecklists = `-- name: ListHRChecklists :many
SELECT id, org_id, type, name, items, created_at, updated_at
FROM hr_checklists
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListHRChecklists(ctx context.Context, orgID string) ([]HrChecklists, error) {
	rows, err := q.db.Query(ctx, listHRChecklists, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HrChecklists{}
	for rows.Next() {
		var i HrChecklists
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Type,
			&i.Name,
			&i.Items,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHREmployees = `-- name: ListHREmployees :many
SELECT id, org_id, first_name, last_name, email, department, role,
       start_date, end_date, status, notes, created_at, updated_at
FROM hr_employees
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListHREmployeesParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListHREmployees(ctx context.Context, arg ListHREmployeesParams) ([]HrEmployees, error) {
	rows, err := q.db.Query(ctx, listHREmployees, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HrEmployees{}
	for rows.Next() {
		var i HrEmployees
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Department,
			&i.Role,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHRRunEvents = `-- name: ListHRRunEvents :many
SELECT id, run_id, org_id, step_id, completed_by, completed_at
FROM hr_run_events
WHERE org_id = $1 AND run_id = $2
ORDER BY completed_at ASC
`

type ListHRRunEventsParams struct {
	OrgID string `json:"org_id"`
	RunID string `json:"run_id"`
}

func (q *Queries) ListHRRunEvents(ctx context.Context, arg ListHRRunEventsParams) ([]HrRunEvents, error) {
	rows, err := q.db.Query(ctx, listHRRunEvents, arg.OrgID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HrRunEvents{}
	for rows.Next() {
		var i HrRunEvents
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.OrgID,
			&i.StepID,
			&i.CompletedBy,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setHREmployeeStatus = `-- name: SetHREmployeeStatus :exec
UPDATE hr_employees
SET status = $3, updated_at = now()
WHERE org_id = $1 AND id = $2
`

type SetHREmployeeStatusParams struct {
	OrgID  string `json:"org_id"`
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetHREmployeeStatus(ctx context.Context, arg SetHREmployeeStatusParams) error {
	_, err := q.db.Exec(ctx, setHREmployeeStatus, arg.OrgID, arg.ID, arg.Status)
	return err
}

const startHRChecklistRun = `-- name: StartHRChecklistRun :one
INSERT INTO hr_checklist_runs (org_id, employee_id, checklist_id)
VALUES ($1, $2, $3)
RETURNING id, org_id, employee_id, checklist_id, status, completed_items,
          started_at, completed_at, created_at, updated_at
`

type StartHRChecklistRunParams struct {
	OrgID       string `json:"org_id"`
	EmployeeID  string `json:"employee_id"`
	ChecklistID string `json:"checklist_id"`
}

func (q *Queries) StartHRChecklistRun(ctx context.Context, arg StartHRChecklistRunParams) (HrChecklistRuns, error) {
	row := q.db.QueryRow(ctx, startHRChecklistRun, arg.OrgID, arg.EmployeeID, arg.ChecklistID)
	var i HrChecklistRuns
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.EmployeeID,
		&i.ChecklistID,
		&i.Status,
		&i.CompletedItems,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHRChecklistRun = `-- name: UpdateHRChecklistRun :one
UPDATE hr_checklist_runs
SET completed_items = $3,
    status          = $4,
    completed_at    = $5,
    updated_at      = now()
WHERE org_id = $1 AND id = $2
RETURNING id, org_id, employee_id, checklist_id, status, completed_items,
          started_at, completed_at, created_at, updated_at
`

type UpdateHRChecklistRunParams struct {
	OrgID          string             `json:"org_id"`
	ID             string             `json:"id"`
	CompletedItems json.RawMessage    `json:"completed_items"`
	Status         string             `json:"status"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateHRChecklistRun(ctx context.Context, arg UpdateHRChecklistRunParams) (HrChecklistRuns, error) {
	row := q.db.QueryRow(ctx, updateHRChecklistRun,
		arg.OrgID,
		arg.ID,
		arg.CompletedItems,
		arg.Status,
		arg.CompletedAt,
	)
	var i HrChecklistRuns
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.EmployeeID,
		&i.ChecklistID,
		&i.Status,
		&i.CompletedItems,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHREmployee = `-- name: UpdateHREmployee :one
UPDATE hr_employees
SET first_name = $3,
    last_name  = $4,
    department = $5,
    role       = $6,
    end_date   = $7,
    status     = $8,
    notes      = $9,
    updated_at = now()
WHERE org_id = $1 AND id = $2
RETURNING id, org_id, first_name, last_name, email, department, role,
          start_date, end_date, status, notes, created_at, updated_at
`

type UpdateHREmployeeParams struct {
	OrgID      string      `json:"org_id"`
	ID         string      `json:"id"`
	FirstName  string      `json:"first_name"`
	LastName   string      `json:"last_name"`
	Department pgtype.Text `json:"department"`
	Role       pgtype.Text `json:"role"`
	EndDate    pgtype.Date `json:"end_date"`
	Status     string      `json:"status"`
	Notes      pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateHREmployee(ctx context.Context, arg UpdateHREmployeeParams) (HrEmployees, error) {
	row := q.db.QueryRow(ctx, updateHREmployee,
		arg.OrgID,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Department,
		arg.Role,
		arg.EndDate,
		arg.Status,
		arg.Notes,
	)
	var i HrEmployees
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Department,
		&i.Role,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hRRevokeUserSessions = `-- name: HRRevokeUserSessions :exec
DELETE FROM refresh_sessions rs
USING users u
WHERE rs.user_id = u.id
  AND rs.org_id  = $1::uuid
  AND u.email    = $2
`

type HRRevokeUserSessionsParams struct {
	OrgID string `json:"org_id"`
	Email string `json:"email"`
}

func (q *Queries) HRRevokeUserSessions(ctx context.Context, arg HRRevokeUserSessionsParams) error {
	_, err := q.db.Exec(ctx, hRRevokeUserSessions, arg.OrgID, arg.Email)
	return err
}

const hRDisableUser = `-- name: HRDisableUser :exec
DELETE FROM org_members om
USING users u
WHERE om.user_id = u.id
  AND om.org_id  = $1::uuid
  AND u.email    = $2
`

type HRDisableUserParams struct {
	OrgID string `json:"org_id"`
	Email string `json:"email"`
}

func (q *Queries) HRDisableUser(ctx context.Context, arg HRDisableUserParams) error {
	_, err := q.db.Exec(ctx, hRDisableUser, arg.OrgID, arg.Email)
	return err
}

const hRRevokeUserAPIKeys = `-- name: HRRevokeUserAPIKeys :exec
UPDATE api_keys ak SET revoked_at = NOW()
FROM users u
WHERE ak.created_by = u.id
  AND ak.org_id     = $1::uuid
  AND u.email       = $2
  AND ak.revoked_at IS NULL
`

type HRRevokeUserAPIKeysParams struct {
	OrgID string `json:"org_id"`
	Email string `json:"email"`
}

func (q *Queries) HRRevokeUserAPIKeys(ctx context.Context, arg HRRevokeUserAPIKeysParams) error {
	_, err := q.db.Exec(ctx, hRRevokeUserAPIKeys, arg.OrgID, arg.Email)
	return err
}

// ── S60: Berechtigungskonzept ─────────────────────────────────────────────────

const createHRAccessConcept = `-- name: CreateHRAccessConcept :one
INSERT INTO hr_access_concepts (org_id, title, scope, owner)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, title, scope, owner, current_version, created_at, updated_at
`

type CreateHRAccessConceptParams struct {
	OrgID string `json:"org_id"`
	Title string `json:"title"`
	Scope string `json:"scope"`
	Owner string `json:"owner"`
}

func (q *Queries) CreateHRAccessConcept(ctx context.Context, arg CreateHRAccessConceptParams) (HrAccessConcepts, error) {
	row := q.db.QueryRow(ctx, createHRAccessConcept, arg.OrgID, arg.Title, arg.Scope, arg.Owner)
	var i HrAccessConcepts
	err := row.Scan(&i.ID, &i.OrgID, &i.Title, &i.Scope, &i.Owner, &i.CurrentVersion, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const listHRAccessConcepts = `-- name: ListHRAccessConcepts :many
SELECT id, org_id, title, scope, owner, current_version, created_at, updated_at FROM hr_access_concepts
WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListHRAccessConcepts(ctx context.Context, orgID string) ([]HrAccessConcepts, error) {
	rows, err := q.db.Query(ctx, listHRAccessConcepts, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HrAccessConcepts{}
	for rows.Next() {
		var i HrAccessConcepts
		if err := rows.Scan(&i.ID, &i.OrgID, &i.Title, &i.Scope, &i.Owner, &i.CurrentVersion, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getHRAccessConcept = `-- name: GetHRAccessConcept :one
SELECT id, org_id, title, scope, owner, current_version, created_at, updated_at FROM hr_access_concepts
WHERE id = $1 AND org_id = $2
`

type GetHRAccessConceptParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetHRAccessConcept(ctx context.Context, arg GetHRAccessConceptParams) (HrAccessConcepts, error) {
	row := q.db.QueryRow(ctx, getHRAccessConcept, arg.ID, arg.OrgID)
	var i HrAccessConcepts
	err := row.Scan(&i.ID, &i.OrgID, &i.Title, &i.Scope, &i.Owner, &i.CurrentVersion, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const updateHRAccessConcept = `-- name: UpdateHRAccessConcept :one
UPDATE hr_access_concepts SET title = $3, scope = $4, owner = $5, updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, title, scope, owner, current_version, created_at, updated_at
`

type UpdateHRAccessConceptParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
	Title string `json:"title"`
	Scope string `json:"scope"`
	Owner string `json:"owner"`
}

func (q *Queries) UpdateHRAccessConcept(ctx context.Context, arg UpdateHRAccessConceptParams) (HrAccessConcepts, error) {
	row := q.db.QueryRow(ctx, updateHRAccessConcept, arg.ID, arg.OrgID, arg.Title, arg.Scope, arg.Owner)
	var i HrAccessConcepts
	err := row.Scan(&i.ID, &i.OrgID, &i.Title, &i.Scope, &i.Owner, &i.CurrentVersion, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteHRAccessConcept = `-- name: DeleteHRAccessConcept :execrows
DELETE FROM hr_access_concepts WHERE id = $1 AND org_id = $2
`

type DeleteHRAccessConceptParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeleteHRAccessConcept(ctx context.Context, arg DeleteHRAccessConceptParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHRAccessConcept, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const incrementHRAccessConceptVersion = `-- name: IncrementHRAccessConceptVersion :one
UPDATE hr_access_concepts SET current_version = current_version + 1, updated_at = NOW()
WHERE id = $1 AND org_id = $2 RETURNING current_version
`

type IncrementHRAccessConceptVersionParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) IncrementHRAccessConceptVersion(ctx context.Context, arg IncrementHRAccessConceptVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementHRAccessConceptVersion, arg.ID, arg.OrgID)
	var currentVersion int32
	err := row.Scan(&currentVersion)
	return currentVersion, err
}

const addHRAccessRole = `-- name: AddHRAccessRole :one
INSERT INTO hr_access_roles (concept_id, org_id, role_name, system_name, access_level, justification, review_interval_months)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, concept_id, org_id, role_name, system_name, access_level, justification, review_interval_months, created_at, updated_at
`

type AddHRAccessRoleParams struct {
	ConceptID            string `json:"concept_id"`
	OrgID                string `json:"org_id"`
	RoleName             string `json:"role_name"`
	SystemName           string `json:"system_name"`
	AccessLevel          string `json:"access_level"`
	Justification        string `json:"justification"`
	ReviewIntervalMonths int32  `json:"review_interval_months"`
}

func (q *Queries) AddHRAccessRole(ctx context.Context, arg AddHRAccessRoleParams) (HrAccessRoles, error) {
	row := q.db.QueryRow(ctx, addHRAccessRole,
		arg.ConceptID, arg.OrgID, arg.RoleName, arg.SystemName, arg.AccessLevel, arg.Justification, arg.ReviewIntervalMonths)
	var i HrAccessRoles
	err := row.Scan(&i.ID, &i.ConceptID, &i.OrgID, &i.RoleName, &i.SystemName, &i.AccessLevel, &i.Justification, &i.ReviewIntervalMonths, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const listHRAccessRoles = `-- name: ListHRAccessRoles :many
SELECT id, concept_id, org_id, role_name, system_name, access_level, justification, review_interval_months, created_at, updated_at
FROM hr_access_roles WHERE concept_id = $1 AND org_id = $2 ORDER BY role_name, system_name
`

type ListHRAccessRolesParams struct {
	ConceptID string `json:"concept_id"`
	OrgID     string `json:"org_id"`
}

func (q *Queries) ListHRAccessRoles(ctx context.Context, arg ListHRAccessRolesParams) ([]HrAccessRoles, error) {
	rows, err := q.db.Query(ctx, listHRAccessRoles, arg.ConceptID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HrAccessRoles{}
	for rows.Next() {
		var i HrAccessRoles
		if err := rows.Scan(&i.ID, &i.ConceptID, &i.OrgID, &i.RoleName, &i.SystemName, &i.AccessLevel, &i.Justification, &i.ReviewIntervalMonths, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const updateHRAccessRole = `-- name: UpdateHRAccessRole :one
UPDATE hr_access_roles
SET role_name = $3, system_name = $4, access_level = $5, justification = $6, review_interval_months = $7, updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, concept_id, org_id, role_name, system_name, access_level, justification, review_interval_months, created_at, updated_at
`

type UpdateHRAccessRoleParams struct {
	ID                   string `json:"id"`
	OrgID                string `json:"org_id"`
	RoleName             string `json:"role_name"`
	SystemName           string `json:"system_name"`
	AccessLevel          string `json:"access_level"`
	Justification        string `json:"justification"`
	ReviewIntervalMonths int32  `json:"review_interval_months"`
}

func (q *Queries) UpdateHRAccessRole(ctx context.Context, arg UpdateHRAccessRoleParams) (HrAccessRoles, error) {
	row := q.db.QueryRow(ctx, updateHRAccessRole,
		arg.ID, arg.OrgID, arg.RoleName, arg.SystemName, arg.AccessLevel, arg.Justification, arg.ReviewIntervalMonths)
	var i HrAccessRoles
	err := row.Scan(&i.ID, &i.ConceptID, &i.OrgID, &i.RoleName, &i.SystemName, &i.AccessLevel, &i.Justification, &i.ReviewIntervalMonths, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteHRAccessRole = `-- name: DeleteHRAccessRole :execrows
DELETE FROM hr_access_roles WHERE id = $1 AND org_id = $2
`

type DeleteHRAccessRoleParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeleteHRAccessRole(ctx context.Context, arg DeleteHRAccessRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHRAccessRole, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertHRAccessConceptVersion = `-- name: InsertHRAccessConceptVersion :one
INSERT INTO hr_access_concept_versions (concept_id, org_id, version_number, snapshot)
VALUES ($1, $2, $3, $4)
RETURNING id, concept_id, org_id, version_number, snapshot, created_at
`

type InsertHRAccessConceptVersionParams struct {
	ConceptID     string          `json:"concept_id"`
	OrgID         string          `json:"org_id"`
	VersionNumber int32           `json:"version_number"`
	Snapshot      json.RawMessage `json:"snapshot"`
}

func (q *Queries) InsertHRAccessConceptVersion(ctx context.Context, arg InsertHRAccessConceptVersionParams) (HrAccessConceptVersions, error) {
	row := q.db.QueryRow(ctx, insertHRAccessConceptVersion,
		arg.ConceptID, arg.OrgID, arg.VersionNumber, arg.Snapshot)
	var i HrAccessConceptVersions
	err := row.Scan(&i.ID, &i.ConceptID, &i.OrgID, &i.VersionNumber, &i.Snapshot, &i.CreatedAt)
	return i, err
}

const listHRAccessConceptVersions = `-- name: ListHRAccessConceptVersions :many
SELECT id, concept_id, org_id, version_number, created_at
FROM hr_access_concept_versions WHERE concept_id = $1 AND org_id = $2 ORDER BY version_number DESC
`

type ListHRAccessConceptVersionsParams struct {
	ConceptID string `json:"concept_id"`
	OrgID     string `json:"org_id"`
}

type ListHRAccessConceptVersionsRow struct {
	ID            string             `json:"id"`
	ConceptID     string             `json:"concept_id"`
	OrgID         string             `json:"org_id"`
	VersionNumber int32              `json:"version_number"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListHRAccessConceptVersions(ctx context.Context, arg ListHRAccessConceptVersionsParams) ([]ListHRAccessConceptVersionsRow, error) {
	rows, err := q.db.Query(ctx, listHRAccessConceptVersions, arg.ConceptID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHRAccessConceptVersionsRow{}
	for rows.Next() {
		var i ListHRAccessConceptVersionsRow
		if err := rows.Scan(&i.ID, &i.ConceptID, &i.OrgID, &i.VersionNumber, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getHRAccessConceptVersion = `-- name: GetHRAccessConceptVersion :one
SELECT id, concept_id, org_id, version_number, snapshot, created_at FROM hr_access_concept_versions
WHERE concept_id = $1 AND org_id = $2 AND version_number = $3
`

type GetHRAccessConceptVersionParams struct {
	ConceptID     string `json:"concept_id"`
	OrgID         string `json:"org_id"`
	VersionNumber int32  `json:"version_number"`
}

func (q *Queries) GetHRAccessConceptVersion(ctx context.Context, arg GetHRAccessConceptVersionParams) (HrAccessConceptVersions, error) {
	row := q.db.QueryRow(ctx, getHRAccessConceptVersion, arg.ConceptID, arg.OrgID, arg.VersionNumber)
	var i HrAccessConceptVersions
	err := row.Scan(&i.ID, &i.ConceptID, &i.OrgID, &i.VersionNumber, &i.Snapshot, &i.CreatedAt)
	return i, err
}
