// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vaktaware.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSREventsByType = `-- name: CountSREventsByType :one

SELECT COUNT(*) FROM sr_events
WHERE campaign_id = $1 AND type = $2
`

type CountSREventsByTypeParams struct {
	CampaignID string `json:"campaign_id"`
	Type       string `json:"type"`
}

// ── Tracking events ───────────────────────────────────────────────────────
func (q *Queries) CountSREventsByType(ctx context.Context, arg CountSREventsByTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSREventsByType, arg.CampaignID, arg.Type)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSRTargetsInGroup = `-- name: CountSRTargetsInGroup :one
SELECT COUNT(*) FROM sr_targets WHERE group_id = $1
`

func (q *Queries) CountSRTargetsInGroup(ctx context.Context, groupID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSRTargetsInGroup, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSRCampaign = `-- name: CreateSRCampaign :one

INSERT INTO sr_campaigns
       (org_id, name, template_id, group_id, landing_page_id,
        from_name, from_email, subject, scheduled_at, recurrence,
        track_opens, betriebsrat_mode, created_by)
VALUES ($1, $2,
        $8::uuid,
        $9::uuid,
        $10::uuid,
        $3, $4, $5,
        $11::timestamptz,
        $12::text,
        $6, $7,
        $13::uuid)
RETURNING id, org_id, name, status, template_id, group_id, landing_page_id,
          from_name, from_email, subject, scheduled_at, started_at,
          completed_at, recurrence, track_opens, betriebsrat_mode,
          created_by, created_at, updated_at
`

type CreateSRCampaignParams struct {
	OrgID           string             `json:"org_id"`
	Name            string             `json:"name"`
	FromName        string             `json:"from_name"`
	FromEmail       string             `json:"from_email"`
	Subject         string             `json:"subject"`
	TrackOpens      bool               `json:"track_opens"`
	BetriebsratMode bool               `json:"betriebsrat_mode"`
	TemplateID      pgtype.UUID        `json:"template_id"`
	GroupID         pgtype.UUID        `json:"group_id"`
	LandingPageID   pgtype.UUID        `json:"landing_page_id"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	Recurrence      pgtype.Text        `json:"recurrence"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
}

type CreateSRCampaignRow struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	Name            string             `json:"name"`
	Status          string             `json:"status"`
	TemplateID      pgtype.UUID        `json:"template_id"`
	GroupID         pgtype.UUID        `json:"group_id"`
	LandingPageID   pgtype.UUID        `json:"landing_page_id"`
	FromName        string             `json:"from_name"`
	FromEmail       string             `json:"from_email"`
	Subject         string             `json:"subject"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Recurrence      pgtype.Text        `json:"recurrence"`
	TrackOpens      bool               `json:"track_opens"`
	BetriebsratMode bool               `json:"betriebsrat_mode"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// ── Campaigns ─────────────────────────────────────────────────────────────
func (q *Queries) CreateSRCampaign(ctx context.Context, arg CreateSRCampaignParams) (CreateSRCampaignRow, error) {
	row := q.db.QueryRow(ctx, createSRCampaign,
		arg.OrgID,
		arg.Name,
		arg.FromName,
		arg.FromEmail,
		arg.Subject,
		arg.TrackOpens,
		arg.BetriebsratMode,
		arg.TemplateID,
		arg.GroupID,
		arg.LandingPageID,
		arg.ScheduledAt,
		arg.Recurrence,
		arg.CreatedBy,
	)
	var i CreateSRCampaignRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.TemplateID,
		&i.GroupID,
		&i.LandingPageID,
		&i.FromName,
		&i.FromEmail,
		&i.Subject,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Recurrence,
		&i.TrackOpens,
		&i.BetriebsratMode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSRLandingPage = `-- name: CreateSRLandingPage :one

INSERT INTO sr_landing_pages (org_id, name, html_content)
VALUES ($1, $2, $3)
RETURNING id, org_id, name, html_content, created_at
`

type CreateSRLandingPageParams struct {
	OrgID       string `json:"org_id"`
	Name        string `json:"name"`
	HtmlContent string `json:"html_content"`
}

// ── Landing pages ─────────────────────────────────────────────────────────
func (q *Queries) CreateSRLandingPage(ctx context.Context, arg CreateSRLandingPageParams) (SrLandingPages, error) {
	row := q.db.QueryRow(ctx, createSRLandingPage, arg.OrgID, arg.Name, arg.HtmlContent)
	var i SrLandingPages
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.HtmlContent,
		&i.CreatedAt,
	)
	return i, err
}

const createSRPhishReport = `-- name: CreateSRPhishReport :one
INSERT INTO sr_phish_reports
       (org_id, campaign_id, reporter_email, subject, sender, is_simulation)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, campaign_id, reporter_email, reported_at,
          subject, sender, is_simulation, created_at
`

type CreateSRPhishReportParams struct {
	OrgID         string      `json:"org_id"`
	CampaignID    pgtype.UUID `json:"campaign_id"`
	ReporterEmail string      `json:"reporter_email"`
	Subject       pgtype.Text `json:"subject"`
	Sender        pgtype.Text `json:"sender"`
	IsSimulation  bool        `json:"is_simulation"`
}

func (q *Queries) CreateSRPhishReport(ctx context.Context, arg CreateSRPhishReportParams) (SrPhishReports, error) {
	row := q.db.QueryRow(ctx, createSRPhishReport,
		arg.OrgID,
		arg.CampaignID,
		arg.ReporterEmail,
		arg.Subject,
		arg.Sender,
		arg.IsSimulation,
	)
	var i SrPhishReports
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CampaignID,
		&i.ReporterEmail,
		&i.ReportedAt,
		&i.Subject,
		&i.Sender,
		&i.IsSimulation,
		&i.CreatedAt,
	)
	return i, err
}

const createSRTargetGroup = `-- name: CreateSRTargetGroup :one

INSERT INTO sr_target_groups (org_id, name, source)
VALUES ($1, $2, $3)
RETURNING id, org_id, name, source, ad_ou, created_at
`

type CreateSRTargetGroupParams struct {
	OrgID  string `json:"org_id"`
	Name   string `json:"name"`
	Source string `json:"source"`
}

// ── Target groups ─────────────────────────────────────────────────────────
func (q *Queries) CreateSRTargetGroup(ctx context.Context, arg CreateSRTargetGroupParams) (SrTargetGroups, error) {
	row := q.db.QueryRow(ctx, createSRTargetGroup, arg.OrgID, arg.Name, arg.Source)
	var i SrTargetGroups
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Source,
		&i.AdOu,
		&i.CreatedAt,
	)
	return i, err
}

const createSRTemplate = `-- name: CreateSRTemplate :one


INSERT INTO sr_templates
       (org_id, name, subject, from_name, from_email, html_body, attack_type, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8::uuid)
RETURNING id, org_id, name, subject, from_name, from_email, html_body,
          attack_type, is_preset, created_by, created_at
`

type CreateSRTemplateParams struct {
	OrgID      string      `json:"org_id"`
	Name       string      `json:"name"`
	Subject    string      `json:"subject"`
	FromName   string      `json:"from_name"`
	FromEmail  string      `json:"from_email"`
	HtmlBody   string      `json:"html_body"`
	AttackType string      `json:"attack_type"`
	CreatedBy  pgtype.UUID `json:"created_by"`
}

// Vakt Aware (Phishing-Simulation & Awareness-Training)
//
// Tabellen-Präfix `sr_*` seit Migration 122 (vorher `pg_*` — kollidierte
// mit dem PostgreSQL-System-Katalog-Namespace und blockierte den
// sqlc-Parser, siehe ADR-0005).
// ── Templates ─────────────────────────────────────────────────────────────
func (q *Queries) CreateSRTemplate(ctx context.Context, arg CreateSRTemplateParams) (SrTemplates, error) {
	row := q.db.QueryRow(ctx, createSRTemplate,
		arg.OrgID,
		arg.Name,
		arg.Subject,
		arg.FromName,
		arg.FromEmail,
		arg.HtmlBody,
		arg.AttackType,
		arg.CreatedBy,
	)
	var i SrTemplates
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Subject,
		&i.FromName,
		&i.FromEmail,
		&i.HtmlBody,
		&i.AttackType,
		&i.IsPreset,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createSRTrackingEvent = `-- name: CreateSRTrackingEvent :exec
INSERT INTO sr_events
       (org_id, campaign_id, target_id, department, type,
        tracking_token, ip_address, user_agent)
VALUES ($1, $2,
        $5::uuid,
        $6::text,
        $3, $4,
        $7::text,
        $8::text)
`

type CreateSRTrackingEventParams struct {
	OrgID         string      `json:"org_id"`
	CampaignID    string      `json:"campaign_id"`
	Type          string      `json:"type"`
	TrackingToken string      `json:"tracking_token"`
	TargetID      pgtype.UUID `json:"target_id"`
	Department    pgtype.Text `json:"department"`
	IpAddress     pgtype.Text `json:"ip_address"`
	UserAgent     pgtype.Text `json:"user_agent"`
}

func (q *Queries) CreateSRTrackingEvent(ctx context.Context, arg CreateSRTrackingEventParams) error {
	_, err := q.db.Exec(ctx, createSRTrackingEvent,
		arg.OrgID,
		arg.CampaignID,
		arg.Type,
		arg.TrackingToken,
		arg.TargetID,
		arg.Department,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const createSRTrainingModule = `-- name: CreateSRTrainingModule :one

INSERT INTO sr_training_modules
       (org_id, title, type, attack_type, content_url,
        duration_seconds, passing_score, questions, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9::uuid)
RETURNING id, org_id, title, type, attack_type, content_url,
          duration_seconds, passing_score, questions, created_by, created_at
`

type CreateSRTrainingModuleParams struct {
	OrgID           string      `json:"org_id"`
	Title           string      `json:"title"`
	Type            string      `json:"type"`
	AttackType      string      `json:"attack_type"`
	ContentUrl      string      `json:"content_url"`
	DurationSeconds int32       `json:"duration_seconds"`
	PassingScore    int32       `json:"passing_score"`
	Questions       []byte      `json:"questions"`
	CreatedBy       pgtype.UUID `json:"created_by"`
}

// ── Training modules ──────────────────────────────────────────────────────
func (q *Queries) CreateSRTrainingModule(ctx context.Context, arg CreateSRTrainingModuleParams) (SrTrainingModules, error) {
	row := q.db.QueryRow(ctx, createSRTrainingModule,
		arg.OrgID,
		arg.Title,
		arg.Type,
		arg.AttackType,
		arg.ContentUrl,
		arg.DurationSeconds,
		arg.PassingScore,
		arg.Questions,
		arg.CreatedBy,
	)
	var i SrTrainingModules
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.Type,
		&i.AttackType,
		&i.ContentUrl,
		&i.DurationSeconds,
		&i.PassingScore,
		&i.Questions,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSRTargetGroup = `-- name: DeleteSRTargetGroup :execrows
DELETE FROM sr_target_groups
WHERE id = $1 AND org_id = $2
`

type DeleteSRTargetGroupParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

// Cascades to sr_targets (ON DELETE CASCADE); sr_campaigns.group_id is SET NULL.
func (q *Queries) DeleteSRTargetGroup(ctx context.Context, arg DeleteSRTargetGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSRTargetGroup, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findActiveSRCampaignForReporter = `-- name: FindActiveSRCampaignForReporter :one
SELECT c.id
FROM sr_campaigns c
JOIN sr_target_groups tg ON tg.id = c.group_id
JOIN sr_targets t ON t.group_id = tg.id AND t.org_id = c.org_id
WHERE c.org_id = $1
  AND c.status = 'running'
  AND lower(t.email) = lower($2::text)
LIMIT 1
`

type FindActiveSRCampaignForReporterParams struct {
	OrgID         string `json:"org_id"`
	ReporterEmail string `json:"reporter_email"`
}

func (q *Queries) FindActiveSRCampaignForReporter(ctx context.Context, arg FindActiveSRCampaignForReporterParams) (string, error) {
	row := q.db.QueryRow(ctx, findActiveSRCampaignForReporter, arg.OrgID, arg.ReporterEmail)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getOrgByPhishReportToken = `-- name: GetOrgByPhishReportToken :one

SELECT id FROM organizations WHERE phish_report_token = $1
`

// ── Phish-Button (Feature 5) ──────────────────────────────────────────────
func (q *Queries) GetOrgByPhishReportToken(ctx context.Context, phishReportToken pgtype.Text) (string, error) {
	row := q.db.QueryRow(ctx, getOrgByPhishReportToken, phishReportToken)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getSRAssignment = `-- name: GetSRAssignment :one
SELECT id, org_id, module_id, target_id, department, due_date,
       is_overdue, created_at
FROM sr_assignments
WHERE id = $1 AND org_id = $2
`

type GetSRAssignmentParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetSRAssignment(ctx context.Context, arg GetSRAssignmentParams) (SrAssignments, error) {
	row := q.db.QueryRow(ctx, getSRAssignment, arg.ID, arg.OrgID)
	var i SrAssignments
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ModuleID,
		&i.TargetID,
		&i.Department,
		&i.DueDate,
		&i.IsOverdue,
		&i.CreatedAt,
	)
	return i, err
}

const getSRCampaign = `-- name: GetSRCampaign :one
SELECT id, org_id, name, status, template_id, group_id, landing_page_id,
       from_name, from_email, subject, scheduled_at, started_at,
       completed_at, recurrence, track_opens, betriebsrat_mode,
       created_by, created_at, updated_at
FROM sr_campaigns
WHERE id = $1 AND org_id = $2
`

type GetSRCampaignParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

type GetSRCampaignRow struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	Name            string             `json:"name"`
	Status          string             `json:"status"`
	TemplateID      pgtype.UUID        `json:"template_id"`
	GroupID         pgtype.UUID        `json:"group_id"`
	LandingPageID   pgtype.UUID        `json:"landing_page_id"`
	FromName        string             `json:"from_name"`
	FromEmail       string             `json:"from_email"`
	Subject         string             `json:"subject"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Recurrence      pgtype.Text        `json:"recurrence"`
	TrackOpens      bool               `json:"track_opens"`
	BetriebsratMode bool               `json:"betriebsrat_mode"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSRCampaign(ctx context.Context, arg GetSRCampaignParams) (GetSRCampaignRow, error) {
	row := q.db.QueryRow(ctx, getSRCampaign, arg.ID, arg.OrgID)
	var i GetSRCampaignRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.TemplateID,
		&i.GroupID,
		&i.LandingPageID,
		&i.FromName,
		&i.FromEmail,
		&i.Subject,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Recurrence,
		&i.TrackOpens,
		&i.BetriebsratMode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSRCampaignByTrackingToken = `-- name: GetSRCampaignByTrackingToken :one
SELECT c.id, c.org_id, c.name, c.status, c.template_id, c.group_id,
       c.landing_page_id, c.from_name, c.from_email, c.subject,
       c.scheduled_at, c.started_at, c.completed_at, c.recurrence,
       c.track_opens, c.betriebsrat_mode, c.created_by, c.created_at,
       c.updated_at
FROM sr_campaigns c
JOIN sr_events e ON e.campaign_id = c.id
WHERE e.tracking_token = $1
LIMIT 1
`

type GetSRCampaignByTrackingTokenRow struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	Name            string             `json:"name"`
	Status          string             `json:"status"`
	TemplateID      pgtype.UUID        `json:"template_id"`
	GroupID         pgtype.UUID        `json:"group_id"`
	LandingPageID   pgtype.UUID        `json:"landing_page_id"`
	FromName        string             `json:"from_name"`
	FromEmail       string             `json:"from_email"`
	Subject         string             `json:"subject"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Recurrence      pgtype.Text        `json:"recurrence"`
	TrackOpens      bool               `json:"track_opens"`
	BetriebsratMode bool               `json:"betriebsrat_mode"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSRCampaignByTrackingToken(ctx context.Context, trackingToken string) (GetSRCampaignByTrackingTokenRow, error) {
	row := q.db.QueryRow(ctx, getSRCampaignByTrackingToken, trackingToken)
	var i GetSRCampaignByTrackingTokenRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.TemplateID,
		&i.GroupID,
		&i.LandingPageID,
		&i.FromName,
		&i.FromEmail,
		&i.Subject,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Recurrence,
		&i.TrackOpens,
		&i.BetriebsratMode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSRCampaignGroupID = `-- name: GetSRCampaignGroupID :one
SELECT group_id FROM sr_campaigns WHERE id = $1
`

func (q *Queries) GetSRCampaignGroupID(ctx context.Context, id string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getSRCampaignGroupID, id)
	var group_id pgtype.UUID
	err := row.Scan(&group_id)
	return group_id, err
}

const getSRCompletionByAssignment = `-- name: GetSRCompletionByAssignment :one
SELECT id, org_id, assignment_id, score, passed, completed_at
FROM sr_completions
WHERE assignment_id = $1 AND org_id = $2
LIMIT 1
`

type GetSRCompletionByAssignmentParams struct {
	AssignmentID string `json:"assignment_id"`
	OrgID        string `json:"org_id"`
}

func (q *Queries) GetSRCompletionByAssignment(ctx context.Context, arg GetSRCompletionByAssignmentParams) (SrCompletions, error) {
	row := q.db.QueryRow(ctx, getSRCompletionByAssignment, arg.AssignmentID, arg.OrgID)
	var i SrCompletions
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AssignmentID,
		&i.Score,
		&i.Passed,
		&i.CompletedAt,
	)
	return i, err
}

const getSRLandingPageForCampaign = `-- name: GetSRLandingPageForCampaign :one
SELECT lp.id, lp.org_id, lp.name, lp.html_content, lp.created_at
FROM sr_landing_pages lp
JOIN sr_campaigns c ON c.landing_page_id = lp.id
WHERE c.id = $1
`

func (q *Queries) GetSRLandingPageForCampaign(ctx context.Context, id string) (SrLandingPages, error) {
	row := q.db.QueryRow(ctx, getSRLandingPageForCampaign, id)
	var i SrLandingPages
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.HtmlContent,
		&i.CreatedAt,
	)
	return i, err
}

const getSRPhishReportStats = `-- name: GetSRPhishReportStats :one
SELECT
    COUNT(*)::bigint                                      AS total,
    COUNT(*) FILTER (WHERE is_simulation = TRUE)::bigint  AS simulations,
    COUNT(*) FILTER (WHERE is_simulation = FALSE)::bigint AS real_threats
FROM sr_phish_reports
WHERE org_id = $1
`

type GetSRPhishReportStatsRow struct {
	Total       int64 `json:"total"`
	Simulations int64 `json:"simulations"`
	RealThreats int64 `json:"real_threats"`
}

func (q *Queries) GetSRPhishReportStats(ctx context.Context, orgID string) (GetSRPhishReportStatsRow, error) {
	row := q.db.QueryRow(ctx, getSRPhishReportStats, orgID)
	var i GetSRPhishReportStatsRow
	err := row.Scan(&i.Total, &i.Simulations, &i.RealThreats)
	return i, err
}

const getSRTargetByEmail = `-- name: GetSRTargetByEmail :one
SELECT id, org_id, group_id, email, first_name, last_name, department,
       is_bounced, created_at
FROM sr_targets
WHERE org_id = $1 AND email = $2
ORDER BY created_at ASC
LIMIT 1
`

type GetSRTargetByEmailParams struct {
	OrgID string `json:"org_id"`
	Email string `json:"email"`
}

// Used to resolve "assign by email" to an existing target regardless of
// which group it lives in, before falling back to creating a new one.
func (q *Queries) GetSRTargetByEmail(ctx context.Context, arg GetSRTargetByEmailParams) (SrTargets, error) {
	row := q.db.QueryRow(ctx, getSRTargetByEmail, arg.OrgID, arg.Email)
	var i SrTargets
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GroupID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Department,
		&i.IsBounced,
		&i.CreatedAt,
	)
	return i, err
}

const getSRTemplate = `-- name: GetSRTemplate :one
SELECT id, org_id, name, subject, from_name, from_email, html_body,
       attack_type, is_preset, created_by, created_at
FROM sr_templates
WHERE id = $1 AND (org_id = $2 OR is_preset = TRUE)
`

type GetSRTemplateParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetSRTemplate(ctx context.Context, arg GetSRTemplateParams) (SrTemplates, error) {
	row := q.db.QueryRow(ctx, getSRTemplate, arg.ID, arg.OrgID)
	var i SrTemplates
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Subject,
		&i.FromName,
		&i.FromEmail,
		&i.HtmlBody,
		&i.AttackType,
		&i.IsPreset,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getSRTrainingModuleByAttackType = `-- name: GetSRTrainingModuleByAttackType :one
SELECT id, org_id, title, type, attack_type, content_url,
       duration_seconds, passing_score, questions, created_by, created_at
FROM sr_training_modules
WHERE org_id = $1 AND attack_type = $2
LIMIT 1
`

type GetSRTrainingModuleByAttackTypeParams struct {
	OrgID      string `json:"org_id"`
	AttackType string `json:"attack_type"`
}

func (q *Queries) GetSRTrainingModuleByAttackType(ctx context.Context, arg GetSRTrainingModuleByAttackTypeParams) (SrTrainingModules, error) {
	row := q.db.QueryRow(ctx, getSRTrainingModuleByAttackType, arg.OrgID, arg.AttackType)
	var i SrTrainingModules
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.Type,
		&i.AttackType,
		&i.ContentUrl,
		&i.DurationSeconds,
		&i.PassingScore,
		&i.Questions,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getSRTrainingModuleByID = `-- name: GetSRTrainingModuleByID :one
SELECT id, org_id, title, type, attack_type, content_url,
       duration_seconds, passing_score, questions, created_by, created_at
FROM sr_training_modules
WHERE id = $1 AND org_id = $2
`

type GetSRTrainingModuleByIDParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetSRTrainingModuleByID(ctx context.Context, arg GetSRTrainingModuleByIDParams) (SrTrainingModules, error) {
	row := q.db.QueryRow(ctx, getSRTrainingModuleByID, arg.ID, arg.OrgID)
	var i SrTrainingModules
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.Type,
		&i.AttackType,
		&i.ContentUrl,
		&i.DurationSeconds,
		&i.PassingScore,
		&i.Questions,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listSRAssignments = `-- name: ListSRAssignments :many
SELECT id, org_id, module_id, target_id, department, due_date,
       is_overdue, created_at
FROM sr_assignments
WHERE org_id = $1
ORDER BY due_date
LIMIT 500
`

func (q *Queries) ListSRAssignments(ctx context.Context, orgID string) ([]SrAssignments, error) {
	rows, err := q.db.Query(ctx, listSRAssignments, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SrAssignments{}
	for rows.Next() {
		var i SrAssignments
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ModuleID,
			&i.TargetID,
			&i.Department,
			&i.DueDate,
			&i.IsOverdue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSRAssignmentsByModule = `-- name: ListSRAssignmentsByModule :many
SELECT a.id, a.due_date, a.created_at,
       t.email AS user_email,
       c.score, c.passed, c.completed_at
FROM sr_assignments a
LEFT JOIN sr_targets t ON t.id = a.target_id
LEFT JOIN sr_completions c ON c.assignment_id = a.id
WHERE a.org_id = $1 AND a.module_id = $2
ORDER BY a.created_at DESC
LIMIT 500
`

type ListSRAssignmentsByModuleParams struct {
	OrgID    string `json:"org_id"`
	ModuleID string `json:"module_id"`
}

type ListSRAssignmentsByModuleRow struct {
	ID          string             `json:"id"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UserEmail   pgtype.Text        `json:"user_email"`
	Score       pgtype.Int4        `json:"score"`
	Passed      pgtype.Bool        `json:"passed"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

// Per-assignment detail for a single module: target email (NULL if the
// assignment has no target or the target was later deleted — target_id is
// ON DELETE SET NULL) plus completion outcome (NULL = still "assigned").
func (q *Queries) ListSRAssignmentsByModule(ctx context.Context, arg ListSRAssignmentsByModuleParams) ([]ListSRAssignmentsByModuleRow, error) {
	rows, err := q.db.Query(ctx, listSRAssignmentsByModule, arg.OrgID, arg.ModuleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSRAssignmentsByModuleRow{}
	for rows.Next() {
		var i ListSRAssignmentsByModuleRow
		if err := rows.Scan(
			&i.ID,
			&i.DueDate,
			&i.CreatedAt,
			&i.UserEmail,
			&i.Score,
			&i.Passed,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSRCampaigns = `-- name: ListSRCampaigns :many
SELECT id, org_id, name, status, template_id, group_id, landing_page_id,
       from_name, from_email, subject, scheduled_at, started_at,
       completed_at, recurrence, track_opens, betriebsrat_mode,
       created_by, created_at, updated_at
FROM sr_campaigns
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT 500
`

type ListSRCampaignsRow struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	Name            string             `json:"name"`
	Status          string             `json:"status"`
	TemplateID      pgtype.UUID        `json:"template_id"`
	GroupID         pgtype.UUID        `json:"group_id"`
	LandingPageID   pgtype.UUID        `json:"landing_page_id"`
	FromName        string             `json:"from_name"`
	FromEmail       string             `json:"from_email"`
	Subject         string             `json:"subject"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Recurrence      pgtype.Text        `json:"recurrence"`
	TrackOpens      bool               `json:"track_opens"`
	BetriebsratMode bool               `json:"betriebsrat_mode"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListSRCampaigns(ctx context.Context, orgID string) ([]ListSRCampaignsRow, error) {
	rows, err := q.db.Query(ctx, listSRCampaigns, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSRCampaignsRow{}
	for rows.Next() {
		var i ListSRCampaignsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Status,
			&i.TemplateID,
			&i.GroupID,
			&i.LandingPageID,
			&i.FromName,
			&i.FromEmail,
			&i.Subject,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Recurrence,
			&i.TrackOpens,
			&i.BetriebsratMode,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSRCompletedAssignments = `-- name: ListSRCompletedAssignments :many
SELECT a.id, a.org_id, a.module_id, a.target_id, a.department, a.due_date,
       a.is_overdue, a.created_at
FROM sr_assignments a
WHERE a.org_id = $1
  AND a.id IN (SELECT assignment_id FROM sr_completions)
ORDER BY a.due_date
LIMIT 500
`

func (q *Queries) ListSRCompletedAssignments(ctx context.Context, orgID string) ([]SrAssignments, error) {
	rows, err := q.db.Query(ctx, listSRCompletedAssignments, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SrAssignments{}
	for rows.Next() {
		var i SrAssignments
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ModuleID,
			&i.TargetID,
			&i.Department,
			&i.DueDate,
			&i.IsOverdue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSRLandingPages = `-- name: ListSRLandingPages :many
SELECT id, org_id, name, html_content, created_at
FROM sr_landing_pages
WHERE org_id = $1
ORDER BY name
LIMIT 500
`

func (q *Queries) ListSRLandingPages(ctx context.Context, orgID string) ([]SrLandingPages, error) {
	rows, err := q.db.Query(ctx, listSRLandingPages, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SrLandingPages{}
	for rows.Next() {
		var i SrLandingPages
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.HtmlContent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSROverdueAssignments = `-- name: ListSROverdueAssignments :many
SELECT id, org_id, module_id, target_id, department, due_date,
       is_overdue, created_at
FROM sr_assignments
WHERE org_id = $1 AND is_overdue = TRUE
ORDER BY due_date
LIMIT 500
`

func (q *Queries) ListSROverdueAssignments(ctx context.Context, orgID string) ([]SrAssignments, error) {
	rows, err := q.db.Query(ctx, listSROverdueAssignments, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SrAssignments{}
	for rows.Next() {
		var i SrAssignments
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ModuleID,
			&i.TargetID,
			&i.Department,
			&i.DueDate,
			&i.IsOverdue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSRPhishReports = `-- name: ListSRPhishReports :many
SELECT id, org_id, campaign_id, reporter_email, reported_at,
       subject, sender, is_simulation, created_at
FROM sr_phish_reports
WHERE org_id = $1
ORDER BY reported_at DESC
LIMIT 500
`

func (q *Queries) ListSRPhishReports(ctx context.Context, orgID string) ([]SrPhishReports, error) {
	rows, err := q.db.Query(ctx, listSRPhishReports, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SrPhishReports{}
	for rows.Next() {
		var i SrPhishReports
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CampaignID,
			&i.ReporterEmail,
			&i.ReportedAt,
			&i.Subject,
			&i.Sender,
			&i.IsSimulation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSRTargetGroups = `-- name: ListSRTargetGroups :many
SELECT id, org_id, name, source, ad_ou, created_at
FROM sr_target_groups
WHERE org_id = $1
ORDER BY name
LIMIT 500
`

func (q *Queries) ListSRTargetGroups(ctx context.Context, orgID string) ([]SrTargetGroups, error) {
	rows, err := q.db.Query(ctx, listSRTargetGroups, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SrTargetGroups{}
	for rows.Next() {
		var i SrTargetGroups
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Source,
			&i.AdOu,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSRTargets = `-- name: ListSRTargets :many
SELECT id, org_id, group_id, email, first_name, last_name, department,
       is_bounced, created_at
FROM sr_targets
WHERE group_id = $1 AND org_id = $2
ORDER BY email
LIMIT 500
`

type ListSRTargetsParams struct {
	GroupID string `json:"group_id"`
	OrgID   string `json:"org_id"`
}

func (q *Queries) ListSRTargets(ctx context.Context, arg ListSRTargetsParams) ([]SrTargets, error) {
	rows, err := q.db.Query(ctx, listSRTargets, arg.GroupID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SrTargets{}
	for rows.Next() {
		var i SrTargets
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.GroupID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Department,
			&i.IsBounced,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSRTemplates = `-- name: ListSRTemplates :many
SELECT id, org_id, name, subject, from_name, from_email, html_body,
       attack_type, is_preset, created_by, created_at
FROM sr_templates
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT 500
`

func (q *Queries) ListSRTemplates(ctx context.Context, orgID string) ([]SrTemplates, error) {
	rows, err := q.db.Query(ctx, listSRTemplates, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SrTemplates{}
	for rows.Next() {
		var i SrTemplates
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Subject,
			&i.FromName,
			&i.FromEmail,
			&i.HtmlBody,
			&i.AttackType,
			&i.IsPreset,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSRTrainingModules = `-- name: ListSRTrainingModules :many
SELECT id, org_id, title, type, attack_type, content_url,
       duration_seconds, passing_score, questions, created_by, created_at
FROM sr_training_modules
WHERE org_id = $1
ORDER BY title
LIMIT 500
`

func (q *Queries) ListSRTrainingModules(ctx context.Context, orgID string) ([]SrTrainingModules, error) {
	rows, err := q.db.Query(ctx, listSRTrainingModules, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SrTrainingModules{}
	for rows.Next() {
		var i SrTrainingModules
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Title,
			&i.Type,
			&i.AttackType,
			&i.ContentUrl,
			&i.DurationSeconds,
			&i.PassingScore,
			&i.Questions,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrgPhishReportToken = `-- name: SetOrgPhishReportToken :exec
UPDATE organizations SET phish_report_token = $1 WHERE id = $2
`

type SetOrgPhishReportTokenParams struct {
	PhishReportToken pgtype.Text `json:"phish_report_token"`
	ID               string      `json:"id"`
}

func (q *Queries) SetOrgPhishReportToken(ctx context.Context, arg SetOrgPhishReportTokenParams) error {
	_, err := q.db.Exec(ctx, setOrgPhishReportToken, arg.PhishReportToken, arg.ID)
	return err
}

const setSRCampaignCompleted = `-- name: SetSRCampaignCompleted :exec
UPDATE sr_campaigns
SET status = 'completed', completed_at = NOW(), updated_at = NOW()
WHERE id = $1 AND org_id = $2
`

type SetSRCampaignCompletedParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) SetSRCampaignCompleted(ctx context.Context, arg SetSRCampaignCompletedParams) error {
	_, err := q.db.Exec(ctx, setSRCampaignCompleted, arg.ID, arg.OrgID)
	return err
}

const updateSRCampaignStatus = `-- name: UpdateSRCampaignStatus :exec
UPDATE sr_campaigns
SET status = $1, updated_at = NOW()
WHERE id = $2 AND org_id = $3
`

type UpdateSRCampaignStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
	OrgID  string `json:"org_id"`
}

func (q *Queries) UpdateSRCampaignStatus(ctx context.Context, arg UpdateSRCampaignStatusParams) error {
	_, err := q.db.Exec(ctx, updateSRCampaignStatus, arg.Status, arg.ID, arg.OrgID)
	return err
}

// ── Assignments ───────────────────────────────────────────────────────────
//
// sr_assignments.UNIQUE(module_id, target_id) is DEFERRABLE INITIALLY
// DEFERRED, and Postgres does not allow ON CONFLICT against a deferrable
// constraint as the arbiter — upserting is an explicit find-then-insert-or-
// update instead of a single ON CONFLICT statement.

const findSRAssignmentByTarget = `-- name: FindSRAssignmentByTarget :one
SELECT id, org_id, module_id, target_id, department, due_date,
       is_overdue, created_at
FROM sr_assignments
WHERE org_id = $1 AND module_id = $2 AND target_id = $3::uuid
LIMIT 1
`

type FindSRAssignmentByTargetParams struct {
	OrgID    string      `json:"org_id"`
	ModuleID string      `json:"module_id"`
	TargetID pgtype.UUID `json:"target_id"`
}

func (q *Queries) FindSRAssignmentByTarget(ctx context.Context, arg FindSRAssignmentByTargetParams) (SrAssignments, error) {
	row := q.db.QueryRow(ctx, findSRAssignmentByTarget, arg.OrgID, arg.ModuleID, arg.TargetID)
	var i SrAssignments
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ModuleID,
		&i.TargetID,
		&i.Department,
		&i.DueDate,
		&i.IsOverdue,
		&i.CreatedAt,
	)
	return i, err
}

const insertSRAssignment = `-- name: InsertSRAssignment :one
INSERT INTO sr_assignments (org_id, module_id, target_id, department, due_date)
VALUES ($1, $2,
        $4::uuid,
        $5::text,
        $3)
RETURNING id, org_id, module_id, target_id, department, due_date,
          is_overdue, created_at
`

type InsertSRAssignmentParams struct {
	OrgID      string             `json:"org_id"`
	ModuleID   string             `json:"module_id"`
	DueDate    pgtype.Timestamptz `json:"due_date"`
	TargetID   pgtype.UUID        `json:"target_id"`
	Department pgtype.Text        `json:"department"`
}

func (q *Queries) InsertSRAssignment(ctx context.Context, arg InsertSRAssignmentParams) (SrAssignments, error) {
	row := q.db.QueryRow(ctx, insertSRAssignment,
		arg.OrgID,
		arg.ModuleID,
		arg.DueDate,
		arg.TargetID,
		arg.Department,
	)
	var i SrAssignments
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ModuleID,
		&i.TargetID,
		&i.Department,
		&i.DueDate,
		&i.IsOverdue,
		&i.CreatedAt,
	)
	return i, err
}

const updateSRAssignmentDueDate = `-- name: UpdateSRAssignmentDueDate :one
UPDATE sr_assignments SET due_date = GREATEST($2, due_date)
WHERE id = $1
RETURNING id, org_id, module_id, target_id, department, due_date,
          is_overdue, created_at
`

type UpdateSRAssignmentDueDateParams struct {
	ID      string             `json:"id"`
	DueDate pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) UpdateSRAssignmentDueDate(ctx context.Context, arg UpdateSRAssignmentDueDateParams) (SrAssignments, error) {
	row := q.db.QueryRow(ctx, updateSRAssignmentDueDate, arg.ID, arg.DueDate)
	var i SrAssignments
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ModuleID,
		&i.TargetID,
		&i.Department,
		&i.DueDate,
		&i.IsOverdue,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSRCompletion = `-- name: UpsertSRCompletion :one
INSERT INTO sr_completions (org_id, assignment_id, score, passed)
VALUES ($1, $2, $4::int, $3)
ON CONFLICT (assignment_id) DO UPDATE
   SET score        = EXCLUDED.score,
       passed       = EXCLUDED.passed,
       completed_at = NOW()
RETURNING id, org_id, assignment_id, score, passed, completed_at
`

type UpsertSRCompletionParams struct {
	OrgID        string      `json:"org_id"`
	AssignmentID string      `json:"assignment_id"`
	Passed       bool        `json:"passed"`
	Score        pgtype.Int4 `json:"score"`
}

func (q *Queries) UpsertSRCompletion(ctx context.Context, arg UpsertSRCompletionParams) (SrCompletions, error) {
	row := q.db.QueryRow(ctx, upsertSRCompletion,
		arg.OrgID,
		arg.AssignmentID,
		arg.Passed,
		arg.Score,
	)
	var i SrCompletions
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AssignmentID,
		&i.Score,
		&i.Passed,
		&i.CompletedAt,
	)
	return i, err
}

const upsertSRTarget = `-- name: UpsertSRTarget :one

INSERT INTO sr_targets (org_id, group_id, email, first_name, last_name, department)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (group_id, email) DO UPDATE
   SET first_name = EXCLUDED.first_name,
       last_name  = EXCLUDED.last_name,
       department = EXCLUDED.department
RETURNING id, org_id, group_id, email, first_name, last_name, department,
          is_bounced, created_at
`

type UpsertSRTargetParams struct {
	OrgID      string `json:"org_id"`
	GroupID    string `json:"group_id"`
	Email      string `json:"email"`
	FirstName  string `json:"first_name"`
	LastName   string `json:"last_name"`
	Department string `json:"department"`
}

// ── Targets ───────────────────────────────────────────────────────────────
func (q *Queries) UpsertSRTarget(ctx context.Context, arg UpsertSRTargetParams) (SrTargets, error) {
	row := q.db.QueryRow(ctx, upsertSRTarget,
		arg.OrgID,
		arg.GroupID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Department,
	)
	var i SrTargets
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GroupID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Department,
		&i.IsBounced,
		&i.CreatedAt,
	)
	return i, err
}

const getSROrganizationName = `-- name: GetSROrganizationName :one
SELECT name FROM organizations WHERE id = $1::uuid
`

func (q *Queries) GetSROrganizationName(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getSROrganizationName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getSRTargetEmail = `-- name: GetSRTargetEmail :one
SELECT email FROM sr_targets WHERE id = $1
`

func (q *Queries) GetSRTargetEmail(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getSRTargetEmail, id)
	var email string
	err := row.Scan(&email)
	return email, err
}
